--[[
description: 战斗单元骨骼序列帧配置
author: zhenhui
date: 2016/12/5
]]--

local RAFU_Cfg_Bone = {
	['B_F_PrismTankDown'] ={--光陵坦克
	     name = "Army_PrismTankCar",
	     plist = "Army_PrismTank_Action.color.plist",
	     pic = "Army_PrismTank_Action.color.png",
	   	 fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = false,
	},
	['B_F_PrismTankUp'] ={--光陵坦克
	     name = "Army_PrismTankGun",
	     plist = "Army_PrismTank_Action.color.plist",
	     pic = "Army_PrismTank_Action.color.png",
	    fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 15,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 4,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = false,
	},
	['B_F_GrizzlyTankDown'] ={--灰熊坦克
	     name = "Army_GrizzlyTankCar",
	     plist = "Army_GrizzlyTank_Action.plist",
	     pic = "Army_GrizzlyTank_Action.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
			[ACTION_TYPE.ACTION_ROCK_LEFT] =5,
			[ACTION_TYPE.ACTION_ROCK_RIGHT] = 5,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_ROCK_LEFT] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_ROCK_RIGHT] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = false,
	},
	['B_F_GrizzlyTankUp'] ={--灰熊坦克
	     name = "Army_GrizzlyTankGun",
	     plist = "Army_GrizzlyTank_Action.plist",
	     pic = "Army_GrizzlyTank_Action.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_SIXTEEN_DIR_OBJ,

		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = false,
	},
	['B_F_InfantryFightingVehicleDown'] ={--多功能步兵坦克
	     name = "Army_InfantryFightingVehicleCar",
	     plist = "Army_InfantryFightingVehicle_Action.color.plist",
	     pic = "Army_InfantryFightingVehicle_Action.color.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = false,
	},
	['B_F_InfantryFightingVehicleUp'] ={--多功能步兵坦克
	     name = "Army_InfantryFightingVehicleGun",
	     plist = "Army_InfantryFightingVehicle_Action.color.plist",
	     pic = "Army_InfantryFightingVehicle_Action.color.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = false,
	},
	['B_F_RhinoTankUp'] ={--犀牛坦克
	    
	     name = "Army_RhinoTankGun",
	     plist = "Army_RhinoTank_Action.plist",
	     pic = "Army_RhinoTank_Action.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = false,
	},
	['B_F_RhinoTankDown'] ={--犀牛坦克
	     name = "Army_RhinoTankCar",
	     plist = "Army_RhinoTank_Action.plist",
	     pic = "Army_RhinoTank_Action.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = false,
	},
	['B_F_TeslaTankUp'] ={--磁暴坦克
	    
	     name = "Army_TeslaTankGun",
	     plist = "Army_TeslaTank_Action.color.plist",
	     pic = "Army_TeslaTank_Action.color.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = false,
	},
	['B_F_TeslaTankDown'] ={--磁暴坦克
	     name = "Army_TeslaTankCar",
	     plist = "Army_TeslaTank_Action.color.plist",
	     pic = "Army_TeslaTank_Action.color.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = false,
	},
	['B_F_ApocalypseTankUp'] ={--天启坦克
	    
	     name = "Army_ApocalypseTankGun",
	     plist = "Army_ApocalypseTank_Action.color.plist",
	     pic = "Army_ApocalypseTank_Action.color.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = false,
	},
	['B_F_ApocalypseTankDown'] ={--天启坦克
	     name = "Army_ApocalypseTankCar",
	     plist = "Army_ApocalypseTank_Action.color.plist",
	     pic = "Army_ApocalypseTank_Action.color.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = false,
	},
	['B_F_TankDestroyerDown'] ={--坦克杀手
	     name = "Army_TankDestroyer",
	     plist = "Army_TankDestroyer_Action.plist",
	     pic = "Army_TankDestroyer_Action.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = false,
	},
	['B_F_FreezerTank'] ={--冷冻车
	     name = "Army_FreezerTank",
	     plist = "Army_FreezerTank_Action.plist",
	     pic = "Army_FreezerTank_Action.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = false,
	},
	['B_F_MirageTankDown'] ={--幻影坦克
	     name = "Army_MirageTank",
	     plist = "Army_MirageTank_Action.plist",
	     pic = "Army_MirageTank_Action.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = false,
	},
	['B_F_BattleFortressDown'] ={--战斗要塞
	     name = "Army_BattleFortress",
	     plist = "Army_BattleFortress_Action.plist",
	     pic = "Army_BattleFortress_Action.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = false,
	},
	['B_F_AmericanSoldier'] ={--美国大兵
	     name = "Army_AmericanSoldier",
	     plist = "Army_AmericanSoldier_Action.color.plist",
	     pic = "Army_AmericanSoldier_Action.color.png",
	    fps = {
			[ACTION_TYPE.ACTION_IDLE] = 8,
			[ACTION_TYPE.ACTION_ATTACK] = 25,
			[ACTION_TYPE.ACTION_RUN] = 15,
			[ACTION_TYPE.ACTION_DEATH] = 20,
			[ACTION_TYPE.ACTION_SIT_IDLE] = 20,
			[ACTION_TYPE.ACTION_SIT_ATTACK] = 20,
			[ACTION_TYPE.ACTION_SIT_DOWN] = 20,
			[ACTION_TYPE.ACTION_SIT_UP] = 20,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 6,
			[ACTION_TYPE.ACTION_RUN] = 6,
			[ACTION_TYPE.ACTION_DEATH] = 15,
			[ACTION_TYPE.ACTION_SIT_IDLE] = 1,
			[ACTION_TYPE.ACTION_SIT_ATTACK] = 6,
			[ACTION_TYPE.ACTION_SIT_DOWN] = 15,
			[ACTION_TYPE.ACTION_SIT_UP] = 15,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_SIT_IDLE] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_SIT_ATTACK] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_SIT_DOWN] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_SIT_UP] = BF_EIGHT_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
			[ACTION_TYPE.ACTION_SIT_IDLE] = true,
			[ACTION_TYPE.ACTION_SIT_ATTACK] = true,
			[ACTION_TYPE.ACTION_SIT_DOWN] = false,
			[ACTION_TYPE.ACTION_SIT_UP] = false,
		},
		needDirFlip = true,
	},
	['B_F_Initiate'] ={--尤里新兵
	     name = "Army_Initiate",
	     plist = "Army_Initiate_Action.color.plist",
	     pic = "Army_Initiate_Action.color.png",
	    fps = {
			[ACTION_TYPE.ACTION_IDLE] = 20,
			[ACTION_TYPE.ACTION_ATTACK] = 20,
			[ACTION_TYPE.ACTION_RUN] = 20,
			[ACTION_TYPE.ACTION_DEATH] = 20,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 6,
			[ACTION_TYPE.ACTION_RUN] = 6,
			[ACTION_TYPE.ACTION_DEATH] = 15,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_EIGHT_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = true,
	},
	['B_F_Brute'] ={--狂兽人
	     name = "Army_Brute",
	     plist = "Army_Brute_Action.plist",
	     pic = "Army_Brute_Action.png",
	    fps = {
			[ACTION_TYPE.ACTION_IDLE] = 8,
			[ACTION_TYPE.ACTION_ATTACK] = 25,
			[ACTION_TYPE.ACTION_RUN] = 12,
			[ACTION_TYPE.ACTION_DEATH] = 20,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 10,
			[ACTION_TYPE.ACTION_RUN] = 6,
			[ACTION_TYPE.ACTION_DEATH] = 15,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_EIGHT_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = true,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = true,
	},
    ['B_F_Conscript'] ={--动员兵
	     name = "Army_Conscript",
	     plist = "Army_Conscript_Action.color.plist",
	     pic = "Army_Conscript_Action.color.png",
	    fps = {
			[ACTION_TYPE.ACTION_IDLE] = 8,
			[ACTION_TYPE.ACTION_ATTACK] = 30,
			[ACTION_TYPE.ACTION_RUN] = 15,
			[ACTION_TYPE.ACTION_DEATH] = 20,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 6,
			[ACTION_TYPE.ACTION_RUN] = 6,
			[ACTION_TYPE.ACTION_DEATH] = 15,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_EIGHT_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = true,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = true,
	},
	['B_F_Boris'] ={--鲍里斯
	     name = "Army_Boris",
	     plist = "Army_Boris_Action.plist",
	     pic = "Army_Boris_Action.png",
	    fps = {
			[ACTION_TYPE.ACTION_IDLE] = 8,
			[ACTION_TYPE.ACTION_ATTACK] = 30,
			[ACTION_TYPE.ACTION_RUN] = 15,
			[ACTION_TYPE.ACTION_DEATH] = 20,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 6,
			[ACTION_TYPE.ACTION_RUN] = 6,
			[ACTION_TYPE.ACTION_DEATH] = 15,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_EIGHT_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = true,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = true,
	},
	['B_F_KirovAirshipUp'] ={--基洛夫飞艇
	     name = "Army_KirovAirship",
	     plist = "Army_KirovAirship_Action.color.plist",
	     pic = "Army_KirovAirship_Action.color.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = false,
	},
	['B_F_KirovAirshipDown'] ={--基洛夫飞艇
	     name = "Army_KirovAirshipShadow",
	     plist = "Army_KirovAirship_Action.color.plist",
	     pic = "Army_KirovAirship_Action.color.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = false,
	},
	['B_F_BlackEagleUp'] ={--黑鹰战机
	     name = "Army_BlackEagle",
	     plist = "Army_BlackEagle_Action.color.plist",
	     pic = "Army_BlackEagle_Action.color.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = false,
	},
	['B_F_BlackEagleDown'] ={--黑鹰战机
	     name = "Army_BlackEagleShadow",
	     plist = "Army_BlackEagle_Action.color.plist",
	     pic = "Army_BlackEagle_Action.color.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = false,
	},
    ['B_F_RocketeerUp'] ={--火箭飞行兵
	     name = "Army_Rocketeer",
	     plist = "Army_Rocketeer_Action.color.plist",
	     pic = "Army_Rocketeer_Action.color.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 18,
			[ACTION_TYPE.ACTION_ATTACK] = 30,
			[ACTION_TYPE.ACTION_RUN] = 15,
			[ACTION_TYPE.ACTION_DEATH] = 20,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 6,
			[ACTION_TYPE.ACTION_ATTACK] = 6,
			[ACTION_TYPE.ACTION_RUN] = 6,
			[ACTION_TYPE.ACTION_DEATH] = 15,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_EIGHT_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = false,
	},
	['B_F_RocketeerDown'] ={--火箭飞行兵
	     name = "Army_RocketeerShadow",
	     plist = "Army_Rocketeer_Action.color.plist",
	     pic = "Army_Rocketeer_Action.color.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 8,
			[ACTION_TYPE.ACTION_ATTACK] = 30,
			[ACTION_TYPE.ACTION_RUN] = 15,
			[ACTION_TYPE.ACTION_DEATH] = 20,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 6,
			[ACTION_TYPE.ACTION_ATTACK] = 6,
			[ACTION_TYPE.ACTION_RUN] = 6,
			[ACTION_TYPE.ACTION_DEATH] = 15,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_EIGHT_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = false,
	},
    ['B_F_BorisUp'] ={--鲍里斯
	     name = "Army_Boris",
	     plist = "Army_Boris_Action.plist",
	     pic = "Army_Boris_Action.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 8,
			[ACTION_TYPE.ACTION_ATTACK] = 25,
			[ACTION_TYPE.ACTION_RUN] = 15,
			[ACTION_TYPE.ACTION_DEATH] = 20,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 6,
			[ACTION_TYPE.ACTION_RUN] = 6,
			[ACTION_TYPE.ACTION_DEATH] = 15,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_EIGHT_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = false,
	},
	['B_F_BorisBadgeDown'] ={--英雄徽章
	     name = "Army_BorisBadge",
	     plist = "Army_Boris_Action.plist",
	     pic = "Army_Boris_Action.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 15,
			[ACTION_TYPE.ACTION_ATTACK] = 15,
			[ACTION_TYPE.ACTION_RUN] = 15,
			[ACTION_TYPE.ACTION_DEATH] = 15,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 20,
			[ACTION_TYPE.ACTION_ATTACK] = 20,
			[ACTION_TYPE.ACTION_RUN] = 20,
			[ACTION_TYPE.ACTION_DEATH] = 20,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_EIGHT_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = false,
	},
	['B_F_TeslaCoilDown'] ={--电磁塔
	     name = "Army_TeslaCoil",
	     plist = "Army_TeslaCoil_Action.color.plist",
	     pic = "Army_TeslaCoil_Action.color.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 20,
			[ACTION_TYPE.ACTION_ATTACK] = 20,
			[ACTION_TYPE.ACTION_BEHIT_ATTACK] = 20,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 20,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 10,
			[ACTION_TYPE.ACTION_ATTACK] = 9,
			[ACTION_TYPE.ACTION_BEHIT_ATTACK] = 9,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 11,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_BEHIT_ATTACK] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = BF_ONE_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_BEHIT_ATTACK] = false,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = true,
		},
		needDirFlip = false,
	},
	['B_F_ConstructionYardDown'] ={--苏俄基地
	     name = "Army_ConstructionYard",
	     plist = "Army_ConstructionYard_Action.color.plist",
	     pic = "Army_ConstructionYard_Action.color.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = BF_ONE_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = true,
		},
		needDirFlip = false,
	},
	['B_F_YuriConstructionYardDown'] ={--尤里基地
	     name = "Army_YuriConstructionYard",
	     plist = "Army_YuriConstructionYard_Action.color.plist",
	     pic = "Army_YuriConstructionYard_Action.color.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = BF_ONE_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = true,
		},
		needDirFlip = false,
	},
	['B_F_V3CarDown'] ={--v3车身
	     name = "Army_V3Car",
	     plist = "Army_V3Car_Action.color.plist",
	     pic = "Army_V3Car_Action.color.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 8,
			[ACTION_TYPE.ACTION_ATTACK] = 30,
			[ACTION_TYPE.ACTION_RUN] = 15,
			[ACTION_TYPE.ACTION_DEATH] = 20,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = false,
	},
	['B_F_V3CarUp'] ={--v3炮
	     name = "Army_V3Gun",
	     plist = "Army_V3Gun_Action.color.plist",
	     pic = "Army_V3Gun_Action.color.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 6,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 15,
			[ACTION_TYPE.ACTION_DEATH] = 20,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 6,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = false,
	},
	['B_F_V3Bullet'] ={--V3子弹
	     name = "Army_V3Bullet",
	     plist = "Army_V3Bullet_Action.color.plist",
	     pic = "Army_V3Bullet_Action.color.png",
	    fps = {
			[ACTION_TYPE.ACTION_IDLE] = 8,
			[ACTION_TYPE.ACTION_RUN] = 15,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 3,
			[ACTION_TYPE.ACTION_RUN] = 3,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = false,
			[ACTION_TYPE.ACTION_RUN] = false,
		},
		needDirFlip = false,
	},
	['B_F_DreadnoughtBullet'] ={-- 技能单发炮弹
	     name = "Army_DreadnoughtBullet",
	     plist = "Army_DreadnoughtBullet_Action.plist",
	     pic = "Army_DreadnoughtBullet_Action.png",
	    fps = {
			[ACTION_TYPE.ACTION_IDLE] = 8,
			[ACTION_TYPE.ACTION_RUN] = 15,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 3,
			[ACTION_TYPE.ACTION_RUN] = 3,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = false,
			[ACTION_TYPE.ACTION_RUN] = false,
		},
		needDirFlip = false,
	},
	['Army_DreadnoughtBulletShadow'] ={-- 技能单发炮弹的影子
	     name = "Army_DreadnoughtBulletShadow",
	     plist = "Army_DreadnoughtBullet_Action.plist",
	     pic = "Army_DreadnoughtBullet_Action.png",
	    fps = {
			[ACTION_TYPE.ACTION_IDLE] = 8,
			[ACTION_TYPE.ACTION_RUN] = 15,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 3,
			[ACTION_TYPE.ACTION_RUN] = 3,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = false,
			[ACTION_TYPE.ACTION_RUN] = false,
		},
		needDirFlip = false,
	},
	['B_F_DreadnoughtMissile'] ={-- 技能多发炮弹
	     name = "Army_DreadnoughtMissile",
	     plist = "Army_DreadnoughtMissile_Action.plist",
	     pic = "Army_DreadnoughtMissile_Action.png",
	    fps = {
			[ACTION_TYPE.ACTION_IDLE] = 8,
			[ACTION_TYPE.ACTION_RUN] = 15,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 3,
			[ACTION_TYPE.ACTION_RUN] = 3,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = false,
			[ACTION_TYPE.ACTION_RUN] = false,
		},
		needDirFlip = false,
	},
	['Army_DreadnoughtMissileShadow'] ={-- 技能多发炮弹的影子
	     name = "Army_DreadnoughtMissileShadow",
	     plist = "Army_DreadnoughtMissile_Action.plist",
	     pic = "Army_DreadnoughtMissile_Action.png",
	    fps = {
			[ACTION_TYPE.ACTION_IDLE] = 8,
			[ACTION_TYPE.ACTION_RUN] = 15,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 3,
			[ACTION_TYPE.ACTION_RUN] = 3,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = false,
			[ACTION_TYPE.ACTION_RUN] = false,
		},
		needDirFlip = false,
	},
	['B_F_Paratroopers'] ={--伞兵
	     name = "Army_Paratroopers",
	     plist = "Army_Paratroopers_Action.plist",
	     pic = "Army_Paratroopers_Action.png",
	    fps = {
			[ACTION_TYPE.ACTION_IDLE] = 15, --空中
			[ACTION_TYPE.ACTION_RUN] = 15, --开伞
			[ACTION_TYPE.ACTION_ATTACK]=15,--收伞
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 21,--空中
			[ACTION_TYPE.ACTION_RUN] = 19,--开伞
			[ACTION_TYPE.ACTION_ATTACK]=29,--收伞
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_ONE_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = false,
			[ACTION_TYPE.ACTION_ATTACK] = false,
		},
		needDirFlip = false,
	},
	['B_F_GattlingCannonDown'] ={--哨戒炮
	     name = "Army_GattlingCannon",
	     plist = "Army_GattlingCannon_Action.color.plist",
	     pic = "Army_GattlingCannon_Action.color.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
		},
		needDirFlip = false,
	},
	['B_F_YuriGattlingCannonDown'] ={--盖特机炮
	     name = "Army_YuriGattlingCannon",
	     plist = "Army_YuriGattlingCannon_Action.color.plist",
	     pic = "Army_YuriGattlingCannon_Action.color.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 25
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 3,
			[ACTION_TYPE.ACTION_ATTACK] = 6,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_ATTACK] = true,
		},
		needDirFlip = false,
	},
	['B_F_FlakCannonDown'] ={--防空炮
	     name = "Army_FlakCannon",
	     plist = "Army_FlakCannon_Action.color.plist",
	     pic = "Army_FlakCannon_Action.color.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
		},
		needDirFlip = false,
	},
	['B_F_TankBunkerDown'] ={--苏俄战斗碉堡
	     name = "Army_TankBunker",
	     plist = "Army_TankBunker_Action.plist",
	     pic = "Army_TankBunker_Action.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = BF_ONE_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = true,
		},
		needDirFlip = false,
	},
	['B_F_TeslaReactorDown'] ={--苏俄发电厂
	     name = "Army_TeslaReactor",
	     plist = "Army_TeslaReactor_Action.color.plist",
	     pic = "Army_TeslaReactor_Action.color.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 15,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 15,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 19,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 19,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = BF_ONE_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = true,
		},
		needDirFlip = false,
	},
	['B_F_YuriTeslaReactorDown'] ={--尤里发电厂
	     name = "Army_YuriTeslaReactor",
	     plist = "Army_YuriTeslaReactor_Action.color.plist",
	     pic = "Army_YuriTeslaReactor_Action.color.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 15,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 15,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 8,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 8,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = BF_ONE_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = true,
		},
		needDirFlip = false,
	},
	['B_F_OilWellDown'] ={--油井
	     name = "Army_OilWell",
	     plist = "Army_OilWell_Action.color.plist",
	     pic = "Army_OilWell_Action.color.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 15,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 15,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 32,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 32,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = BF_ONE_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = true,
		},
		needDirFlip = false,
	},
		['B_F_FlagDown'] ={--旗帜
	     name = "Army_Flag",
	     plist = "Army_Flag_Action.color.plist",
	     pic = "Army_Flag_Action.color.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 20,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 16,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_ONE_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
		},
		needDirFlip = false,
	},
	    ['B_F_WallOriginDown'] ={--苏俄城墙中心
	     name = "Army_WallOrigin",
	     plist = "Army_Wall_Action.plist",
	     pic = "Army_Wall_Action.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = BF_ONE_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = true,
		},
		needDirFlip = false,
	},
		['B_F_WallXDown'] ={--苏俄城墙X轴
	     name = "Army_WallX",
	     plist = "Army_Wall_Action.plist",
	     pic = "Army_Wall_Action.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = BF_ONE_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = true,
		},
		needDirFlip = false,
	},
		['B_F_WallYDown'] ={--苏俄城墙Y轴
	     name = "Army_WallY",
	     plist = "Army_Wall_Action.plist",
	     pic = "Army_Wall_Action.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = BF_ONE_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = true,
		},
		needDirFlip = false,
	},
	    ['B_F_YuriWallOriginDown'] ={--尤里城墙中心
	     name = "Army_YuriWallOrigin",
	     plist = "Army_YuriWall_Action.plist",
	     pic = "Army_YuriWall_Action.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = BF_ONE_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = true,
		},
		needDirFlip = false,
	},
		['B_F_YuriWallXDown'] ={--尤里城墙X轴
	     name = "Army_YuriWallX",
	     plist = "Army_YuriWall_Action.plist",
	     pic = "Army_YuriWall_Action.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = BF_ONE_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = true,
		},
		needDirFlip = false,
	},
		['B_F_YuriWallYDown'] ={--尤里城墙Y轴
	     name = "Army_YuriWallY",
	     plist = "Army_YuriWall_Action.plist",
	     pic = "Army_YuriWall_Action.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = BF_ONE_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = true,
		},
		needDirFlip = false,
	},
	['B_F_SandBagOriginDown'] ={--沙包中心
	     name = "Army_SandBagOrigin",
	     plist = "Army_SandBag_Action.plist",
	     pic = "Army_SandBag_Action.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = BF_ONE_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = true,
		},
		needDirFlip = false,
	},
	['B_F_SandBagXDown'] ={--沙包X轴
	     name = "Army_SandBagX",
	     plist = "Army_SandBag_Action.plist",
	     pic = "Army_SandBag_Action.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = BF_ONE_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = true,
		},
		needDirFlip = false,
	},
	['B_F_SandBagYDown'] ={--沙包Y轴
	     name = "Army_SandBagY",
	     plist = "Army_SandBag_Action.plist",
	     pic = "Army_SandBag_Action.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 1,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = BF_ONE_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = true,
		},
		needDirFlip = false,
	},
	    ['B_F_TentDown'] ={--医疗帐篷
	     name = "Army_Tent",
	     plist = "Army_Tent_Action.plist",
	     pic = "Army_Tent_Action.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 20,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 13,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_ONE_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
		},
		needDirFlip = false,
	},
	['B_F_PsychicTowerDown'] ={--心灵控制器
	     name = "Army_PsychicTower",
	     plist = "Army_PsychicTower_Action.plist",
	     pic = "Army_PsychicTower_Action.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 15,
			[ACTION_TYPE.ACTION_RUN] = 15,
			[ACTION_TYPE.ACTION_ATTACK] = 20,
			[ACTION_TYPE.ACTION_BEHIT_ATTACK] = 20,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_RUN] = 15,
			[ACTION_TYPE.ACTION_ATTACK] = 7,
			[ACTION_TYPE.ACTION_BEHIT_ATTACK] = 7,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_BEHIT_ATTACK] = BF_ONE_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = false,
			[ACTION_TYPE.ACTION_ATTACK] = true,
			[ACTION_TYPE.ACTION_BEHIT_ATTACK] = false,
		},
		needDirFlip = false,
	},
	['B_F_GrandCannonDown'] ={--法国巨炮
	     name = "Army_GrandCannon",
	     plist = "Army_GrandCannon_Action.color.plist",
	     pic = "Army_GrandCannon_Action.color.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 20,
			[ACTION_TYPE.ACTION_ATTACK] = 20
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 3,
			[ACTION_TYPE.ACTION_ATTACK] = 4,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = false,
			[ACTION_TYPE.ACTION_ATTACK] = false,
		},
		needDirFlip = false,
	},
	['B_F_PrismTowerDown'] ={--光陵塔
	     name = "Army_PrismTower",
	     plist = "Army_PrismTower_Action.color.plist",
	     pic = "Army_PrismTower_Action.color.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 20,
			[ACTION_TYPE.ACTION_ATTACK] = 20,
			[ACTION_TYPE.ACTION_BEHIT_ATTACK] = 20,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 20,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 9,
			[ACTION_TYPE.ACTION_ATTACK] = 10,
			[ACTION_TYPE.ACTION_BEHIT_ATTACK] = 10,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = 9,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_BEHIT_ATTACK] = BF_ONE_DIR_OBJ,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = BF_ONE_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_BEHIT_ATTACK] = false,
			[ACTION_TYPE.ACTION_BEHIT_IDLE] = true,
		},
		needDirFlip = false,
	},
	['B_F_TerrorDrone'] ={--恐怖机器人test bls
	     name = "Army_TerrorDrone",
	     plist = "Army_TerrorDrone_Action.color.plist",
	     pic = "Army_TerrorDrone_Action.color.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 20,
			[ACTION_TYPE.ACTION_ATTACK] = 20,
			[ACTION_TYPE.ACTION_RUN] = 20,
			[ACTION_TYPE.ACTION_DEATH] = 20,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 8,
			[ACTION_TYPE.ACTION_ATTACK] = 32,
			[ACTION_TYPE.ACTION_RUN] = 8,
			[ACTION_TYPE.ACTION_DEATH] = 8,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_EIGHT_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = false,
	},
	['B_F_TeslaTrooper'] ={--磁暴步兵
	     name = "Army_TeslaTrooper",
	     plist = "Army_TeslaTrooper_Action.plist",
	     pic = "Army_TeslaTrooper_Action.png",
	    fps = {
			[ACTION_TYPE.ACTION_IDLE] = 20,
			[ACTION_TYPE.ACTION_ATTACK] = 20,
			[ACTION_TYPE.ACTION_RUN] = 20,
			[ACTION_TYPE.ACTION_DEATH] = 20,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 6,
			[ACTION_TYPE.ACTION_RUN] = 6,
			[ACTION_TYPE.ACTION_DEATH] = 15,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_EIGHT_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = true,
	},
	['B_F_FlakTrooper'] ={--防空步兵
	     name = "Army_FlakTrooper",
	     plist = "Army_FlakTrooper_Action.plist",
	     pic = "Army_FlakTrooper_Action.png",
	    fps = {
			[ACTION_TYPE.ACTION_IDLE] = 20,
			[ACTION_TYPE.ACTION_ATTACK] = 20,
			[ACTION_TYPE.ACTION_RUN] = 20,
			[ACTION_TYPE.ACTION_DEATH] = 20,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 6,
			[ACTION_TYPE.ACTION_RUN] = 6,
			[ACTION_TYPE.ACTION_DEATH] = 15,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_EIGHT_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = true,
	},
	['B_F_MedicalVehicle'] ={ --医疗车
	     name = "Army_MedicalVehicle",
	     plist = "Army_MedicalVehicle_Action.plist",
	     pic = "Army_MedicalVehicle_Action.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 20,
			[ACTION_TYPE.ACTION_ATTACK] = 20,
			[ACTION_TYPE.ACTION_RUN] = 20,
			[ACTION_TYPE.ACTION_DEATH] = 20,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_EIGHT_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_EIGHT_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = true,
			[ACTION_TYPE.ACTION_DEATH] = true,
		},
		needDirFlip = true,
	},
	['B_F_NightHawkTransportUp'] ={ --夜鹰直升机 机体
	     name = "Army_NightHawkTransport",
	     plist = "Army_NightHawkTransport_Action.plist",
	     pic = "Army_NightHawkTransport_Action.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 15,
			[ACTION_TYPE.ACTION_ATTACK] = 15,
			[ACTION_TYPE.ACTION_RUN] = 15,
			[ACTION_TYPE.ACTION_DEATH] = 15,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = true,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = true,
	},
	['B_F_NightHawkTransportDown'] ={ --夜鹰直升机 机翼
	     name = "Army_NightHawkTransportCrew",
	     plist = "Army_NightHawkTransport_Action.plist",
	     pic = "Army_NightHawkTransport_Action.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 15,
			[ACTION_TYPE.ACTION_ATTACK] = 15,
			[ACTION_TYPE.ACTION_RUN] = 15,
			[ACTION_TYPE.ACTION_DEATH] = 15,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 6,
			[ACTION_TYPE.ACTION_ATTACK] = 6,
			[ACTION_TYPE.ACTION_RUN] = 6,
			[ACTION_TYPE.ACTION_DEATH] = 6,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = true,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = true,
	},
	['B_F_NightHawkTransportShadow'] ={ --夜鹰直升机 影子
	     name = "Army_NightHawkTransportShadow",
	     plist = "Army_NightHawkTransport_Action.plist",
	     pic = "Army_NightHawkTransport_Action.png",
	     fps = {
			[ACTION_TYPE.ACTION_IDLE] = 15,
			[ACTION_TYPE.ACTION_ATTACK] = 15,
			[ACTION_TYPE.ACTION_RUN] = 15,
			[ACTION_TYPE.ACTION_DEATH] = 15,
		},
	    frameCount = {
			[ACTION_TYPE.ACTION_IDLE] = 1,
			[ACTION_TYPE.ACTION_ATTACK] = 1,
			[ACTION_TYPE.ACTION_RUN] = 1,
			[ACTION_TYPE.ACTION_DEATH] = 1,
		},
		actionDefine = {
			[ACTION_TYPE.ACTION_IDLE] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_RUN] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_ATTACK] = BF_SIXTEEN_DIR_OBJ,
			[ACTION_TYPE.ACTION_DEATH] = BF_SIXTEEN_DIR_OBJ,
		},
		actionRepeat = {
			[ACTION_TYPE.ACTION_IDLE] = true,
			[ACTION_TYPE.ACTION_RUN] = true,
			[ACTION_TYPE.ACTION_ATTACK] = false,
			[ACTION_TYPE.ACTION_DEATH] = false,
		},
		needDirFlip = true,
	},
}


return RAFU_Cfg_Bone
