--[[
description: 特效配置
author: zhenhui
date: 2016/11/22
]]--


local RAFU_Cfg_Effect = {
	["E_TankBlast"] = {
		class = "RAFU_Effect_ccb",
		ccbiName = "RABattleTest_Tank_Blast.ccbi",
		scale = 1.0,
		timeLine = "Default Timeline"
	},
	["Fight_Start"] = {
		class = "RAFU_Effect_ccb",
		ccbiName = "RABattle_Ani_BlakEagle.ccbi",
		pic = "Army_BlackEagle_Action.png",
		plist = "Army_BlackEagle_Action.plist",
		scale = 1.0,
		autoExit = true,
		timeLine = "Default Timeline"
	},
	["Mig_fly"] = {
		class = "RAFU_Effect_ccb",
		ccbiName = "RABattle_Ani_MiG.ccbi",
		pic = "Army_MiG_Action.png",
		plist = "Army_MiG_Action.plist",
		scale = 1.0,
		autoExit = true,
		timeLine = "Default Timeline"
	},
	["ParaPlane_Fly"] = {
		class = "RAFU_Effect_ccb",
		ccbiName = "RABattle_Ani_Transport.ccbi",
		pic = "Army_Transport_Action.png",
		plist = "Army_Transport_Action.plist",
		scale = 1.0,
		autoExit = true,
		timeLine = "Default Timeline"
	},	
	["Bulllt_Effect_Surface"] = {
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		frameName = "Fight_Ani_Scene_Hole_",
		probability = 90,
		percent = {5,10,15,40,55,60,85,100} --各种弹坑占的比例
	},
	["Bulllt_Effect_Build_Surface"] = {
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		frameName = "Fight_Ani_Scene_Hole_",
		probability = 50,
		percent = {30,60,100,100,100,100,100,100} --各种弹坑占的比例
	},		
	["E_BuildingBlast"] = {
		class = "RAFU_Effect_ccb",
		ccbiName = "Ani_Map_BaseExplode.ccbi",
		pic = "MapAni.png",
		plist = "MapAni.plist",
		scale = 1.0,
		timeLine = "Default Timeline"
	},
	["Fight_Ani_Behit_1"] = {
		class = "RAFU_Effect_frameList",
		prefix = "Fight_Ani_Behit_1",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		frameCount = 12,
		frameFps = 25,
		repeated = false,
		lastTime = 0.3,
		scale = 1.0,
		indexMode = 1,
	},
	["Fight_Ani_Behit_3"] = {
		class = "RAFU_Effect_frameList",
		prefix = "Fight_Ani_Behit_3",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		frameCount = 16,
		frameFps = 25,
		repeated = false,
		lastTime = 0.8,
		scale = 1.0,
		indexMode = 1,
	},
	["Fight_Ani_Behit_4"] = {
		class = "RAFU_Effect_frameList",
		prefix = "Fight_Ani_Behit_4",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		frameCount = 14,
		frameFps = 15,
		repeated = false,
		lastTime = 1,
		scale = 1.5,
		indexMode = 1,
	},
	["Fight_Ani_Behit_5"] = {
		class = "RAFU_Effect_frameList",
		prefix = "Fight_Ani_Behit_5",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		frameCount = 22,
		frameFps = 20,
		repeated = false,
		lastTime = 1.5,
		scale = 0.8,
		indexMode = 1,
	},
	["Fight_Ani_Fire_1"] = {
		class = "RAFU_Effect_frameList",
		prefix = "Fight_Ani_Fire_1",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		frameCount = 8,
		frameFps = 25,
		repeated = false,
		lastTime = 0.3,
		scale = 1.0,
		indexMode = 1,
	},
	["Fight_Ani_Fire_2"] = {
		class = "RAFU_Effect_frameList",
		prefix = "Fight_Ani_Fire_2",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		frameCount = 20,
		frameFps = 25,
		repeated = false,
		lastTime = 0.3,
		scale = 1.0,
		indexMode = 1,
	},
	["Fight_Ani_Death_Machine_1"] = {
		class = "RAFU_Effect_frameList",
		prefix = "Fight_Ani_Death_Machine_1",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		frameCount = 21,
		frameFps = 20,
		repeated = false,
		lastTime = 3,
		scale = 1,
		indexMode = 1,
	},
	["Fight_Ani_Death_Machine_2"] = {
		class = "RAFU_Effect_frameList",
		prefix = "Fight_Ani_Death_Machine_2",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		frameCount = 10,
		frameFps = 20,
		repeated = false,
		lastTime = 2,
		scale = 1,
		indexMode = 1,
	},
	["Fight_Ani_Death_Machine_3"] = {
		class = "RAFU_Effect_frameList",
		prefix = "Fight_Ani_Death_Machine_3",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		frameCount = 13,
		frameFps = 20,
		repeated = false,
		lastTime = 1,
		scale = 1,
		indexMode = 1,
	},
	["Fight_Ani_Behit_2"] = {
		class = "RAFU_Effect_frameList",
		prefix = "Fight_Ani_Behit_2",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		frameCount = 13,
		frameFps = 25,
		repeated = false,
		lastTime = 0.6,
		scale = 1,
		indexMode = 1,
	},
	["Fight_Ani_Death_Buff_1"] = {
		class = "RAFU_Effect_frameList",
		prefix = "Fight_Ani_Death_Buff_1",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		frameCount = 13,
		frameFps = 25,
		repeated = false,
		lastTime = 0.6,
		scale = 1,
		indexMode = 1,
	},
	["Fight_Ani_Death_Buff_2"] = {
		class = "RAFU_Effect_frameList",
		prefix = "Fight_Ani_Death_Buff_2",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		frameCount = 13,
		frameFps = 25,
		repeated = false,
		lastTime = 0.6,
		scale = 1,
		indexMode = 1,
	},
	["Fight_Ani_Death_Buff_3"] = {
		class = "RAFU_Effect_frameList",
		prefix = "Fight_Ani_Death_Buff_3",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		frameCount = 13,
		frameFps = 25,
		repeated = false,
		lastTime = 0.6,
		scale = 1,
		indexMode = 1,
	},
	["Fight_Ani_Death_Building_1"] = {
		class = "RAFU_Effect_ccb",
		ccbiName = "RABattle_Effect_Building_1.ccbi",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		scale = 1.0,
		autoExit = true,
		timeLine = "Default Timeline"
	},
	["Fight_Ani_Death_Building_2"] = {
		class = "RAFU_Effect_ccb",
		ccbiName = "RABattle_Effect_Building_2.ccbi",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		scale = 1.0,
		autoExit = true,
		timeLine = "Default Timeline"
	},
	["Fight_Ani_Death_Building_3"] = {
		class = "RAFU_Effect_ccb",
		ccbiName = "RABattle_Effect_Building_3.ccbi",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		scale = 1.0,
		autoExit = true,
		timeLine = "Default Timeline"
	},
	["Fight_Ani_Death_Building_4"] = {
		class = "RAFU_Effect_ccb",
		ccbiName = "RABattle_Effect_Building_4.ccbi",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		scale = 1.0,
		autoExit = true,
		timeLine = "Default Timeline"
	},
	["Fight_Ani_Behit_6"] = {
		class = "RAFU_Effect_frameList",
		prefix = "Fight_Ani_Behit_6",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		frameCount = 20,
		frameFps = 20,
		repeated = false,
		lastTime = 1,
		scale = 1,
		indexMode = 1,
	},
	["Fight_Ani_Buff_Effect_3"] = {
		class = "RAFU_Effect_frameList",
		prefix = "Fight_Ani_Buff_Effect_3",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		frameCount = 30,
		frameFps = 25,
		repeated = true,
		lastTime = 1,
		scale = 0.6,
		indexMode = 1,
	},
	["Fight_Ani_Buff_Effect_1"] = {
		class = "RAFU_Effect_frameList",
		prefix = "Fight_Ani_Buff_Effect_1",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		frameCount = 13,
		frameFps = 20,
		repeated = false,
		lastTime = 1,
		scale = 1,
		indexMode = 1,
	},
	["OneMissile_Skill_Effect"] = {--技能单发炮弹
		FrameClassName = 'RAFU_Effect_bone',
		BoneFrameCfgName = "B_F_DreadnoughtBullet",
		CanSwitch = false,
		Zorder = 2,
		isTop = false,
		scale = 0.7,
		imageOffsetY = 0
	},
	["OneMissile_SkillShadow_Effect"] = {
		FrameClassName = 'RAFU_Effect_bone',
		BoneFrameCfgName = "Army_DreadnoughtBulletShadow",
		CanSwitch = false,
		Zorder = 2,
		isTop = false,
		scale = 0.7,
		imageOffsetY = 0
	},
	["MultipleMissile_Skill_Effect"] = {--技能多发炮弹
		FrameClassName = 'RAFU_Effect_bone',
		BoneFrameCfgName = "B_F_DreadnoughtMissile",
		CanSwitch = false,
		Zorder = 2,
		isTop = false,
		scale = 0.5,
		imageOffsetY = 0
	},
	["MultipleMissile_SkillShadow_Effect"] = {
		FrameClassName = 'RAFU_Effect_bone',
		BoneFrameCfgName = "Army_DreadnoughtMissileShadow",
		CanSwitch = false,
		Zorder = 2,
		isTop = false,
		scale = 0.5,
		imageOffsetY = 0
	},
	["Fight_Ani_Behit_8"] = {
		class = "RAFU_Effect_frameList",
		prefix = "Fight_Ani_Behit_8",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		frameCount = 35,
		frameFps = 20,
		repeated = true,
		lastTime = 1,
		scale = 1,
		indexMode = 1,
	},
	["Fight_Ani_Behit_9"] = {
		class = "RAFU_Effect_frameList",
		prefix = "Fight_Ani_Behit_9",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		frameCount = 21,
		frameFps = 20,
		repeated = false,
		lastTime = 1.2,
		scale = 1,
		indexMode = 1,
		},
	["Fight_Ani_Behit_10"] = {
		class = "RAFU_Effect_frameList",
		prefix = "Fight_Ani_Behit_10",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		frameCount = 23,
		frameFps = 20,
		repeated = false,
		lastTime = 1.2,
		scale = 1,
		indexMode = 1,
		},
	["Fight_Ani_Behit_11"] = {
		class = "RAFU_Effect_frameList",
		prefix = "Fight_Ani_Behit_11",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		frameCount = 23,
		frameFps = 7,
		repeated = false,
		lastTime = 3,
		scale = 1,
		indexMode = 1,
		},
	["Fight_Ani_Behit_12"] = {
		class = "RAFU_Effect_frameList",
		prefix = "Fight_Ani_Behit_12",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		frameCount = 23,
		frameFps = 15,
		repeated = false,
		lastTime = 1.5,
		scale = 1,
		indexMode = 1,
		},
	["Fight_Ani_Behit_13"] = {
		class = "RAFU_Effect_frameList",
		prefix = "Fight_Ani_Behit_13",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		frameCount = 10,
		frameFps = 15,
		repeated = false,
		lastTime = 1,
		scale = 1,
		indexMode = 1,
		},
	["Fight_Ani_Bullet_Parabola_4"] = {
		class = "RAFU_Effect_frameList",
		prefix = "Fight_Ani_Bullet_Parabola_4",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		frameCount = 11,
		frameFps = 20,
		repeated = false,
		lastTime = 1,
		scale = 0.5,
		indexMode = 1,
	},
	["Fight_Ani_Bullet_ParabolaShadow_4"] = {
		class = "RAFU_Effect_frameList",
		prefix = "Fight_Ani_Bullet_ParabolaShadow_4",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		frameCount = 11,
		frameFps = 20,
		repeated = false,
		lastTime = 1,
		scale = 0.5,
		indexMode = 1,
	},
	["Fight_Ani_Crew_1"] = {
		class = "RAFU_Effect_frameList",
		prefix = "Fight_Ani_Crew_1",
		pic = "Army_NightHawkTransport_Action.png",
		plist = "Army_NightHawkTransport_Action.plist",
		frameCount = 6,
		frameFps = 25,
		repeated = true,
		lastTime = 0.5,
		scale = 1,
		indexMode = 1,
		},
	["Fight_Ani_AM_ATTACK"] = {
		class = "RAFU_Effect_spriteRepeat",
		ccbiName = "RAAM_Effect_Attack.ccbi",
		pic = "Army_Effect_1.png",
		plist = "Army_Effect_1.plist",
		scale = 1.0,
		autoExit = true,
	},
}
return RAFU_Cfg_Effect