-- Generated By protoc-gen-lua Do not Edit


local Account_Local_Var_Table = {}

local protobuf = require "protobuf"
module('Account_pb')


ACCOUNTBIND = protobuf.Descriptor();
Account_Local_Var_Table.ACCOUNTBIND_PLAYERID_FIELD = protobuf.FieldDescriptor();
Account_Local_Var_Table.ACCOUNTBIND_PFTYPE_FIELD = protobuf.FieldDescriptor();
Account_Local_Var_Table.ACCOUNTBIND_PFUID_FIELD = protobuf.FieldDescriptor();
Account_Local_Var_Table.ACCOUNTBIND_PARAMS_FIELD = protobuf.FieldDescriptor();
ACCOUNTUNBIND = protobuf.Descriptor();
Account_Local_Var_Table.ACCOUNTUNBIND_PLAYERID_FIELD = protobuf.FieldDescriptor();
Account_Local_Var_Table.ACCOUNTUNBIND_PFTYPE_FIELD = protobuf.FieldDescriptor();
Account_Local_Var_Table.ACCOUNTUNBIND_PFUID_FIELD = protobuf.FieldDescriptor();
Account_Local_Var_Table.ACCOUNTUNBIND_PARAMS_FIELD = protobuf.FieldDescriptor();

Account_Local_Var_Table.ACCOUNTBIND_PLAYERID_FIELD.name = "playerId"
Account_Local_Var_Table.ACCOUNTBIND_PLAYERID_FIELD.full_name = ".AccountBind.playerId"
Account_Local_Var_Table.ACCOUNTBIND_PLAYERID_FIELD.number = 1
Account_Local_Var_Table.ACCOUNTBIND_PLAYERID_FIELD.index = 0
Account_Local_Var_Table.ACCOUNTBIND_PLAYERID_FIELD.label = 2
Account_Local_Var_Table.ACCOUNTBIND_PLAYERID_FIELD.has_default_value = false
Account_Local_Var_Table.ACCOUNTBIND_PLAYERID_FIELD.default_value = ""
Account_Local_Var_Table.ACCOUNTBIND_PLAYERID_FIELD.type = 9
Account_Local_Var_Table.ACCOUNTBIND_PLAYERID_FIELD.cpp_type = 9

Account_Local_Var_Table.ACCOUNTBIND_PFTYPE_FIELD.name = "pfType"
Account_Local_Var_Table.ACCOUNTBIND_PFTYPE_FIELD.full_name = ".AccountBind.pfType"
Account_Local_Var_Table.ACCOUNTBIND_PFTYPE_FIELD.number = 2
Account_Local_Var_Table.ACCOUNTBIND_PFTYPE_FIELD.index = 1
Account_Local_Var_Table.ACCOUNTBIND_PFTYPE_FIELD.label = 2
Account_Local_Var_Table.ACCOUNTBIND_PFTYPE_FIELD.has_default_value = false
Account_Local_Var_Table.ACCOUNTBIND_PFTYPE_FIELD.default_value = ""
Account_Local_Var_Table.ACCOUNTBIND_PFTYPE_FIELD.type = 9
Account_Local_Var_Table.ACCOUNTBIND_PFTYPE_FIELD.cpp_type = 9

Account_Local_Var_Table.ACCOUNTBIND_PFUID_FIELD.name = "pfUid"
Account_Local_Var_Table.ACCOUNTBIND_PFUID_FIELD.full_name = ".AccountBind.pfUid"
Account_Local_Var_Table.ACCOUNTBIND_PFUID_FIELD.number = 3
Account_Local_Var_Table.ACCOUNTBIND_PFUID_FIELD.index = 2
Account_Local_Var_Table.ACCOUNTBIND_PFUID_FIELD.label = 2
Account_Local_Var_Table.ACCOUNTBIND_PFUID_FIELD.has_default_value = false
Account_Local_Var_Table.ACCOUNTBIND_PFUID_FIELD.default_value = ""
Account_Local_Var_Table.ACCOUNTBIND_PFUID_FIELD.type = 9
Account_Local_Var_Table.ACCOUNTBIND_PFUID_FIELD.cpp_type = 9

Account_Local_Var_Table.ACCOUNTBIND_PARAMS_FIELD.name = "params"
Account_Local_Var_Table.ACCOUNTBIND_PARAMS_FIELD.full_name = ".AccountBind.params"
Account_Local_Var_Table.ACCOUNTBIND_PARAMS_FIELD.number = 4
Account_Local_Var_Table.ACCOUNTBIND_PARAMS_FIELD.index = 3
Account_Local_Var_Table.ACCOUNTBIND_PARAMS_FIELD.label = 1
Account_Local_Var_Table.ACCOUNTBIND_PARAMS_FIELD.has_default_value = false
Account_Local_Var_Table.ACCOUNTBIND_PARAMS_FIELD.default_value = ""
Account_Local_Var_Table.ACCOUNTBIND_PARAMS_FIELD.type = 9
Account_Local_Var_Table.ACCOUNTBIND_PARAMS_FIELD.cpp_type = 9

ACCOUNTBIND.name = "AccountBind"
ACCOUNTBIND.full_name = ".AccountBind"
ACCOUNTBIND.nested_types = {}
ACCOUNTBIND.enum_types = {}
ACCOUNTBIND.fields = {Account_Local_Var_Table.ACCOUNTBIND_PLAYERID_FIELD, Account_Local_Var_Table.ACCOUNTBIND_PFTYPE_FIELD, Account_Local_Var_Table.ACCOUNTBIND_PFUID_FIELD, Account_Local_Var_Table.ACCOUNTBIND_PARAMS_FIELD}
ACCOUNTBIND.is_extendable = false
ACCOUNTBIND.extensions = {}
Account_Local_Var_Table.ACCOUNTUNBIND_PLAYERID_FIELD.name = "playerId"
Account_Local_Var_Table.ACCOUNTUNBIND_PLAYERID_FIELD.full_name = ".AccountUnbind.playerId"
Account_Local_Var_Table.ACCOUNTUNBIND_PLAYERID_FIELD.number = 1
Account_Local_Var_Table.ACCOUNTUNBIND_PLAYERID_FIELD.index = 0
Account_Local_Var_Table.ACCOUNTUNBIND_PLAYERID_FIELD.label = 2
Account_Local_Var_Table.ACCOUNTUNBIND_PLAYERID_FIELD.has_default_value = false
Account_Local_Var_Table.ACCOUNTUNBIND_PLAYERID_FIELD.default_value = ""
Account_Local_Var_Table.ACCOUNTUNBIND_PLAYERID_FIELD.type = 9
Account_Local_Var_Table.ACCOUNTUNBIND_PLAYERID_FIELD.cpp_type = 9

Account_Local_Var_Table.ACCOUNTUNBIND_PFTYPE_FIELD.name = "pfType"
Account_Local_Var_Table.ACCOUNTUNBIND_PFTYPE_FIELD.full_name = ".AccountUnbind.pfType"
Account_Local_Var_Table.ACCOUNTUNBIND_PFTYPE_FIELD.number = 2
Account_Local_Var_Table.ACCOUNTUNBIND_PFTYPE_FIELD.index = 1
Account_Local_Var_Table.ACCOUNTUNBIND_PFTYPE_FIELD.label = 2
Account_Local_Var_Table.ACCOUNTUNBIND_PFTYPE_FIELD.has_default_value = false
Account_Local_Var_Table.ACCOUNTUNBIND_PFTYPE_FIELD.default_value = ""
Account_Local_Var_Table.ACCOUNTUNBIND_PFTYPE_FIELD.type = 9
Account_Local_Var_Table.ACCOUNTUNBIND_PFTYPE_FIELD.cpp_type = 9

Account_Local_Var_Table.ACCOUNTUNBIND_PFUID_FIELD.name = "pfUid"
Account_Local_Var_Table.ACCOUNTUNBIND_PFUID_FIELD.full_name = ".AccountUnbind.pfUid"
Account_Local_Var_Table.ACCOUNTUNBIND_PFUID_FIELD.number = 3
Account_Local_Var_Table.ACCOUNTUNBIND_PFUID_FIELD.index = 2
Account_Local_Var_Table.ACCOUNTUNBIND_PFUID_FIELD.label = 2
Account_Local_Var_Table.ACCOUNTUNBIND_PFUID_FIELD.has_default_value = false
Account_Local_Var_Table.ACCOUNTUNBIND_PFUID_FIELD.default_value = ""
Account_Local_Var_Table.ACCOUNTUNBIND_PFUID_FIELD.type = 9
Account_Local_Var_Table.ACCOUNTUNBIND_PFUID_FIELD.cpp_type = 9

Account_Local_Var_Table.ACCOUNTUNBIND_PARAMS_FIELD.name = "params"
Account_Local_Var_Table.ACCOUNTUNBIND_PARAMS_FIELD.full_name = ".AccountUnbind.params"
Account_Local_Var_Table.ACCOUNTUNBIND_PARAMS_FIELD.number = 4
Account_Local_Var_Table.ACCOUNTUNBIND_PARAMS_FIELD.index = 3
Account_Local_Var_Table.ACCOUNTUNBIND_PARAMS_FIELD.label = 1
Account_Local_Var_Table.ACCOUNTUNBIND_PARAMS_FIELD.has_default_value = false
Account_Local_Var_Table.ACCOUNTUNBIND_PARAMS_FIELD.default_value = ""
Account_Local_Var_Table.ACCOUNTUNBIND_PARAMS_FIELD.type = 9
Account_Local_Var_Table.ACCOUNTUNBIND_PARAMS_FIELD.cpp_type = 9

ACCOUNTUNBIND.name = "AccountUnbind"
ACCOUNTUNBIND.full_name = ".AccountUnbind"
ACCOUNTUNBIND.nested_types = {}
ACCOUNTUNBIND.enum_types = {}
ACCOUNTUNBIND.fields = {Account_Local_Var_Table.ACCOUNTUNBIND_PLAYERID_FIELD, Account_Local_Var_Table.ACCOUNTUNBIND_PFTYPE_FIELD, Account_Local_Var_Table.ACCOUNTUNBIND_PFUID_FIELD, Account_Local_Var_Table.ACCOUNTUNBIND_PARAMS_FIELD}
ACCOUNTUNBIND.is_extendable = false
ACCOUNTUNBIND.extensions = {}

AccountBind = protobuf.Message(ACCOUNTBIND)
AccountUnbind = protobuf.Message(ACCOUNTUNBIND)

