-- Generated By protoc-gen-lua Do not Edit


local Cdk_Local_Var_Table = {}

local protobuf = require "protobuf"
local Reward_pb = require("Reward_pb")
module('Cdk_pb')


HPUSECDK = protobuf.Descriptor();
Cdk_Local_Var_Table.HPUSECDK_CDKEY_FIELD = protobuf.FieldDescriptor();
HPUSECDKRET = protobuf.Descriptor();
Cdk_Local_Var_Table.HPUSECDKRET_CDKEY_FIELD = protobuf.FieldDescriptor();
Cdk_Local_Var_Table.HPUSECDKRET_STATUS_FIELD = protobuf.FieldDescriptor();
Cdk_Local_Var_Table.HPUSECDKRET_REWARD_FIELD = protobuf.FieldDescriptor();

Cdk_Local_Var_Table.HPUSECDK_CDKEY_FIELD.name = "cdkey"
Cdk_Local_Var_Table.HPUSECDK_CDKEY_FIELD.full_name = ".HPUseCdk.cdkey"
Cdk_Local_Var_Table.HPUSECDK_CDKEY_FIELD.number = 1
Cdk_Local_Var_Table.HPUSECDK_CDKEY_FIELD.index = 0
Cdk_Local_Var_Table.HPUSECDK_CDKEY_FIELD.label = 2
Cdk_Local_Var_Table.HPUSECDK_CDKEY_FIELD.has_default_value = false
Cdk_Local_Var_Table.HPUSECDK_CDKEY_FIELD.default_value = ""
Cdk_Local_Var_Table.HPUSECDK_CDKEY_FIELD.type = 9
Cdk_Local_Var_Table.HPUSECDK_CDKEY_FIELD.cpp_type = 9

HPUSECDK.name = "HPUseCdk"
HPUSECDK.full_name = ".HPUseCdk"
HPUSECDK.nested_types = {}
HPUSECDK.enum_types = {}
HPUSECDK.fields = {Cdk_Local_Var_Table.HPUSECDK_CDKEY_FIELD}
HPUSECDK.is_extendable = false
HPUSECDK.extensions = {}
Cdk_Local_Var_Table.HPUSECDKRET_CDKEY_FIELD.name = "cdkey"
Cdk_Local_Var_Table.HPUSECDKRET_CDKEY_FIELD.full_name = ".HPUseCdkRet.cdkey"
Cdk_Local_Var_Table.HPUSECDKRET_CDKEY_FIELD.number = 1
Cdk_Local_Var_Table.HPUSECDKRET_CDKEY_FIELD.index = 0
Cdk_Local_Var_Table.HPUSECDKRET_CDKEY_FIELD.label = 2
Cdk_Local_Var_Table.HPUSECDKRET_CDKEY_FIELD.has_default_value = false
Cdk_Local_Var_Table.HPUSECDKRET_CDKEY_FIELD.default_value = ""
Cdk_Local_Var_Table.HPUSECDKRET_CDKEY_FIELD.type = 9
Cdk_Local_Var_Table.HPUSECDKRET_CDKEY_FIELD.cpp_type = 9

Cdk_Local_Var_Table.HPUSECDKRET_STATUS_FIELD.name = "status"
Cdk_Local_Var_Table.HPUSECDKRET_STATUS_FIELD.full_name = ".HPUseCdkRet.status"
Cdk_Local_Var_Table.HPUSECDKRET_STATUS_FIELD.number = 2
Cdk_Local_Var_Table.HPUSECDKRET_STATUS_FIELD.index = 1
Cdk_Local_Var_Table.HPUSECDKRET_STATUS_FIELD.label = 2
Cdk_Local_Var_Table.HPUSECDKRET_STATUS_FIELD.has_default_value = false
Cdk_Local_Var_Table.HPUSECDKRET_STATUS_FIELD.default_value = 0
Cdk_Local_Var_Table.HPUSECDKRET_STATUS_FIELD.type = 5
Cdk_Local_Var_Table.HPUSECDKRET_STATUS_FIELD.cpp_type = 1

Cdk_Local_Var_Table.HPUSECDKRET_REWARD_FIELD.name = "reward"
Cdk_Local_Var_Table.HPUSECDKRET_REWARD_FIELD.full_name = ".HPUseCdkRet.reward"
Cdk_Local_Var_Table.HPUSECDKRET_REWARD_FIELD.number = 3
Cdk_Local_Var_Table.HPUSECDKRET_REWARD_FIELD.index = 2
Cdk_Local_Var_Table.HPUSECDKRET_REWARD_FIELD.label = 1
Cdk_Local_Var_Table.HPUSECDKRET_REWARD_FIELD.has_default_value = false
Cdk_Local_Var_Table.HPUSECDKRET_REWARD_FIELD.default_value = nil
Cdk_Local_Var_Table.HPUSECDKRET_REWARD_FIELD.message_type = Reward_pb.REWARDINFO
Cdk_Local_Var_Table.HPUSECDKRET_REWARD_FIELD.type = 11
Cdk_Local_Var_Table.HPUSECDKRET_REWARD_FIELD.cpp_type = 10

HPUSECDKRET.name = "HPUseCdkRet"
HPUSECDKRET.full_name = ".HPUseCdkRet"
HPUSECDKRET.nested_types = {}
HPUSECDKRET.enum_types = {}
HPUSECDKRET.fields = {Cdk_Local_Var_Table.HPUSECDKRET_CDKEY_FIELD, Cdk_Local_Var_Table.HPUSECDKRET_STATUS_FIELD, Cdk_Local_Var_Table.HPUSECDKRET_REWARD_FIELD}
HPUSECDKRET.is_extendable = false
HPUSECDKRET.extensions = {}

HPUseCdk = protobuf.Message(HPUSECDK)
HPUseCdkRet = protobuf.Message(HPUSECDKRET)

