-- Generated By protoc-gen-lua Do not Edit


local Common_Local_Var_Table = {}

local protobuf = require "protobuf"
module('Common_pb')


HPREDPOINTSYNC = protobuf.Descriptor();
Common_Local_Var_Table.HPREDPOINTSYNC_TYPE_FIELD = protobuf.FieldDescriptor();
Common_Local_Var_Table.HPREDPOINTSYNC_VALUE_FIELD = protobuf.FieldDescriptor();

Common_Local_Var_Table.HPREDPOINTSYNC_TYPE_FIELD.name = "type"
Common_Local_Var_Table.HPREDPOINTSYNC_TYPE_FIELD.full_name = ".HpRedPointSync.type"
Common_Local_Var_Table.HPREDPOINTSYNC_TYPE_FIELD.number = 1
Common_Local_Var_Table.HPREDPOINTSYNC_TYPE_FIELD.index = 0
Common_Local_Var_Table.HPREDPOINTSYNC_TYPE_FIELD.label = 2
Common_Local_Var_Table.HPREDPOINTSYNC_TYPE_FIELD.has_default_value = false
Common_Local_Var_Table.HPREDPOINTSYNC_TYPE_FIELD.default_value = 0
Common_Local_Var_Table.HPREDPOINTSYNC_TYPE_FIELD.type = 5
Common_Local_Var_Table.HPREDPOINTSYNC_TYPE_FIELD.cpp_type = 1

Common_Local_Var_Table.HPREDPOINTSYNC_VALUE_FIELD.name = "value"
Common_Local_Var_Table.HPREDPOINTSYNC_VALUE_FIELD.full_name = ".HpRedPointSync.value"
Common_Local_Var_Table.HPREDPOINTSYNC_VALUE_FIELD.number = 2
Common_Local_Var_Table.HPREDPOINTSYNC_VALUE_FIELD.index = 1
Common_Local_Var_Table.HPREDPOINTSYNC_VALUE_FIELD.label = 1
Common_Local_Var_Table.HPREDPOINTSYNC_VALUE_FIELD.has_default_value = false
Common_Local_Var_Table.HPREDPOINTSYNC_VALUE_FIELD.default_value = ""
Common_Local_Var_Table.HPREDPOINTSYNC_VALUE_FIELD.type = 9
Common_Local_Var_Table.HPREDPOINTSYNC_VALUE_FIELD.cpp_type = 9

HPREDPOINTSYNC.name = "HpRedPointSync"
HPREDPOINTSYNC.full_name = ".HpRedPointSync"
HPREDPOINTSYNC.nested_types = {}
HPREDPOINTSYNC.enum_types = {}
HPREDPOINTSYNC.fields = {Common_Local_Var_Table.HPREDPOINTSYNC_TYPE_FIELD, Common_Local_Var_Table.HPREDPOINTSYNC_VALUE_FIELD}
HPREDPOINTSYNC.is_extendable = false
HPREDPOINTSYNC.extensions = {}

HpRedPointSync = protobuf.Message(HPREDPOINTSYNC)

