-- Generated By protoc-gen-lua Do not Edit


local Consume_Local_Var_Table = {}

local protobuf = require "protobuf"
module('Consume_pb')


SYNCATTRINFO = protobuf.Descriptor();
Consume_Local_Var_Table.SYNCATTRINFO_GOLD_FIELD = protobuf.FieldDescriptor();
Consume_Local_Var_Table.SYNCATTRINFO_COIN_FIELD = protobuf.FieldDescriptor();
Consume_Local_Var_Table.SYNCATTRINFO_GOLDORE_FIELD = protobuf.FieldDescriptor();
Consume_Local_Var_Table.SYNCATTRINFO_OIL_FIELD = protobuf.FieldDescriptor();
Consume_Local_Var_Table.SYNCATTRINFO_STEEL_FIELD = protobuf.FieldDescriptor();
Consume_Local_Var_Table.SYNCATTRINFO_TOMBARTHITE_FIELD = protobuf.FieldDescriptor();
Consume_Local_Var_Table.SYNCATTRINFO_LEVEL_FIELD = protobuf.FieldDescriptor();
Consume_Local_Var_Table.SYNCATTRINFO_EXP_FIELD = protobuf.FieldDescriptor();
Consume_Local_Var_Table.SYNCATTRINFO_VIPLEVEL_FIELD = protobuf.FieldDescriptor();
Consume_Local_Var_Table.SYNCATTRINFO_ELECTRIC_FIELD = protobuf.FieldDescriptor();
Consume_Local_Var_Table.SYNCATTRINFO_ELECTRICMAX_FIELD = protobuf.FieldDescriptor();
Consume_Local_Var_Table.SYNCATTRINFO_VIT_FIELD = protobuf.FieldDescriptor();
Consume_Local_Var_Table.SYNCATTRINFO_GUILDCONTRIBUTION_FIELD = protobuf.FieldDescriptor();
CONSUMEITEM = protobuf.Descriptor();
Consume_Local_Var_Table.CONSUMEITEM_TYPE_FIELD = protobuf.FieldDescriptor();
Consume_Local_Var_Table.CONSUMEITEM_ID_FIELD = protobuf.FieldDescriptor();
Consume_Local_Var_Table.CONSUMEITEM_ITEMID_FIELD = protobuf.FieldDescriptor();
Consume_Local_Var_Table.CONSUMEITEM_COUNT_FIELD = protobuf.FieldDescriptor();
HPCONSUMEINFO = protobuf.Descriptor();
Consume_Local_Var_Table.HPCONSUMEINFO_ATTRINFO_FIELD = protobuf.FieldDescriptor();
Consume_Local_Var_Table.HPCONSUMEINFO_CONSUMEITEM_FIELD = protobuf.FieldDescriptor();

Consume_Local_Var_Table.SYNCATTRINFO_GOLD_FIELD.name = "gold"
Consume_Local_Var_Table.SYNCATTRINFO_GOLD_FIELD.full_name = ".SyncAttrInfo.gold"
Consume_Local_Var_Table.SYNCATTRINFO_GOLD_FIELD.number = 1
Consume_Local_Var_Table.SYNCATTRINFO_GOLD_FIELD.index = 0
Consume_Local_Var_Table.SYNCATTRINFO_GOLD_FIELD.label = 1
Consume_Local_Var_Table.SYNCATTRINFO_GOLD_FIELD.has_default_value = false
Consume_Local_Var_Table.SYNCATTRINFO_GOLD_FIELD.default_value = 0
Consume_Local_Var_Table.SYNCATTRINFO_GOLD_FIELD.type = 5
Consume_Local_Var_Table.SYNCATTRINFO_GOLD_FIELD.cpp_type = 1

Consume_Local_Var_Table.SYNCATTRINFO_COIN_FIELD.name = "coin"
Consume_Local_Var_Table.SYNCATTRINFO_COIN_FIELD.full_name = ".SyncAttrInfo.coin"
Consume_Local_Var_Table.SYNCATTRINFO_COIN_FIELD.number = 2
Consume_Local_Var_Table.SYNCATTRINFO_COIN_FIELD.index = 1
Consume_Local_Var_Table.SYNCATTRINFO_COIN_FIELD.label = 1
Consume_Local_Var_Table.SYNCATTRINFO_COIN_FIELD.has_default_value = false
Consume_Local_Var_Table.SYNCATTRINFO_COIN_FIELD.default_value = 0
Consume_Local_Var_Table.SYNCATTRINFO_COIN_FIELD.type = 5
Consume_Local_Var_Table.SYNCATTRINFO_COIN_FIELD.cpp_type = 1

Consume_Local_Var_Table.SYNCATTRINFO_GOLDORE_FIELD.name = "goldore"
Consume_Local_Var_Table.SYNCATTRINFO_GOLDORE_FIELD.full_name = ".SyncAttrInfo.goldore"
Consume_Local_Var_Table.SYNCATTRINFO_GOLDORE_FIELD.number = 4
Consume_Local_Var_Table.SYNCATTRINFO_GOLDORE_FIELD.index = 2
Consume_Local_Var_Table.SYNCATTRINFO_GOLDORE_FIELD.label = 1
Consume_Local_Var_Table.SYNCATTRINFO_GOLDORE_FIELD.has_default_value = false
Consume_Local_Var_Table.SYNCATTRINFO_GOLDORE_FIELD.default_value = 0
Consume_Local_Var_Table.SYNCATTRINFO_GOLDORE_FIELD.type = 3
Consume_Local_Var_Table.SYNCATTRINFO_GOLDORE_FIELD.cpp_type = 2

Consume_Local_Var_Table.SYNCATTRINFO_OIL_FIELD.name = "oil"
Consume_Local_Var_Table.SYNCATTRINFO_OIL_FIELD.full_name = ".SyncAttrInfo.oil"
Consume_Local_Var_Table.SYNCATTRINFO_OIL_FIELD.number = 5
Consume_Local_Var_Table.SYNCATTRINFO_OIL_FIELD.index = 3
Consume_Local_Var_Table.SYNCATTRINFO_OIL_FIELD.label = 1
Consume_Local_Var_Table.SYNCATTRINFO_OIL_FIELD.has_default_value = false
Consume_Local_Var_Table.SYNCATTRINFO_OIL_FIELD.default_value = 0
Consume_Local_Var_Table.SYNCATTRINFO_OIL_FIELD.type = 3
Consume_Local_Var_Table.SYNCATTRINFO_OIL_FIELD.cpp_type = 2

Consume_Local_Var_Table.SYNCATTRINFO_STEEL_FIELD.name = "steel"
Consume_Local_Var_Table.SYNCATTRINFO_STEEL_FIELD.full_name = ".SyncAttrInfo.steel"
Consume_Local_Var_Table.SYNCATTRINFO_STEEL_FIELD.number = 6
Consume_Local_Var_Table.SYNCATTRINFO_STEEL_FIELD.index = 4
Consume_Local_Var_Table.SYNCATTRINFO_STEEL_FIELD.label = 1
Consume_Local_Var_Table.SYNCATTRINFO_STEEL_FIELD.has_default_value = false
Consume_Local_Var_Table.SYNCATTRINFO_STEEL_FIELD.default_value = 0
Consume_Local_Var_Table.SYNCATTRINFO_STEEL_FIELD.type = 3
Consume_Local_Var_Table.SYNCATTRINFO_STEEL_FIELD.cpp_type = 2

Consume_Local_Var_Table.SYNCATTRINFO_TOMBARTHITE_FIELD.name = "tombarthite"
Consume_Local_Var_Table.SYNCATTRINFO_TOMBARTHITE_FIELD.full_name = ".SyncAttrInfo.tombarthite"
Consume_Local_Var_Table.SYNCATTRINFO_TOMBARTHITE_FIELD.number = 7
Consume_Local_Var_Table.SYNCATTRINFO_TOMBARTHITE_FIELD.index = 5
Consume_Local_Var_Table.SYNCATTRINFO_TOMBARTHITE_FIELD.label = 1
Consume_Local_Var_Table.SYNCATTRINFO_TOMBARTHITE_FIELD.has_default_value = false
Consume_Local_Var_Table.SYNCATTRINFO_TOMBARTHITE_FIELD.default_value = 0
Consume_Local_Var_Table.SYNCATTRINFO_TOMBARTHITE_FIELD.type = 3
Consume_Local_Var_Table.SYNCATTRINFO_TOMBARTHITE_FIELD.cpp_type = 2

Consume_Local_Var_Table.SYNCATTRINFO_LEVEL_FIELD.name = "level"
Consume_Local_Var_Table.SYNCATTRINFO_LEVEL_FIELD.full_name = ".SyncAttrInfo.level"
Consume_Local_Var_Table.SYNCATTRINFO_LEVEL_FIELD.number = 8
Consume_Local_Var_Table.SYNCATTRINFO_LEVEL_FIELD.index = 6
Consume_Local_Var_Table.SYNCATTRINFO_LEVEL_FIELD.label = 1
Consume_Local_Var_Table.SYNCATTRINFO_LEVEL_FIELD.has_default_value = false
Consume_Local_Var_Table.SYNCATTRINFO_LEVEL_FIELD.default_value = 0
Consume_Local_Var_Table.SYNCATTRINFO_LEVEL_FIELD.type = 5
Consume_Local_Var_Table.SYNCATTRINFO_LEVEL_FIELD.cpp_type = 1

Consume_Local_Var_Table.SYNCATTRINFO_EXP_FIELD.name = "exp"
Consume_Local_Var_Table.SYNCATTRINFO_EXP_FIELD.full_name = ".SyncAttrInfo.exp"
Consume_Local_Var_Table.SYNCATTRINFO_EXP_FIELD.number = 9
Consume_Local_Var_Table.SYNCATTRINFO_EXP_FIELD.index = 7
Consume_Local_Var_Table.SYNCATTRINFO_EXP_FIELD.label = 1
Consume_Local_Var_Table.SYNCATTRINFO_EXP_FIELD.has_default_value = false
Consume_Local_Var_Table.SYNCATTRINFO_EXP_FIELD.default_value = 0
Consume_Local_Var_Table.SYNCATTRINFO_EXP_FIELD.type = 5
Consume_Local_Var_Table.SYNCATTRINFO_EXP_FIELD.cpp_type = 1

Consume_Local_Var_Table.SYNCATTRINFO_VIPLEVEL_FIELD.name = "vipLevel"
Consume_Local_Var_Table.SYNCATTRINFO_VIPLEVEL_FIELD.full_name = ".SyncAttrInfo.vipLevel"
Consume_Local_Var_Table.SYNCATTRINFO_VIPLEVEL_FIELD.number = 10
Consume_Local_Var_Table.SYNCATTRINFO_VIPLEVEL_FIELD.index = 8
Consume_Local_Var_Table.SYNCATTRINFO_VIPLEVEL_FIELD.label = 1
Consume_Local_Var_Table.SYNCATTRINFO_VIPLEVEL_FIELD.has_default_value = false
Consume_Local_Var_Table.SYNCATTRINFO_VIPLEVEL_FIELD.default_value = 0
Consume_Local_Var_Table.SYNCATTRINFO_VIPLEVEL_FIELD.type = 5
Consume_Local_Var_Table.SYNCATTRINFO_VIPLEVEL_FIELD.cpp_type = 1

Consume_Local_Var_Table.SYNCATTRINFO_ELECTRIC_FIELD.name = "electric"
Consume_Local_Var_Table.SYNCATTRINFO_ELECTRIC_FIELD.full_name = ".SyncAttrInfo.electric"
Consume_Local_Var_Table.SYNCATTRINFO_ELECTRIC_FIELD.number = 11
Consume_Local_Var_Table.SYNCATTRINFO_ELECTRIC_FIELD.index = 9
Consume_Local_Var_Table.SYNCATTRINFO_ELECTRIC_FIELD.label = 1
Consume_Local_Var_Table.SYNCATTRINFO_ELECTRIC_FIELD.has_default_value = false
Consume_Local_Var_Table.SYNCATTRINFO_ELECTRIC_FIELD.default_value = 0
Consume_Local_Var_Table.SYNCATTRINFO_ELECTRIC_FIELD.type = 3
Consume_Local_Var_Table.SYNCATTRINFO_ELECTRIC_FIELD.cpp_type = 2

Consume_Local_Var_Table.SYNCATTRINFO_ELECTRICMAX_FIELD.name = "electricMax"
Consume_Local_Var_Table.SYNCATTRINFO_ELECTRICMAX_FIELD.full_name = ".SyncAttrInfo.electricMax"
Consume_Local_Var_Table.SYNCATTRINFO_ELECTRICMAX_FIELD.number = 12
Consume_Local_Var_Table.SYNCATTRINFO_ELECTRICMAX_FIELD.index = 10
Consume_Local_Var_Table.SYNCATTRINFO_ELECTRICMAX_FIELD.label = 1
Consume_Local_Var_Table.SYNCATTRINFO_ELECTRICMAX_FIELD.has_default_value = false
Consume_Local_Var_Table.SYNCATTRINFO_ELECTRICMAX_FIELD.default_value = 0
Consume_Local_Var_Table.SYNCATTRINFO_ELECTRICMAX_FIELD.type = 3
Consume_Local_Var_Table.SYNCATTRINFO_ELECTRICMAX_FIELD.cpp_type = 2

Consume_Local_Var_Table.SYNCATTRINFO_VIT_FIELD.name = "vit"
Consume_Local_Var_Table.SYNCATTRINFO_VIT_FIELD.full_name = ".SyncAttrInfo.vit"
Consume_Local_Var_Table.SYNCATTRINFO_VIT_FIELD.number = 13
Consume_Local_Var_Table.SYNCATTRINFO_VIT_FIELD.index = 11
Consume_Local_Var_Table.SYNCATTRINFO_VIT_FIELD.label = 1
Consume_Local_Var_Table.SYNCATTRINFO_VIT_FIELD.has_default_value = false
Consume_Local_Var_Table.SYNCATTRINFO_VIT_FIELD.default_value = 0
Consume_Local_Var_Table.SYNCATTRINFO_VIT_FIELD.type = 5
Consume_Local_Var_Table.SYNCATTRINFO_VIT_FIELD.cpp_type = 1

Consume_Local_Var_Table.SYNCATTRINFO_GUILDCONTRIBUTION_FIELD.name = "guildContribution"
Consume_Local_Var_Table.SYNCATTRINFO_GUILDCONTRIBUTION_FIELD.full_name = ".SyncAttrInfo.guildContribution"
Consume_Local_Var_Table.SYNCATTRINFO_GUILDCONTRIBUTION_FIELD.number = 14
Consume_Local_Var_Table.SYNCATTRINFO_GUILDCONTRIBUTION_FIELD.index = 12
Consume_Local_Var_Table.SYNCATTRINFO_GUILDCONTRIBUTION_FIELD.label = 1
Consume_Local_Var_Table.SYNCATTRINFO_GUILDCONTRIBUTION_FIELD.has_default_value = false
Consume_Local_Var_Table.SYNCATTRINFO_GUILDCONTRIBUTION_FIELD.default_value = 0
Consume_Local_Var_Table.SYNCATTRINFO_GUILDCONTRIBUTION_FIELD.type = 5
Consume_Local_Var_Table.SYNCATTRINFO_GUILDCONTRIBUTION_FIELD.cpp_type = 1

SYNCATTRINFO.name = "SyncAttrInfo"
SYNCATTRINFO.full_name = ".SyncAttrInfo"
SYNCATTRINFO.nested_types = {}
SYNCATTRINFO.enum_types = {}
SYNCATTRINFO.fields = {Consume_Local_Var_Table.SYNCATTRINFO_GOLD_FIELD, Consume_Local_Var_Table.SYNCATTRINFO_COIN_FIELD, Consume_Local_Var_Table.SYNCATTRINFO_GOLDORE_FIELD, Consume_Local_Var_Table.SYNCATTRINFO_OIL_FIELD, Consume_Local_Var_Table.SYNCATTRINFO_STEEL_FIELD, Consume_Local_Var_Table.SYNCATTRINFO_TOMBARTHITE_FIELD, Consume_Local_Var_Table.SYNCATTRINFO_LEVEL_FIELD, Consume_Local_Var_Table.SYNCATTRINFO_EXP_FIELD, Consume_Local_Var_Table.SYNCATTRINFO_VIPLEVEL_FIELD, Consume_Local_Var_Table.SYNCATTRINFO_ELECTRIC_FIELD, Consume_Local_Var_Table.SYNCATTRINFO_ELECTRICMAX_FIELD, Consume_Local_Var_Table.SYNCATTRINFO_VIT_FIELD, Consume_Local_Var_Table.SYNCATTRINFO_GUILDCONTRIBUTION_FIELD}
SYNCATTRINFO.is_extendable = false
SYNCATTRINFO.extensions = {}
Consume_Local_Var_Table.CONSUMEITEM_TYPE_FIELD.name = "type"
Consume_Local_Var_Table.CONSUMEITEM_TYPE_FIELD.full_name = ".ConsumeItem.type"
Consume_Local_Var_Table.CONSUMEITEM_TYPE_FIELD.number = 1
Consume_Local_Var_Table.CONSUMEITEM_TYPE_FIELD.index = 0
Consume_Local_Var_Table.CONSUMEITEM_TYPE_FIELD.label = 2
Consume_Local_Var_Table.CONSUMEITEM_TYPE_FIELD.has_default_value = false
Consume_Local_Var_Table.CONSUMEITEM_TYPE_FIELD.default_value = 0
Consume_Local_Var_Table.CONSUMEITEM_TYPE_FIELD.type = 5
Consume_Local_Var_Table.CONSUMEITEM_TYPE_FIELD.cpp_type = 1

Consume_Local_Var_Table.CONSUMEITEM_ID_FIELD.name = "id"
Consume_Local_Var_Table.CONSUMEITEM_ID_FIELD.full_name = ".ConsumeItem.id"
Consume_Local_Var_Table.CONSUMEITEM_ID_FIELD.number = 2
Consume_Local_Var_Table.CONSUMEITEM_ID_FIELD.index = 1
Consume_Local_Var_Table.CONSUMEITEM_ID_FIELD.label = 2
Consume_Local_Var_Table.CONSUMEITEM_ID_FIELD.has_default_value = false
Consume_Local_Var_Table.CONSUMEITEM_ID_FIELD.default_value = ""
Consume_Local_Var_Table.CONSUMEITEM_ID_FIELD.type = 9
Consume_Local_Var_Table.CONSUMEITEM_ID_FIELD.cpp_type = 9

Consume_Local_Var_Table.CONSUMEITEM_ITEMID_FIELD.name = "itemId"
Consume_Local_Var_Table.CONSUMEITEM_ITEMID_FIELD.full_name = ".ConsumeItem.itemId"
Consume_Local_Var_Table.CONSUMEITEM_ITEMID_FIELD.number = 3
Consume_Local_Var_Table.CONSUMEITEM_ITEMID_FIELD.index = 2
Consume_Local_Var_Table.CONSUMEITEM_ITEMID_FIELD.label = 2
Consume_Local_Var_Table.CONSUMEITEM_ITEMID_FIELD.has_default_value = false
Consume_Local_Var_Table.CONSUMEITEM_ITEMID_FIELD.default_value = 0
Consume_Local_Var_Table.CONSUMEITEM_ITEMID_FIELD.type = 5
Consume_Local_Var_Table.CONSUMEITEM_ITEMID_FIELD.cpp_type = 1

Consume_Local_Var_Table.CONSUMEITEM_COUNT_FIELD.name = "count"
Consume_Local_Var_Table.CONSUMEITEM_COUNT_FIELD.full_name = ".ConsumeItem.count"
Consume_Local_Var_Table.CONSUMEITEM_COUNT_FIELD.number = 4
Consume_Local_Var_Table.CONSUMEITEM_COUNT_FIELD.index = 3
Consume_Local_Var_Table.CONSUMEITEM_COUNT_FIELD.label = 1
Consume_Local_Var_Table.CONSUMEITEM_COUNT_FIELD.has_default_value = false
Consume_Local_Var_Table.CONSUMEITEM_COUNT_FIELD.default_value = 0
Consume_Local_Var_Table.CONSUMEITEM_COUNT_FIELD.type = 5
Consume_Local_Var_Table.CONSUMEITEM_COUNT_FIELD.cpp_type = 1

CONSUMEITEM.name = "ConsumeItem"
CONSUMEITEM.full_name = ".ConsumeItem"
CONSUMEITEM.nested_types = {}
CONSUMEITEM.enum_types = {}
CONSUMEITEM.fields = {Consume_Local_Var_Table.CONSUMEITEM_TYPE_FIELD, Consume_Local_Var_Table.CONSUMEITEM_ID_FIELD, Consume_Local_Var_Table.CONSUMEITEM_ITEMID_FIELD, Consume_Local_Var_Table.CONSUMEITEM_COUNT_FIELD}
CONSUMEITEM.is_extendable = false
CONSUMEITEM.extensions = {}
Consume_Local_Var_Table.HPCONSUMEINFO_ATTRINFO_FIELD.name = "attrInfo"
Consume_Local_Var_Table.HPCONSUMEINFO_ATTRINFO_FIELD.full_name = ".HPConsumeInfo.attrInfo"
Consume_Local_Var_Table.HPCONSUMEINFO_ATTRINFO_FIELD.number = 1
Consume_Local_Var_Table.HPCONSUMEINFO_ATTRINFO_FIELD.index = 0
Consume_Local_Var_Table.HPCONSUMEINFO_ATTRINFO_FIELD.label = 1
Consume_Local_Var_Table.HPCONSUMEINFO_ATTRINFO_FIELD.has_default_value = false
Consume_Local_Var_Table.HPCONSUMEINFO_ATTRINFO_FIELD.default_value = nil
Consume_Local_Var_Table.HPCONSUMEINFO_ATTRINFO_FIELD.message_type = SYNCATTRINFO
Consume_Local_Var_Table.HPCONSUMEINFO_ATTRINFO_FIELD.type = 11
Consume_Local_Var_Table.HPCONSUMEINFO_ATTRINFO_FIELD.cpp_type = 10

Consume_Local_Var_Table.HPCONSUMEINFO_CONSUMEITEM_FIELD.name = "consumeItem"
Consume_Local_Var_Table.HPCONSUMEINFO_CONSUMEITEM_FIELD.full_name = ".HPConsumeInfo.consumeItem"
Consume_Local_Var_Table.HPCONSUMEINFO_CONSUMEITEM_FIELD.number = 2
Consume_Local_Var_Table.HPCONSUMEINFO_CONSUMEITEM_FIELD.index = 1
Consume_Local_Var_Table.HPCONSUMEINFO_CONSUMEITEM_FIELD.label = 3
Consume_Local_Var_Table.HPCONSUMEINFO_CONSUMEITEM_FIELD.has_default_value = false
Consume_Local_Var_Table.HPCONSUMEINFO_CONSUMEITEM_FIELD.default_value = {}
Consume_Local_Var_Table.HPCONSUMEINFO_CONSUMEITEM_FIELD.message_type = CONSUMEITEM
Consume_Local_Var_Table.HPCONSUMEINFO_CONSUMEITEM_FIELD.type = 11
Consume_Local_Var_Table.HPCONSUMEINFO_CONSUMEITEM_FIELD.cpp_type = 10

HPCONSUMEINFO.name = "HPConsumeInfo"
HPCONSUMEINFO.full_name = ".HPConsumeInfo"
HPCONSUMEINFO.nested_types = {}
HPCONSUMEINFO.enum_types = {}
HPCONSUMEINFO.fields = {Consume_Local_Var_Table.HPCONSUMEINFO_ATTRINFO_FIELD, Consume_Local_Var_Table.HPCONSUMEINFO_CONSUMEITEM_FIELD}
HPCONSUMEINFO.is_extendable = false
HPCONSUMEINFO.extensions = {}

ConsumeItem = protobuf.Message(CONSUMEITEM)
HPConsumeInfo = protobuf.Message(HPCONSUMEINFO)
SyncAttrInfo = protobuf.Message(SYNCATTRINFO)

