-- Generated By protoc-gen-lua Do not Edit


local Equipment_Local_Var_Table = {}

local protobuf = require "protobuf"
module('Equipment_pb')


EQUIPMENTPB = protobuf.Descriptor();
Equipment_Local_Var_Table.EQUIPMENTPB_UUID_FIELD = protobuf.FieldDescriptor();
Equipment_Local_Var_Table.EQUIPMENTPB_EQUIPID_FIELD = protobuf.FieldDescriptor();
Equipment_Local_Var_Table.EQUIPMENTPB_LEVEL_FIELD = protobuf.FieldDescriptor();
Equipment_Local_Var_Table.EQUIPMENTPB_POINT_FIELD = protobuf.FieldDescriptor();
HPEQUIPMENTINFOSYNC = protobuf.Descriptor();
Equipment_Local_Var_Table.HPEQUIPMENTINFOSYNC_EQUIPMENTS_FIELD = protobuf.FieldDescriptor();
HPEQUIPLEVELUPREQ = protobuf.Descriptor();
Equipment_Local_Var_Table.HPEQUIPLEVELUPREQ_UUID_FIELD = protobuf.FieldDescriptor();
HPEQUIPENHANCEREQ = protobuf.Descriptor();
Equipment_Local_Var_Table.HPEQUIPENHANCEREQ_UUID_FIELD = protobuf.FieldDescriptor();
HPEQUIPENHANCERESP = protobuf.Descriptor();
Equipment_Local_Var_Table.HPEQUIPENHANCERESP_RESULT_FIELD = protobuf.FieldDescriptor();
Equipment_Local_Var_Table.HPEQUIPENHANCERESP_POINT_FIELD = protobuf.FieldDescriptor();
HPPLAYEREQUIPINFOREQ = protobuf.Descriptor();
Equipment_Local_Var_Table.HPPLAYEREQUIPINFOREQ_PLAYERID_FIELD = protobuf.FieldDescriptor();
HPPLAYEREQUIPINFORESP = protobuf.Descriptor();
Equipment_Local_Var_Table.HPPLAYEREQUIPINFORESP_EQUIPMENTS_FIELD = protobuf.FieldDescriptor();

Equipment_Local_Var_Table.EQUIPMENTPB_UUID_FIELD.name = "uuid"
Equipment_Local_Var_Table.EQUIPMENTPB_UUID_FIELD.full_name = ".EquipmentPB.uuid"
Equipment_Local_Var_Table.EQUIPMENTPB_UUID_FIELD.number = 1
Equipment_Local_Var_Table.EQUIPMENTPB_UUID_FIELD.index = 0
Equipment_Local_Var_Table.EQUIPMENTPB_UUID_FIELD.label = 2
Equipment_Local_Var_Table.EQUIPMENTPB_UUID_FIELD.has_default_value = false
Equipment_Local_Var_Table.EQUIPMENTPB_UUID_FIELD.default_value = ""
Equipment_Local_Var_Table.EQUIPMENTPB_UUID_FIELD.type = 9
Equipment_Local_Var_Table.EQUIPMENTPB_UUID_FIELD.cpp_type = 9

Equipment_Local_Var_Table.EQUIPMENTPB_EQUIPID_FIELD.name = "equipId"
Equipment_Local_Var_Table.EQUIPMENTPB_EQUIPID_FIELD.full_name = ".EquipmentPB.equipId"
Equipment_Local_Var_Table.EQUIPMENTPB_EQUIPID_FIELD.number = 2
Equipment_Local_Var_Table.EQUIPMENTPB_EQUIPID_FIELD.index = 1
Equipment_Local_Var_Table.EQUIPMENTPB_EQUIPID_FIELD.label = 2
Equipment_Local_Var_Table.EQUIPMENTPB_EQUIPID_FIELD.has_default_value = false
Equipment_Local_Var_Table.EQUIPMENTPB_EQUIPID_FIELD.default_value = 0
Equipment_Local_Var_Table.EQUIPMENTPB_EQUIPID_FIELD.type = 5
Equipment_Local_Var_Table.EQUIPMENTPB_EQUIPID_FIELD.cpp_type = 1

Equipment_Local_Var_Table.EQUIPMENTPB_LEVEL_FIELD.name = "level"
Equipment_Local_Var_Table.EQUIPMENTPB_LEVEL_FIELD.full_name = ".EquipmentPB.level"
Equipment_Local_Var_Table.EQUIPMENTPB_LEVEL_FIELD.number = 3
Equipment_Local_Var_Table.EQUIPMENTPB_LEVEL_FIELD.index = 2
Equipment_Local_Var_Table.EQUIPMENTPB_LEVEL_FIELD.label = 2
Equipment_Local_Var_Table.EQUIPMENTPB_LEVEL_FIELD.has_default_value = false
Equipment_Local_Var_Table.EQUIPMENTPB_LEVEL_FIELD.default_value = 0
Equipment_Local_Var_Table.EQUIPMENTPB_LEVEL_FIELD.type = 5
Equipment_Local_Var_Table.EQUIPMENTPB_LEVEL_FIELD.cpp_type = 1

Equipment_Local_Var_Table.EQUIPMENTPB_POINT_FIELD.name = "point"
Equipment_Local_Var_Table.EQUIPMENTPB_POINT_FIELD.full_name = ".EquipmentPB.point"
Equipment_Local_Var_Table.EQUIPMENTPB_POINT_FIELD.number = 4
Equipment_Local_Var_Table.EQUIPMENTPB_POINT_FIELD.index = 3
Equipment_Local_Var_Table.EQUIPMENTPB_POINT_FIELD.label = 2
Equipment_Local_Var_Table.EQUIPMENTPB_POINT_FIELD.has_default_value = false
Equipment_Local_Var_Table.EQUIPMENTPB_POINT_FIELD.default_value = 0
Equipment_Local_Var_Table.EQUIPMENTPB_POINT_FIELD.type = 5
Equipment_Local_Var_Table.EQUIPMENTPB_POINT_FIELD.cpp_type = 1

EQUIPMENTPB.name = "EquipmentPB"
EQUIPMENTPB.full_name = ".EquipmentPB"
EQUIPMENTPB.nested_types = {}
EQUIPMENTPB.enum_types = {}
EQUIPMENTPB.fields = {Equipment_Local_Var_Table.EQUIPMENTPB_UUID_FIELD, Equipment_Local_Var_Table.EQUIPMENTPB_EQUIPID_FIELD, Equipment_Local_Var_Table.EQUIPMENTPB_LEVEL_FIELD, Equipment_Local_Var_Table.EQUIPMENTPB_POINT_FIELD}
EQUIPMENTPB.is_extendable = false
EQUIPMENTPB.extensions = {}
Equipment_Local_Var_Table.HPEQUIPMENTINFOSYNC_EQUIPMENTS_FIELD.name = "equipments"
Equipment_Local_Var_Table.HPEQUIPMENTINFOSYNC_EQUIPMENTS_FIELD.full_name = ".HPEquipmentInfoSync.equipments"
Equipment_Local_Var_Table.HPEQUIPMENTINFOSYNC_EQUIPMENTS_FIELD.number = 1
Equipment_Local_Var_Table.HPEQUIPMENTINFOSYNC_EQUIPMENTS_FIELD.index = 0
Equipment_Local_Var_Table.HPEQUIPMENTINFOSYNC_EQUIPMENTS_FIELD.label = 3
Equipment_Local_Var_Table.HPEQUIPMENTINFOSYNC_EQUIPMENTS_FIELD.has_default_value = false
Equipment_Local_Var_Table.HPEQUIPMENTINFOSYNC_EQUIPMENTS_FIELD.default_value = {}
Equipment_Local_Var_Table.HPEQUIPMENTINFOSYNC_EQUIPMENTS_FIELD.message_type = EQUIPMENTPB
Equipment_Local_Var_Table.HPEQUIPMENTINFOSYNC_EQUIPMENTS_FIELD.type = 11
Equipment_Local_Var_Table.HPEQUIPMENTINFOSYNC_EQUIPMENTS_FIELD.cpp_type = 10

HPEQUIPMENTINFOSYNC.name = "HPEquipmentInfoSync"
HPEQUIPMENTINFOSYNC.full_name = ".HPEquipmentInfoSync"
HPEQUIPMENTINFOSYNC.nested_types = {}
HPEQUIPMENTINFOSYNC.enum_types = {}
HPEQUIPMENTINFOSYNC.fields = {Equipment_Local_Var_Table.HPEQUIPMENTINFOSYNC_EQUIPMENTS_FIELD}
HPEQUIPMENTINFOSYNC.is_extendable = false
HPEQUIPMENTINFOSYNC.extensions = {}
Equipment_Local_Var_Table.HPEQUIPLEVELUPREQ_UUID_FIELD.name = "uuid"
Equipment_Local_Var_Table.HPEQUIPLEVELUPREQ_UUID_FIELD.full_name = ".HPEquipLevelUpReq.uuid"
Equipment_Local_Var_Table.HPEQUIPLEVELUPREQ_UUID_FIELD.number = 1
Equipment_Local_Var_Table.HPEQUIPLEVELUPREQ_UUID_FIELD.index = 0
Equipment_Local_Var_Table.HPEQUIPLEVELUPREQ_UUID_FIELD.label = 2
Equipment_Local_Var_Table.HPEQUIPLEVELUPREQ_UUID_FIELD.has_default_value = false
Equipment_Local_Var_Table.HPEQUIPLEVELUPREQ_UUID_FIELD.default_value = ""
Equipment_Local_Var_Table.HPEQUIPLEVELUPREQ_UUID_FIELD.type = 9
Equipment_Local_Var_Table.HPEQUIPLEVELUPREQ_UUID_FIELD.cpp_type = 9

HPEQUIPLEVELUPREQ.name = "HPEquipLevelUpReq"
HPEQUIPLEVELUPREQ.full_name = ".HPEquipLevelUpReq"
HPEQUIPLEVELUPREQ.nested_types = {}
HPEQUIPLEVELUPREQ.enum_types = {}
HPEQUIPLEVELUPREQ.fields = {Equipment_Local_Var_Table.HPEQUIPLEVELUPREQ_UUID_FIELD}
HPEQUIPLEVELUPREQ.is_extendable = false
HPEQUIPLEVELUPREQ.extensions = {}
Equipment_Local_Var_Table.HPEQUIPENHANCEREQ_UUID_FIELD.name = "uuid"
Equipment_Local_Var_Table.HPEQUIPENHANCEREQ_UUID_FIELD.full_name = ".HPEquipEnhanceReq.uuid"
Equipment_Local_Var_Table.HPEQUIPENHANCEREQ_UUID_FIELD.number = 1
Equipment_Local_Var_Table.HPEQUIPENHANCEREQ_UUID_FIELD.index = 0
Equipment_Local_Var_Table.HPEQUIPENHANCEREQ_UUID_FIELD.label = 2
Equipment_Local_Var_Table.HPEQUIPENHANCEREQ_UUID_FIELD.has_default_value = false
Equipment_Local_Var_Table.HPEQUIPENHANCEREQ_UUID_FIELD.default_value = ""
Equipment_Local_Var_Table.HPEQUIPENHANCEREQ_UUID_FIELD.type = 9
Equipment_Local_Var_Table.HPEQUIPENHANCEREQ_UUID_FIELD.cpp_type = 9

HPEQUIPENHANCEREQ.name = "HPEquipEnhanceReq"
HPEQUIPENHANCEREQ.full_name = ".HPEquipEnhanceReq"
HPEQUIPENHANCEREQ.nested_types = {}
HPEQUIPENHANCEREQ.enum_types = {}
HPEQUIPENHANCEREQ.fields = {Equipment_Local_Var_Table.HPEQUIPENHANCEREQ_UUID_FIELD}
HPEQUIPENHANCEREQ.is_extendable = false
HPEQUIPENHANCEREQ.extensions = {}
Equipment_Local_Var_Table.HPEQUIPENHANCERESP_RESULT_FIELD.name = "result"
Equipment_Local_Var_Table.HPEQUIPENHANCERESP_RESULT_FIELD.full_name = ".HPEquipEnhanceResp.result"
Equipment_Local_Var_Table.HPEQUIPENHANCERESP_RESULT_FIELD.number = 1
Equipment_Local_Var_Table.HPEQUIPENHANCERESP_RESULT_FIELD.index = 0
Equipment_Local_Var_Table.HPEQUIPENHANCERESP_RESULT_FIELD.label = 2
Equipment_Local_Var_Table.HPEQUIPENHANCERESP_RESULT_FIELD.has_default_value = false
Equipment_Local_Var_Table.HPEQUIPENHANCERESP_RESULT_FIELD.default_value = false
Equipment_Local_Var_Table.HPEQUIPENHANCERESP_RESULT_FIELD.type = 8
Equipment_Local_Var_Table.HPEQUIPENHANCERESP_RESULT_FIELD.cpp_type = 7

Equipment_Local_Var_Table.HPEQUIPENHANCERESP_POINT_FIELD.name = "point"
Equipment_Local_Var_Table.HPEQUIPENHANCERESP_POINT_FIELD.full_name = ".HPEquipEnhanceResp.point"
Equipment_Local_Var_Table.HPEQUIPENHANCERESP_POINT_FIELD.number = 2
Equipment_Local_Var_Table.HPEQUIPENHANCERESP_POINT_FIELD.index = 1
Equipment_Local_Var_Table.HPEQUIPENHANCERESP_POINT_FIELD.label = 1
Equipment_Local_Var_Table.HPEQUIPENHANCERESP_POINT_FIELD.has_default_value = false
Equipment_Local_Var_Table.HPEQUIPENHANCERESP_POINT_FIELD.default_value = 0
Equipment_Local_Var_Table.HPEQUIPENHANCERESP_POINT_FIELD.type = 5
Equipment_Local_Var_Table.HPEQUIPENHANCERESP_POINT_FIELD.cpp_type = 1

HPEQUIPENHANCERESP.name = "HPEquipEnhanceResp"
HPEQUIPENHANCERESP.full_name = ".HPEquipEnhanceResp"
HPEQUIPENHANCERESP.nested_types = {}
HPEQUIPENHANCERESP.enum_types = {}
HPEQUIPENHANCERESP.fields = {Equipment_Local_Var_Table.HPEQUIPENHANCERESP_RESULT_FIELD, Equipment_Local_Var_Table.HPEQUIPENHANCERESP_POINT_FIELD}
HPEQUIPENHANCERESP.is_extendable = false
HPEQUIPENHANCERESP.extensions = {}
Equipment_Local_Var_Table.HPPLAYEREQUIPINFOREQ_PLAYERID_FIELD.name = "playerId"
Equipment_Local_Var_Table.HPPLAYEREQUIPINFOREQ_PLAYERID_FIELD.full_name = ".HPPlayerEquipInfoReq.playerId"
Equipment_Local_Var_Table.HPPLAYEREQUIPINFOREQ_PLAYERID_FIELD.number = 1
Equipment_Local_Var_Table.HPPLAYEREQUIPINFOREQ_PLAYERID_FIELD.index = 0
Equipment_Local_Var_Table.HPPLAYEREQUIPINFOREQ_PLAYERID_FIELD.label = 2
Equipment_Local_Var_Table.HPPLAYEREQUIPINFOREQ_PLAYERID_FIELD.has_default_value = false
Equipment_Local_Var_Table.HPPLAYEREQUIPINFOREQ_PLAYERID_FIELD.default_value = ""
Equipment_Local_Var_Table.HPPLAYEREQUIPINFOREQ_PLAYERID_FIELD.type = 9
Equipment_Local_Var_Table.HPPLAYEREQUIPINFOREQ_PLAYERID_FIELD.cpp_type = 9

HPPLAYEREQUIPINFOREQ.name = "HPPlayerEquipInfoReq"
HPPLAYEREQUIPINFOREQ.full_name = ".HPPlayerEquipInfoReq"
HPPLAYEREQUIPINFOREQ.nested_types = {}
HPPLAYEREQUIPINFOREQ.enum_types = {}
HPPLAYEREQUIPINFOREQ.fields = {Equipment_Local_Var_Table.HPPLAYEREQUIPINFOREQ_PLAYERID_FIELD}
HPPLAYEREQUIPINFOREQ.is_extendable = false
HPPLAYEREQUIPINFOREQ.extensions = {}
Equipment_Local_Var_Table.HPPLAYEREQUIPINFORESP_EQUIPMENTS_FIELD.name = "equipments"
Equipment_Local_Var_Table.HPPLAYEREQUIPINFORESP_EQUIPMENTS_FIELD.full_name = ".HPPlayerEquipInfoResp.equipments"
Equipment_Local_Var_Table.HPPLAYEREQUIPINFORESP_EQUIPMENTS_FIELD.number = 1
Equipment_Local_Var_Table.HPPLAYEREQUIPINFORESP_EQUIPMENTS_FIELD.index = 0
Equipment_Local_Var_Table.HPPLAYEREQUIPINFORESP_EQUIPMENTS_FIELD.label = 3
Equipment_Local_Var_Table.HPPLAYEREQUIPINFORESP_EQUIPMENTS_FIELD.has_default_value = false
Equipment_Local_Var_Table.HPPLAYEREQUIPINFORESP_EQUIPMENTS_FIELD.default_value = {}
Equipment_Local_Var_Table.HPPLAYEREQUIPINFORESP_EQUIPMENTS_FIELD.message_type = EQUIPMENTPB
Equipment_Local_Var_Table.HPPLAYEREQUIPINFORESP_EQUIPMENTS_FIELD.type = 11
Equipment_Local_Var_Table.HPPLAYEREQUIPINFORESP_EQUIPMENTS_FIELD.cpp_type = 10

HPPLAYEREQUIPINFORESP.name = "HPPlayerEquipInfoResp"
HPPLAYEREQUIPINFORESP.full_name = ".HPPlayerEquipInfoResp"
HPPLAYEREQUIPINFORESP.nested_types = {}
HPPLAYEREQUIPINFORESP.enum_types = {}
HPPLAYEREQUIPINFORESP.fields = {Equipment_Local_Var_Table.HPPLAYEREQUIPINFORESP_EQUIPMENTS_FIELD}
HPPLAYEREQUIPINFORESP.is_extendable = false
HPPLAYEREQUIPINFORESP.extensions = {}

EquipmentPB = protobuf.Message(EQUIPMENTPB)
HPEquipEnhanceReq = protobuf.Message(HPEQUIPENHANCEREQ)
HPEquipEnhanceResp = protobuf.Message(HPEQUIPENHANCERESP)
HPEquipLevelUpReq = protobuf.Message(HPEQUIPLEVELUPREQ)
HPEquipmentInfoSync = protobuf.Message(HPEQUIPMENTINFOSYNC)
HPPlayerEquipInfoReq = protobuf.Message(HPPLAYEREQUIPINFOREQ)
HPPlayerEquipInfoResp = protobuf.Message(HPPLAYEREQUIPINFORESP)

