-- Generated By protoc-gen-lua Do not Edit


local Item_Local_Var_Table = {}

local protobuf = require "protobuf"
module('Item_pb')


ITEMINFO = protobuf.Descriptor();
Item_Local_Var_Table.ITEMINFO_UUID_FIELD = protobuf.FieldDescriptor();
Item_Local_Var_Table.ITEMINFO_ITEMID_FIELD = protobuf.FieldDescriptor();
Item_Local_Var_Table.ITEMINFO_COUNT_FIELD = protobuf.FieldDescriptor();
Item_Local_Var_Table.ITEMINFO_ISNEW_FIELD = protobuf.FieldDescriptor();
HPITEMINFOSYNC = protobuf.Descriptor();
Item_Local_Var_Table.HPITEMINFOSYNC_ITEMINFOS_FIELD = protobuf.FieldDescriptor();
HPITEMUSEREQ = protobuf.Descriptor();
Item_Local_Var_Table.HPITEMUSEREQ_UUID_FIELD = protobuf.FieldDescriptor();
Item_Local_Var_Table.HPITEMUSEREQ_ITEMCOUNT_FIELD = protobuf.FieldDescriptor();
HPITEMUSEBYITEMIDREQ = protobuf.Descriptor();
Item_Local_Var_Table.HPITEMUSEBYITEMIDREQ_ITEMID_FIELD = protobuf.FieldDescriptor();
Item_Local_Var_Table.HPITEMUSEBYITEMIDREQ_ITEMCOUNT_FIELD = protobuf.FieldDescriptor();
HPITEMBUYREQ = protobuf.Descriptor();
Item_Local_Var_Table.HPITEMBUYREQ_SHOPID_FIELD = protobuf.FieldDescriptor();
Item_Local_Var_Table.HPITEMBUYREQ_ITEMCOUNT_FIELD = protobuf.FieldDescriptor();
HPITEMBUYANDUSEREQ = protobuf.Descriptor();
Item_Local_Var_Table.HPITEMBUYANDUSEREQ_ITEMID_FIELD = protobuf.FieldDescriptor();
Item_Local_Var_Table.HPITEMBUYANDUSEREQ_ITEMCOUNT_FIELD = protobuf.FieldDescriptor();
HOTSALESINFO = protobuf.Descriptor();
Item_Local_Var_Table.HOTSALESINFO_SALESID_FIELD = protobuf.FieldDescriptor();
Item_Local_Var_Table.HOTSALESINFO_ENDTIME_FIELD = protobuf.FieldDescriptor();
Item_Local_Var_Table.HOTSALESINFO_ISALREADYBUY_FIELD = protobuf.FieldDescriptor();
HPBUYHOTREQ = protobuf.Descriptor();
Item_Local_Var_Table.HPBUYHOTREQ_SALESID_FIELD = protobuf.FieldDescriptor();

Item_Local_Var_Table.ITEMINFO_UUID_FIELD.name = "uuid"
Item_Local_Var_Table.ITEMINFO_UUID_FIELD.full_name = ".ItemInfo.uuid"
Item_Local_Var_Table.ITEMINFO_UUID_FIELD.number = 1
Item_Local_Var_Table.ITEMINFO_UUID_FIELD.index = 0
Item_Local_Var_Table.ITEMINFO_UUID_FIELD.label = 2
Item_Local_Var_Table.ITEMINFO_UUID_FIELD.has_default_value = false
Item_Local_Var_Table.ITEMINFO_UUID_FIELD.default_value = ""
Item_Local_Var_Table.ITEMINFO_UUID_FIELD.type = 9
Item_Local_Var_Table.ITEMINFO_UUID_FIELD.cpp_type = 9

Item_Local_Var_Table.ITEMINFO_ITEMID_FIELD.name = "itemId"
Item_Local_Var_Table.ITEMINFO_ITEMID_FIELD.full_name = ".ItemInfo.itemId"
Item_Local_Var_Table.ITEMINFO_ITEMID_FIELD.number = 2
Item_Local_Var_Table.ITEMINFO_ITEMID_FIELD.index = 1
Item_Local_Var_Table.ITEMINFO_ITEMID_FIELD.label = 2
Item_Local_Var_Table.ITEMINFO_ITEMID_FIELD.has_default_value = false
Item_Local_Var_Table.ITEMINFO_ITEMID_FIELD.default_value = 0
Item_Local_Var_Table.ITEMINFO_ITEMID_FIELD.type = 5
Item_Local_Var_Table.ITEMINFO_ITEMID_FIELD.cpp_type = 1

Item_Local_Var_Table.ITEMINFO_COUNT_FIELD.name = "count"
Item_Local_Var_Table.ITEMINFO_COUNT_FIELD.full_name = ".ItemInfo.count"
Item_Local_Var_Table.ITEMINFO_COUNT_FIELD.number = 3
Item_Local_Var_Table.ITEMINFO_COUNT_FIELD.index = 2
Item_Local_Var_Table.ITEMINFO_COUNT_FIELD.label = 2
Item_Local_Var_Table.ITEMINFO_COUNT_FIELD.has_default_value = false
Item_Local_Var_Table.ITEMINFO_COUNT_FIELD.default_value = 0
Item_Local_Var_Table.ITEMINFO_COUNT_FIELD.type = 5
Item_Local_Var_Table.ITEMINFO_COUNT_FIELD.cpp_type = 1

Item_Local_Var_Table.ITEMINFO_ISNEW_FIELD.name = "isNew"
Item_Local_Var_Table.ITEMINFO_ISNEW_FIELD.full_name = ".ItemInfo.isNew"
Item_Local_Var_Table.ITEMINFO_ISNEW_FIELD.number = 4
Item_Local_Var_Table.ITEMINFO_ISNEW_FIELD.index = 3
Item_Local_Var_Table.ITEMINFO_ISNEW_FIELD.label = 2
Item_Local_Var_Table.ITEMINFO_ISNEW_FIELD.has_default_value = false
Item_Local_Var_Table.ITEMINFO_ISNEW_FIELD.default_value = false
Item_Local_Var_Table.ITEMINFO_ISNEW_FIELD.type = 8
Item_Local_Var_Table.ITEMINFO_ISNEW_FIELD.cpp_type = 7

ITEMINFO.name = "ItemInfo"
ITEMINFO.full_name = ".ItemInfo"
ITEMINFO.nested_types = {}
ITEMINFO.enum_types = {}
ITEMINFO.fields = {Item_Local_Var_Table.ITEMINFO_UUID_FIELD, Item_Local_Var_Table.ITEMINFO_ITEMID_FIELD, Item_Local_Var_Table.ITEMINFO_COUNT_FIELD, Item_Local_Var_Table.ITEMINFO_ISNEW_FIELD}
ITEMINFO.is_extendable = false
ITEMINFO.extensions = {}
Item_Local_Var_Table.HPITEMINFOSYNC_ITEMINFOS_FIELD.name = "itemInfos"
Item_Local_Var_Table.HPITEMINFOSYNC_ITEMINFOS_FIELD.full_name = ".HPItemInfoSync.itemInfos"
Item_Local_Var_Table.HPITEMINFOSYNC_ITEMINFOS_FIELD.number = 1
Item_Local_Var_Table.HPITEMINFOSYNC_ITEMINFOS_FIELD.index = 0
Item_Local_Var_Table.HPITEMINFOSYNC_ITEMINFOS_FIELD.label = 3
Item_Local_Var_Table.HPITEMINFOSYNC_ITEMINFOS_FIELD.has_default_value = false
Item_Local_Var_Table.HPITEMINFOSYNC_ITEMINFOS_FIELD.default_value = {}
Item_Local_Var_Table.HPITEMINFOSYNC_ITEMINFOS_FIELD.message_type = ITEMINFO
Item_Local_Var_Table.HPITEMINFOSYNC_ITEMINFOS_FIELD.type = 11
Item_Local_Var_Table.HPITEMINFOSYNC_ITEMINFOS_FIELD.cpp_type = 10

HPITEMINFOSYNC.name = "HPItemInfoSync"
HPITEMINFOSYNC.full_name = ".HPItemInfoSync"
HPITEMINFOSYNC.nested_types = {}
HPITEMINFOSYNC.enum_types = {}
HPITEMINFOSYNC.fields = {Item_Local_Var_Table.HPITEMINFOSYNC_ITEMINFOS_FIELD}
HPITEMINFOSYNC.is_extendable = false
HPITEMINFOSYNC.extensions = {}
Item_Local_Var_Table.HPITEMUSEREQ_UUID_FIELD.name = "uuid"
Item_Local_Var_Table.HPITEMUSEREQ_UUID_FIELD.full_name = ".HPItemUseReq.uuid"
Item_Local_Var_Table.HPITEMUSEREQ_UUID_FIELD.number = 1
Item_Local_Var_Table.HPITEMUSEREQ_UUID_FIELD.index = 0
Item_Local_Var_Table.HPITEMUSEREQ_UUID_FIELD.label = 2
Item_Local_Var_Table.HPITEMUSEREQ_UUID_FIELD.has_default_value = false
Item_Local_Var_Table.HPITEMUSEREQ_UUID_FIELD.default_value = ""
Item_Local_Var_Table.HPITEMUSEREQ_UUID_FIELD.type = 9
Item_Local_Var_Table.HPITEMUSEREQ_UUID_FIELD.cpp_type = 9

Item_Local_Var_Table.HPITEMUSEREQ_ITEMCOUNT_FIELD.name = "itemCount"
Item_Local_Var_Table.HPITEMUSEREQ_ITEMCOUNT_FIELD.full_name = ".HPItemUseReq.itemCount"
Item_Local_Var_Table.HPITEMUSEREQ_ITEMCOUNT_FIELD.number = 2
Item_Local_Var_Table.HPITEMUSEREQ_ITEMCOUNT_FIELD.index = 1
Item_Local_Var_Table.HPITEMUSEREQ_ITEMCOUNT_FIELD.label = 2
Item_Local_Var_Table.HPITEMUSEREQ_ITEMCOUNT_FIELD.has_default_value = false
Item_Local_Var_Table.HPITEMUSEREQ_ITEMCOUNT_FIELD.default_value = 0
Item_Local_Var_Table.HPITEMUSEREQ_ITEMCOUNT_FIELD.type = 5
Item_Local_Var_Table.HPITEMUSEREQ_ITEMCOUNT_FIELD.cpp_type = 1

HPITEMUSEREQ.name = "HPItemUseReq"
HPITEMUSEREQ.full_name = ".HPItemUseReq"
HPITEMUSEREQ.nested_types = {}
HPITEMUSEREQ.enum_types = {}
HPITEMUSEREQ.fields = {Item_Local_Var_Table.HPITEMUSEREQ_UUID_FIELD, Item_Local_Var_Table.HPITEMUSEREQ_ITEMCOUNT_FIELD}
HPITEMUSEREQ.is_extendable = false
HPITEMUSEREQ.extensions = {}
Item_Local_Var_Table.HPITEMUSEBYITEMIDREQ_ITEMID_FIELD.name = "itemId"
Item_Local_Var_Table.HPITEMUSEBYITEMIDREQ_ITEMID_FIELD.full_name = ".HPItemUseByItemIdReq.itemId"
Item_Local_Var_Table.HPITEMUSEBYITEMIDREQ_ITEMID_FIELD.number = 1
Item_Local_Var_Table.HPITEMUSEBYITEMIDREQ_ITEMID_FIELD.index = 0
Item_Local_Var_Table.HPITEMUSEBYITEMIDREQ_ITEMID_FIELD.label = 2
Item_Local_Var_Table.HPITEMUSEBYITEMIDREQ_ITEMID_FIELD.has_default_value = false
Item_Local_Var_Table.HPITEMUSEBYITEMIDREQ_ITEMID_FIELD.default_value = 0
Item_Local_Var_Table.HPITEMUSEBYITEMIDREQ_ITEMID_FIELD.type = 5
Item_Local_Var_Table.HPITEMUSEBYITEMIDREQ_ITEMID_FIELD.cpp_type = 1

Item_Local_Var_Table.HPITEMUSEBYITEMIDREQ_ITEMCOUNT_FIELD.name = "itemCount"
Item_Local_Var_Table.HPITEMUSEBYITEMIDREQ_ITEMCOUNT_FIELD.full_name = ".HPItemUseByItemIdReq.itemCount"
Item_Local_Var_Table.HPITEMUSEBYITEMIDREQ_ITEMCOUNT_FIELD.number = 2
Item_Local_Var_Table.HPITEMUSEBYITEMIDREQ_ITEMCOUNT_FIELD.index = 1
Item_Local_Var_Table.HPITEMUSEBYITEMIDREQ_ITEMCOUNT_FIELD.label = 2
Item_Local_Var_Table.HPITEMUSEBYITEMIDREQ_ITEMCOUNT_FIELD.has_default_value = false
Item_Local_Var_Table.HPITEMUSEBYITEMIDREQ_ITEMCOUNT_FIELD.default_value = 0
Item_Local_Var_Table.HPITEMUSEBYITEMIDREQ_ITEMCOUNT_FIELD.type = 5
Item_Local_Var_Table.HPITEMUSEBYITEMIDREQ_ITEMCOUNT_FIELD.cpp_type = 1

HPITEMUSEBYITEMIDREQ.name = "HPItemUseByItemIdReq"
HPITEMUSEBYITEMIDREQ.full_name = ".HPItemUseByItemIdReq"
HPITEMUSEBYITEMIDREQ.nested_types = {}
HPITEMUSEBYITEMIDREQ.enum_types = {}
HPITEMUSEBYITEMIDREQ.fields = {Item_Local_Var_Table.HPITEMUSEBYITEMIDREQ_ITEMID_FIELD, Item_Local_Var_Table.HPITEMUSEBYITEMIDREQ_ITEMCOUNT_FIELD}
HPITEMUSEBYITEMIDREQ.is_extendable = false
HPITEMUSEBYITEMIDREQ.extensions = {}
Item_Local_Var_Table.HPITEMBUYREQ_SHOPID_FIELD.name = "shopId"
Item_Local_Var_Table.HPITEMBUYREQ_SHOPID_FIELD.full_name = ".HPItemBuyReq.shopId"
Item_Local_Var_Table.HPITEMBUYREQ_SHOPID_FIELD.number = 1
Item_Local_Var_Table.HPITEMBUYREQ_SHOPID_FIELD.index = 0
Item_Local_Var_Table.HPITEMBUYREQ_SHOPID_FIELD.label = 2
Item_Local_Var_Table.HPITEMBUYREQ_SHOPID_FIELD.has_default_value = false
Item_Local_Var_Table.HPITEMBUYREQ_SHOPID_FIELD.default_value = 0
Item_Local_Var_Table.HPITEMBUYREQ_SHOPID_FIELD.type = 5
Item_Local_Var_Table.HPITEMBUYREQ_SHOPID_FIELD.cpp_type = 1

Item_Local_Var_Table.HPITEMBUYREQ_ITEMCOUNT_FIELD.name = "itemCount"
Item_Local_Var_Table.HPITEMBUYREQ_ITEMCOUNT_FIELD.full_name = ".HPItemBuyReq.itemCount"
Item_Local_Var_Table.HPITEMBUYREQ_ITEMCOUNT_FIELD.number = 2
Item_Local_Var_Table.HPITEMBUYREQ_ITEMCOUNT_FIELD.index = 1
Item_Local_Var_Table.HPITEMBUYREQ_ITEMCOUNT_FIELD.label = 2
Item_Local_Var_Table.HPITEMBUYREQ_ITEMCOUNT_FIELD.has_default_value = false
Item_Local_Var_Table.HPITEMBUYREQ_ITEMCOUNT_FIELD.default_value = 0
Item_Local_Var_Table.HPITEMBUYREQ_ITEMCOUNT_FIELD.type = 5
Item_Local_Var_Table.HPITEMBUYREQ_ITEMCOUNT_FIELD.cpp_type = 1

HPITEMBUYREQ.name = "HPItemBuyReq"
HPITEMBUYREQ.full_name = ".HPItemBuyReq"
HPITEMBUYREQ.nested_types = {}
HPITEMBUYREQ.enum_types = {}
HPITEMBUYREQ.fields = {Item_Local_Var_Table.HPITEMBUYREQ_SHOPID_FIELD, Item_Local_Var_Table.HPITEMBUYREQ_ITEMCOUNT_FIELD}
HPITEMBUYREQ.is_extendable = false
HPITEMBUYREQ.extensions = {}
Item_Local_Var_Table.HPITEMBUYANDUSEREQ_ITEMID_FIELD.name = "itemId"
Item_Local_Var_Table.HPITEMBUYANDUSEREQ_ITEMID_FIELD.full_name = ".HPItemBuyAndUseReq.itemId"
Item_Local_Var_Table.HPITEMBUYANDUSEREQ_ITEMID_FIELD.number = 1
Item_Local_Var_Table.HPITEMBUYANDUSEREQ_ITEMID_FIELD.index = 0
Item_Local_Var_Table.HPITEMBUYANDUSEREQ_ITEMID_FIELD.label = 2
Item_Local_Var_Table.HPITEMBUYANDUSEREQ_ITEMID_FIELD.has_default_value = false
Item_Local_Var_Table.HPITEMBUYANDUSEREQ_ITEMID_FIELD.default_value = 0
Item_Local_Var_Table.HPITEMBUYANDUSEREQ_ITEMID_FIELD.type = 5
Item_Local_Var_Table.HPITEMBUYANDUSEREQ_ITEMID_FIELD.cpp_type = 1

Item_Local_Var_Table.HPITEMBUYANDUSEREQ_ITEMCOUNT_FIELD.name = "itemCount"
Item_Local_Var_Table.HPITEMBUYANDUSEREQ_ITEMCOUNT_FIELD.full_name = ".HPItemBuyAndUseReq.itemCount"
Item_Local_Var_Table.HPITEMBUYANDUSEREQ_ITEMCOUNT_FIELD.number = 2
Item_Local_Var_Table.HPITEMBUYANDUSEREQ_ITEMCOUNT_FIELD.index = 1
Item_Local_Var_Table.HPITEMBUYANDUSEREQ_ITEMCOUNT_FIELD.label = 2
Item_Local_Var_Table.HPITEMBUYANDUSEREQ_ITEMCOUNT_FIELD.has_default_value = false
Item_Local_Var_Table.HPITEMBUYANDUSEREQ_ITEMCOUNT_FIELD.default_value = 0
Item_Local_Var_Table.HPITEMBUYANDUSEREQ_ITEMCOUNT_FIELD.type = 5
Item_Local_Var_Table.HPITEMBUYANDUSEREQ_ITEMCOUNT_FIELD.cpp_type = 1

HPITEMBUYANDUSEREQ.name = "HPItemBuyAndUseReq"
HPITEMBUYANDUSEREQ.full_name = ".HPItemBuyAndUseReq"
HPITEMBUYANDUSEREQ.nested_types = {}
HPITEMBUYANDUSEREQ.enum_types = {}
HPITEMBUYANDUSEREQ.fields = {Item_Local_Var_Table.HPITEMBUYANDUSEREQ_ITEMID_FIELD, Item_Local_Var_Table.HPITEMBUYANDUSEREQ_ITEMCOUNT_FIELD}
HPITEMBUYANDUSEREQ.is_extendable = false
HPITEMBUYANDUSEREQ.extensions = {}
Item_Local_Var_Table.HOTSALESINFO_SALESID_FIELD.name = "salesId"
Item_Local_Var_Table.HOTSALESINFO_SALESID_FIELD.full_name = ".HotSalesInfo.salesId"
Item_Local_Var_Table.HOTSALESINFO_SALESID_FIELD.number = 1
Item_Local_Var_Table.HOTSALESINFO_SALESID_FIELD.index = 0
Item_Local_Var_Table.HOTSALESINFO_SALESID_FIELD.label = 2
Item_Local_Var_Table.HOTSALESINFO_SALESID_FIELD.has_default_value = false
Item_Local_Var_Table.HOTSALESINFO_SALESID_FIELD.default_value = 0
Item_Local_Var_Table.HOTSALESINFO_SALESID_FIELD.type = 5
Item_Local_Var_Table.HOTSALESINFO_SALESID_FIELD.cpp_type = 1

Item_Local_Var_Table.HOTSALESINFO_ENDTIME_FIELD.name = "endTime"
Item_Local_Var_Table.HOTSALESINFO_ENDTIME_FIELD.full_name = ".HotSalesInfo.endTime"
Item_Local_Var_Table.HOTSALESINFO_ENDTIME_FIELD.number = 2
Item_Local_Var_Table.HOTSALESINFO_ENDTIME_FIELD.index = 1
Item_Local_Var_Table.HOTSALESINFO_ENDTIME_FIELD.label = 2
Item_Local_Var_Table.HOTSALESINFO_ENDTIME_FIELD.has_default_value = false
Item_Local_Var_Table.HOTSALESINFO_ENDTIME_FIELD.default_value = 0
Item_Local_Var_Table.HOTSALESINFO_ENDTIME_FIELD.type = 3
Item_Local_Var_Table.HOTSALESINFO_ENDTIME_FIELD.cpp_type = 2

Item_Local_Var_Table.HOTSALESINFO_ISALREADYBUY_FIELD.name = "isAlreadyBuy"
Item_Local_Var_Table.HOTSALESINFO_ISALREADYBUY_FIELD.full_name = ".HotSalesInfo.isAlreadyBuy"
Item_Local_Var_Table.HOTSALESINFO_ISALREADYBUY_FIELD.number = 3
Item_Local_Var_Table.HOTSALESINFO_ISALREADYBUY_FIELD.index = 2
Item_Local_Var_Table.HOTSALESINFO_ISALREADYBUY_FIELD.label = 2
Item_Local_Var_Table.HOTSALESINFO_ISALREADYBUY_FIELD.has_default_value = false
Item_Local_Var_Table.HOTSALESINFO_ISALREADYBUY_FIELD.default_value = false
Item_Local_Var_Table.HOTSALESINFO_ISALREADYBUY_FIELD.type = 8
Item_Local_Var_Table.HOTSALESINFO_ISALREADYBUY_FIELD.cpp_type = 7

HOTSALESINFO.name = "HotSalesInfo"
HOTSALESINFO.full_name = ".HotSalesInfo"
HOTSALESINFO.nested_types = {}
HOTSALESINFO.enum_types = {}
HOTSALESINFO.fields = {Item_Local_Var_Table.HOTSALESINFO_SALESID_FIELD, Item_Local_Var_Table.HOTSALESINFO_ENDTIME_FIELD, Item_Local_Var_Table.HOTSALESINFO_ISALREADYBUY_FIELD}
HOTSALESINFO.is_extendable = false
HOTSALESINFO.extensions = {}
Item_Local_Var_Table.HPBUYHOTREQ_SALESID_FIELD.name = "salesId"
Item_Local_Var_Table.HPBUYHOTREQ_SALESID_FIELD.full_name = ".HPBuyHotReq.salesId"
Item_Local_Var_Table.HPBUYHOTREQ_SALESID_FIELD.number = 1
Item_Local_Var_Table.HPBUYHOTREQ_SALESID_FIELD.index = 0
Item_Local_Var_Table.HPBUYHOTREQ_SALESID_FIELD.label = 2
Item_Local_Var_Table.HPBUYHOTREQ_SALESID_FIELD.has_default_value = false
Item_Local_Var_Table.HPBUYHOTREQ_SALESID_FIELD.default_value = 0
Item_Local_Var_Table.HPBUYHOTREQ_SALESID_FIELD.type = 5
Item_Local_Var_Table.HPBUYHOTREQ_SALESID_FIELD.cpp_type = 1

HPBUYHOTREQ.name = "HPBuyHotReq"
HPBUYHOTREQ.full_name = ".HPBuyHotReq"
HPBUYHOTREQ.nested_types = {}
HPBUYHOTREQ.enum_types = {}
HPBUYHOTREQ.fields = {Item_Local_Var_Table.HPBUYHOTREQ_SALESID_FIELD}
HPBUYHOTREQ.is_extendable = false
HPBUYHOTREQ.extensions = {}

HPBuyHotReq = protobuf.Message(HPBUYHOTREQ)
HPItemBuyAndUseReq = protobuf.Message(HPITEMBUYANDUSEREQ)
HPItemBuyReq = protobuf.Message(HPITEMBUYREQ)
HPItemInfoSync = protobuf.Message(HPITEMINFOSYNC)
HPItemUseByItemIdReq = protobuf.Message(HPITEMUSEBYITEMIDREQ)
HPItemUseReq = protobuf.Message(HPITEMUSEREQ)
HotSalesInfo = protobuf.Message(HOTSALESINFO)
ItemInfo = protobuf.Message(ITEMINFO)

