-- Generated By protoc-gen-lua Do not Edit


local Login_Local_Var_Table = {}

local protobuf = require "protobuf"
module('Login_pb')


HPLOGIN = protobuf.Descriptor();
Login_Local_Var_Table.HPLOGIN_PLATFORM_FIELD = protobuf.FieldDescriptor();
Login_Local_Var_Table.HPLOGIN_CHANNEL_FIELD = protobuf.FieldDescriptor();
Login_Local_Var_Table.HPLOGIN_COUNTRY_FIELD = protobuf.FieldDescriptor();
Login_Local_Var_Table.HPLOGIN_DEVICEID_FIELD = protobuf.FieldDescriptor();
Login_Local_Var_Table.HPLOGIN_LANG_FIELD = protobuf.FieldDescriptor();
Login_Local_Var_Table.HPLOGIN_PHONEINFO_FIELD = protobuf.FieldDescriptor();
Login_Local_Var_Table.HPLOGIN_VERSION_FIELD = protobuf.FieldDescriptor();
Login_Local_Var_Table.HPLOGIN_PLAYERID_FIELD = protobuf.FieldDescriptor();
Login_Local_Var_Table.HPLOGIN_PUID_FIELD = protobuf.FieldDescriptor();
Login_Local_Var_Table.HPLOGIN_TOKEN_FIELD = protobuf.FieldDescriptor();
Login_Local_Var_Table.HPLOGIN_PUSHINFO_FIELD = protobuf.FieldDescriptor();
Login_Local_Var_Table.HPLOGIN_FLAG_FIELD = protobuf.FieldDescriptor();
HPLOGINRET = protobuf.Descriptor();
Login_Local_Var_Table.HPLOGINRET_ERRCODE_FIELD = protobuf.FieldDescriptor();
Login_Local_Var_Table.HPLOGINRET_PLAYERID_FIELD = protobuf.FieldDescriptor();
Login_Local_Var_Table.HPLOGINRET_PUID_FIELD = protobuf.FieldDescriptor();
Login_Local_Var_Table.HPLOGINRET_TIMESTAMP_FIELD = protobuf.FieldDescriptor();
Login_Local_Var_Table.HPLOGINRET_SERVEROPENTIME_FIELD = protobuf.FieldDescriptor();
Login_Local_Var_Table.HPLOGINRET_FLAG_FIELD = protobuf.FieldDescriptor();
HPACTIVEDEVICE = protobuf.Descriptor();
Login_Local_Var_Table.HPACTIVEDEVICE_DEVICEID_FIELD = protobuf.FieldDescriptor();
Login_Local_Var_Table.HPACTIVEDEVICE_ACTIVETOKEN_FIELD = protobuf.FieldDescriptor();
HPACTIVEDEVICERET = protobuf.Descriptor();
Login_Local_Var_Table.HPACTIVEDEVICERET_DEVICEID_FIELD = protobuf.FieldDescriptor();
Login_Local_Var_Table.HPACTIVEDEVICERET_CODE_FIELD = protobuf.FieldDescriptor();
HPASSEMBLEFINISH = protobuf.Descriptor();
Login_Local_Var_Table.HPASSEMBLEFINISH_PLAYERID_FIELD = protobuf.FieldDescriptor();
Login_Local_Var_Table.HPASSEMBLEFINISH_TOKEN_FIELD = protobuf.FieldDescriptor();
HPPLAYERKICKOUT = protobuf.Descriptor();
Login_Local_Var_Table.HPPLAYERKICKOUT_REASON_FIELD = protobuf.FieldDescriptor();

Login_Local_Var_Table.HPLOGIN_PLATFORM_FIELD.name = "platform"
Login_Local_Var_Table.HPLOGIN_PLATFORM_FIELD.full_name = ".HPLogin.platform"
Login_Local_Var_Table.HPLOGIN_PLATFORM_FIELD.number = 1
Login_Local_Var_Table.HPLOGIN_PLATFORM_FIELD.index = 0
Login_Local_Var_Table.HPLOGIN_PLATFORM_FIELD.label = 2
Login_Local_Var_Table.HPLOGIN_PLATFORM_FIELD.has_default_value = false
Login_Local_Var_Table.HPLOGIN_PLATFORM_FIELD.default_value = ""
Login_Local_Var_Table.HPLOGIN_PLATFORM_FIELD.type = 9
Login_Local_Var_Table.HPLOGIN_PLATFORM_FIELD.cpp_type = 9

Login_Local_Var_Table.HPLOGIN_CHANNEL_FIELD.name = "channel"
Login_Local_Var_Table.HPLOGIN_CHANNEL_FIELD.full_name = ".HPLogin.channel"
Login_Local_Var_Table.HPLOGIN_CHANNEL_FIELD.number = 2
Login_Local_Var_Table.HPLOGIN_CHANNEL_FIELD.index = 1
Login_Local_Var_Table.HPLOGIN_CHANNEL_FIELD.label = 2
Login_Local_Var_Table.HPLOGIN_CHANNEL_FIELD.has_default_value = false
Login_Local_Var_Table.HPLOGIN_CHANNEL_FIELD.default_value = ""
Login_Local_Var_Table.HPLOGIN_CHANNEL_FIELD.type = 9
Login_Local_Var_Table.HPLOGIN_CHANNEL_FIELD.cpp_type = 9

Login_Local_Var_Table.HPLOGIN_COUNTRY_FIELD.name = "country"
Login_Local_Var_Table.HPLOGIN_COUNTRY_FIELD.full_name = ".HPLogin.country"
Login_Local_Var_Table.HPLOGIN_COUNTRY_FIELD.number = 3
Login_Local_Var_Table.HPLOGIN_COUNTRY_FIELD.index = 2
Login_Local_Var_Table.HPLOGIN_COUNTRY_FIELD.label = 2
Login_Local_Var_Table.HPLOGIN_COUNTRY_FIELD.has_default_value = false
Login_Local_Var_Table.HPLOGIN_COUNTRY_FIELD.default_value = ""
Login_Local_Var_Table.HPLOGIN_COUNTRY_FIELD.type = 9
Login_Local_Var_Table.HPLOGIN_COUNTRY_FIELD.cpp_type = 9

Login_Local_Var_Table.HPLOGIN_DEVICEID_FIELD.name = "deviceId"
Login_Local_Var_Table.HPLOGIN_DEVICEID_FIELD.full_name = ".HPLogin.deviceId"
Login_Local_Var_Table.HPLOGIN_DEVICEID_FIELD.number = 4
Login_Local_Var_Table.HPLOGIN_DEVICEID_FIELD.index = 3
Login_Local_Var_Table.HPLOGIN_DEVICEID_FIELD.label = 2
Login_Local_Var_Table.HPLOGIN_DEVICEID_FIELD.has_default_value = false
Login_Local_Var_Table.HPLOGIN_DEVICEID_FIELD.default_value = ""
Login_Local_Var_Table.HPLOGIN_DEVICEID_FIELD.type = 9
Login_Local_Var_Table.HPLOGIN_DEVICEID_FIELD.cpp_type = 9

Login_Local_Var_Table.HPLOGIN_LANG_FIELD.name = "lang"
Login_Local_Var_Table.HPLOGIN_LANG_FIELD.full_name = ".HPLogin.lang"
Login_Local_Var_Table.HPLOGIN_LANG_FIELD.number = 5
Login_Local_Var_Table.HPLOGIN_LANG_FIELD.index = 4
Login_Local_Var_Table.HPLOGIN_LANG_FIELD.label = 2
Login_Local_Var_Table.HPLOGIN_LANG_FIELD.has_default_value = false
Login_Local_Var_Table.HPLOGIN_LANG_FIELD.default_value = ""
Login_Local_Var_Table.HPLOGIN_LANG_FIELD.type = 9
Login_Local_Var_Table.HPLOGIN_LANG_FIELD.cpp_type = 9

Login_Local_Var_Table.HPLOGIN_PHONEINFO_FIELD.name = "phoneInfo"
Login_Local_Var_Table.HPLOGIN_PHONEINFO_FIELD.full_name = ".HPLogin.phoneInfo"
Login_Local_Var_Table.HPLOGIN_PHONEINFO_FIELD.number = 6
Login_Local_Var_Table.HPLOGIN_PHONEINFO_FIELD.index = 5
Login_Local_Var_Table.HPLOGIN_PHONEINFO_FIELD.label = 2
Login_Local_Var_Table.HPLOGIN_PHONEINFO_FIELD.has_default_value = false
Login_Local_Var_Table.HPLOGIN_PHONEINFO_FIELD.default_value = ""
Login_Local_Var_Table.HPLOGIN_PHONEINFO_FIELD.type = 9
Login_Local_Var_Table.HPLOGIN_PHONEINFO_FIELD.cpp_type = 9

Login_Local_Var_Table.HPLOGIN_VERSION_FIELD.name = "version"
Login_Local_Var_Table.HPLOGIN_VERSION_FIELD.full_name = ".HPLogin.version"
Login_Local_Var_Table.HPLOGIN_VERSION_FIELD.number = 7
Login_Local_Var_Table.HPLOGIN_VERSION_FIELD.index = 6
Login_Local_Var_Table.HPLOGIN_VERSION_FIELD.label = 2
Login_Local_Var_Table.HPLOGIN_VERSION_FIELD.has_default_value = false
Login_Local_Var_Table.HPLOGIN_VERSION_FIELD.default_value = ""
Login_Local_Var_Table.HPLOGIN_VERSION_FIELD.type = 9
Login_Local_Var_Table.HPLOGIN_VERSION_FIELD.cpp_type = 9

Login_Local_Var_Table.HPLOGIN_PLAYERID_FIELD.name = "playerId"
Login_Local_Var_Table.HPLOGIN_PLAYERID_FIELD.full_name = ".HPLogin.playerId"
Login_Local_Var_Table.HPLOGIN_PLAYERID_FIELD.number = 8
Login_Local_Var_Table.HPLOGIN_PLAYERID_FIELD.index = 7
Login_Local_Var_Table.HPLOGIN_PLAYERID_FIELD.label = 1
Login_Local_Var_Table.HPLOGIN_PLAYERID_FIELD.has_default_value = false
Login_Local_Var_Table.HPLOGIN_PLAYERID_FIELD.default_value = ""
Login_Local_Var_Table.HPLOGIN_PLAYERID_FIELD.type = 9
Login_Local_Var_Table.HPLOGIN_PLAYERID_FIELD.cpp_type = 9

Login_Local_Var_Table.HPLOGIN_PUID_FIELD.name = "puid"
Login_Local_Var_Table.HPLOGIN_PUID_FIELD.full_name = ".HPLogin.puid"
Login_Local_Var_Table.HPLOGIN_PUID_FIELD.number = 9
Login_Local_Var_Table.HPLOGIN_PUID_FIELD.index = 8
Login_Local_Var_Table.HPLOGIN_PUID_FIELD.label = 1
Login_Local_Var_Table.HPLOGIN_PUID_FIELD.has_default_value = false
Login_Local_Var_Table.HPLOGIN_PUID_FIELD.default_value = ""
Login_Local_Var_Table.HPLOGIN_PUID_FIELD.type = 9
Login_Local_Var_Table.HPLOGIN_PUID_FIELD.cpp_type = 9

Login_Local_Var_Table.HPLOGIN_TOKEN_FIELD.name = "token"
Login_Local_Var_Table.HPLOGIN_TOKEN_FIELD.full_name = ".HPLogin.token"
Login_Local_Var_Table.HPLOGIN_TOKEN_FIELD.number = 10
Login_Local_Var_Table.HPLOGIN_TOKEN_FIELD.index = 9
Login_Local_Var_Table.HPLOGIN_TOKEN_FIELD.label = 1
Login_Local_Var_Table.HPLOGIN_TOKEN_FIELD.has_default_value = false
Login_Local_Var_Table.HPLOGIN_TOKEN_FIELD.default_value = ""
Login_Local_Var_Table.HPLOGIN_TOKEN_FIELD.type = 9
Login_Local_Var_Table.HPLOGIN_TOKEN_FIELD.cpp_type = 9

Login_Local_Var_Table.HPLOGIN_PUSHINFO_FIELD.name = "pushInfo"
Login_Local_Var_Table.HPLOGIN_PUSHINFO_FIELD.full_name = ".HPLogin.pushInfo"
Login_Local_Var_Table.HPLOGIN_PUSHINFO_FIELD.number = 11
Login_Local_Var_Table.HPLOGIN_PUSHINFO_FIELD.index = 10
Login_Local_Var_Table.HPLOGIN_PUSHINFO_FIELD.label = 1
Login_Local_Var_Table.HPLOGIN_PUSHINFO_FIELD.has_default_value = false
Login_Local_Var_Table.HPLOGIN_PUSHINFO_FIELD.default_value = ""
Login_Local_Var_Table.HPLOGIN_PUSHINFO_FIELD.type = 9
Login_Local_Var_Table.HPLOGIN_PUSHINFO_FIELD.cpp_type = 9

Login_Local_Var_Table.HPLOGIN_FLAG_FIELD.name = "flag"
Login_Local_Var_Table.HPLOGIN_FLAG_FIELD.full_name = ".HPLogin.flag"
Login_Local_Var_Table.HPLOGIN_FLAG_FIELD.number = 12
Login_Local_Var_Table.HPLOGIN_FLAG_FIELD.index = 11
Login_Local_Var_Table.HPLOGIN_FLAG_FIELD.label = 1
Login_Local_Var_Table.HPLOGIN_FLAG_FIELD.has_default_value = false
Login_Local_Var_Table.HPLOGIN_FLAG_FIELD.default_value = 0
Login_Local_Var_Table.HPLOGIN_FLAG_FIELD.type = 5
Login_Local_Var_Table.HPLOGIN_FLAG_FIELD.cpp_type = 1

HPLOGIN.name = "HPLogin"
HPLOGIN.full_name = ".HPLogin"
HPLOGIN.nested_types = {}
HPLOGIN.enum_types = {}
HPLOGIN.fields = {Login_Local_Var_Table.HPLOGIN_PLATFORM_FIELD, Login_Local_Var_Table.HPLOGIN_CHANNEL_FIELD, Login_Local_Var_Table.HPLOGIN_COUNTRY_FIELD, Login_Local_Var_Table.HPLOGIN_DEVICEID_FIELD, Login_Local_Var_Table.HPLOGIN_LANG_FIELD, Login_Local_Var_Table.HPLOGIN_PHONEINFO_FIELD, Login_Local_Var_Table.HPLOGIN_VERSION_FIELD, Login_Local_Var_Table.HPLOGIN_PLAYERID_FIELD, Login_Local_Var_Table.HPLOGIN_PUID_FIELD, Login_Local_Var_Table.HPLOGIN_TOKEN_FIELD, Login_Local_Var_Table.HPLOGIN_PUSHINFO_FIELD, Login_Local_Var_Table.HPLOGIN_FLAG_FIELD}
HPLOGIN.is_extendable = false
HPLOGIN.extensions = {}
Login_Local_Var_Table.HPLOGINRET_ERRCODE_FIELD.name = "errCode"
Login_Local_Var_Table.HPLOGINRET_ERRCODE_FIELD.full_name = ".HPLoginRet.errCode"
Login_Local_Var_Table.HPLOGINRET_ERRCODE_FIELD.number = 1
Login_Local_Var_Table.HPLOGINRET_ERRCODE_FIELD.index = 0
Login_Local_Var_Table.HPLOGINRET_ERRCODE_FIELD.label = 2
Login_Local_Var_Table.HPLOGINRET_ERRCODE_FIELD.has_default_value = false
Login_Local_Var_Table.HPLOGINRET_ERRCODE_FIELD.default_value = 0
Login_Local_Var_Table.HPLOGINRET_ERRCODE_FIELD.type = 5
Login_Local_Var_Table.HPLOGINRET_ERRCODE_FIELD.cpp_type = 1

Login_Local_Var_Table.HPLOGINRET_PLAYERID_FIELD.name = "playerId"
Login_Local_Var_Table.HPLOGINRET_PLAYERID_FIELD.full_name = ".HPLoginRet.playerId"
Login_Local_Var_Table.HPLOGINRET_PLAYERID_FIELD.number = 2
Login_Local_Var_Table.HPLOGINRET_PLAYERID_FIELD.index = 1
Login_Local_Var_Table.HPLOGINRET_PLAYERID_FIELD.label = 1
Login_Local_Var_Table.HPLOGINRET_PLAYERID_FIELD.has_default_value = false
Login_Local_Var_Table.HPLOGINRET_PLAYERID_FIELD.default_value = ""
Login_Local_Var_Table.HPLOGINRET_PLAYERID_FIELD.type = 9
Login_Local_Var_Table.HPLOGINRET_PLAYERID_FIELD.cpp_type = 9

Login_Local_Var_Table.HPLOGINRET_PUID_FIELD.name = "puid"
Login_Local_Var_Table.HPLOGINRET_PUID_FIELD.full_name = ".HPLoginRet.puid"
Login_Local_Var_Table.HPLOGINRET_PUID_FIELD.number = 3
Login_Local_Var_Table.HPLOGINRET_PUID_FIELD.index = 2
Login_Local_Var_Table.HPLOGINRET_PUID_FIELD.label = 1
Login_Local_Var_Table.HPLOGINRET_PUID_FIELD.has_default_value = false
Login_Local_Var_Table.HPLOGINRET_PUID_FIELD.default_value = ""
Login_Local_Var_Table.HPLOGINRET_PUID_FIELD.type = 9
Login_Local_Var_Table.HPLOGINRET_PUID_FIELD.cpp_type = 9

Login_Local_Var_Table.HPLOGINRET_TIMESTAMP_FIELD.name = "timeStamp"
Login_Local_Var_Table.HPLOGINRET_TIMESTAMP_FIELD.full_name = ".HPLoginRet.timeStamp"
Login_Local_Var_Table.HPLOGINRET_TIMESTAMP_FIELD.number = 4
Login_Local_Var_Table.HPLOGINRET_TIMESTAMP_FIELD.index = 3
Login_Local_Var_Table.HPLOGINRET_TIMESTAMP_FIELD.label = 1
Login_Local_Var_Table.HPLOGINRET_TIMESTAMP_FIELD.has_default_value = false
Login_Local_Var_Table.HPLOGINRET_TIMESTAMP_FIELD.default_value = 0
Login_Local_Var_Table.HPLOGINRET_TIMESTAMP_FIELD.type = 5
Login_Local_Var_Table.HPLOGINRET_TIMESTAMP_FIELD.cpp_type = 1

Login_Local_Var_Table.HPLOGINRET_SERVEROPENTIME_FIELD.name = "serverOpenTime"
Login_Local_Var_Table.HPLOGINRET_SERVEROPENTIME_FIELD.full_name = ".HPLoginRet.serverOpenTime"
Login_Local_Var_Table.HPLOGINRET_SERVEROPENTIME_FIELD.number = 5
Login_Local_Var_Table.HPLOGINRET_SERVEROPENTIME_FIELD.index = 4
Login_Local_Var_Table.HPLOGINRET_SERVEROPENTIME_FIELD.label = 1
Login_Local_Var_Table.HPLOGINRET_SERVEROPENTIME_FIELD.has_default_value = false
Login_Local_Var_Table.HPLOGINRET_SERVEROPENTIME_FIELD.default_value = 0
Login_Local_Var_Table.HPLOGINRET_SERVEROPENTIME_FIELD.type = 3
Login_Local_Var_Table.HPLOGINRET_SERVEROPENTIME_FIELD.cpp_type = 2

Login_Local_Var_Table.HPLOGINRET_FLAG_FIELD.name = "flag"
Login_Local_Var_Table.HPLOGINRET_FLAG_FIELD.full_name = ".HPLoginRet.flag"
Login_Local_Var_Table.HPLOGINRET_FLAG_FIELD.number = 6
Login_Local_Var_Table.HPLOGINRET_FLAG_FIELD.index = 5
Login_Local_Var_Table.HPLOGINRET_FLAG_FIELD.label = 1
Login_Local_Var_Table.HPLOGINRET_FLAG_FIELD.has_default_value = false
Login_Local_Var_Table.HPLOGINRET_FLAG_FIELD.default_value = 0
Login_Local_Var_Table.HPLOGINRET_FLAG_FIELD.type = 5
Login_Local_Var_Table.HPLOGINRET_FLAG_FIELD.cpp_type = 1

HPLOGINRET.name = "HPLoginRet"
HPLOGINRET.full_name = ".HPLoginRet"
HPLOGINRET.nested_types = {}
HPLOGINRET.enum_types = {}
HPLOGINRET.fields = {Login_Local_Var_Table.HPLOGINRET_ERRCODE_FIELD, Login_Local_Var_Table.HPLOGINRET_PLAYERID_FIELD, Login_Local_Var_Table.HPLOGINRET_PUID_FIELD, Login_Local_Var_Table.HPLOGINRET_TIMESTAMP_FIELD, Login_Local_Var_Table.HPLOGINRET_SERVEROPENTIME_FIELD, Login_Local_Var_Table.HPLOGINRET_FLAG_FIELD}
HPLOGINRET.is_extendable = false
HPLOGINRET.extensions = {}
Login_Local_Var_Table.HPACTIVEDEVICE_DEVICEID_FIELD.name = "deviceId"
Login_Local_Var_Table.HPACTIVEDEVICE_DEVICEID_FIELD.full_name = ".HPActiveDevice.deviceId"
Login_Local_Var_Table.HPACTIVEDEVICE_DEVICEID_FIELD.number = 1
Login_Local_Var_Table.HPACTIVEDEVICE_DEVICEID_FIELD.index = 0
Login_Local_Var_Table.HPACTIVEDEVICE_DEVICEID_FIELD.label = 2
Login_Local_Var_Table.HPACTIVEDEVICE_DEVICEID_FIELD.has_default_value = false
Login_Local_Var_Table.HPACTIVEDEVICE_DEVICEID_FIELD.default_value = ""
Login_Local_Var_Table.HPACTIVEDEVICE_DEVICEID_FIELD.type = 9
Login_Local_Var_Table.HPACTIVEDEVICE_DEVICEID_FIELD.cpp_type = 9

Login_Local_Var_Table.HPACTIVEDEVICE_ACTIVETOKEN_FIELD.name = "activeToken"
Login_Local_Var_Table.HPACTIVEDEVICE_ACTIVETOKEN_FIELD.full_name = ".HPActiveDevice.activeToken"
Login_Local_Var_Table.HPACTIVEDEVICE_ACTIVETOKEN_FIELD.number = 2
Login_Local_Var_Table.HPACTIVEDEVICE_ACTIVETOKEN_FIELD.index = 1
Login_Local_Var_Table.HPACTIVEDEVICE_ACTIVETOKEN_FIELD.label = 2
Login_Local_Var_Table.HPACTIVEDEVICE_ACTIVETOKEN_FIELD.has_default_value = false
Login_Local_Var_Table.HPACTIVEDEVICE_ACTIVETOKEN_FIELD.default_value = ""
Login_Local_Var_Table.HPACTIVEDEVICE_ACTIVETOKEN_FIELD.type = 9
Login_Local_Var_Table.HPACTIVEDEVICE_ACTIVETOKEN_FIELD.cpp_type = 9

HPACTIVEDEVICE.name = "HPActiveDevice"
HPACTIVEDEVICE.full_name = ".HPActiveDevice"
HPACTIVEDEVICE.nested_types = {}
HPACTIVEDEVICE.enum_types = {}
HPACTIVEDEVICE.fields = {Login_Local_Var_Table.HPACTIVEDEVICE_DEVICEID_FIELD, Login_Local_Var_Table.HPACTIVEDEVICE_ACTIVETOKEN_FIELD}
HPACTIVEDEVICE.is_extendable = false
HPACTIVEDEVICE.extensions = {}
Login_Local_Var_Table.HPACTIVEDEVICERET_DEVICEID_FIELD.name = "deviceId"
Login_Local_Var_Table.HPACTIVEDEVICERET_DEVICEID_FIELD.full_name = ".HPActiveDeviceRet.deviceId"
Login_Local_Var_Table.HPACTIVEDEVICERET_DEVICEID_FIELD.number = 1
Login_Local_Var_Table.HPACTIVEDEVICERET_DEVICEID_FIELD.index = 0
Login_Local_Var_Table.HPACTIVEDEVICERET_DEVICEID_FIELD.label = 2
Login_Local_Var_Table.HPACTIVEDEVICERET_DEVICEID_FIELD.has_default_value = false
Login_Local_Var_Table.HPACTIVEDEVICERET_DEVICEID_FIELD.default_value = ""
Login_Local_Var_Table.HPACTIVEDEVICERET_DEVICEID_FIELD.type = 9
Login_Local_Var_Table.HPACTIVEDEVICERET_DEVICEID_FIELD.cpp_type = 9

Login_Local_Var_Table.HPACTIVEDEVICERET_CODE_FIELD.name = "code"
Login_Local_Var_Table.HPACTIVEDEVICERET_CODE_FIELD.full_name = ".HPActiveDeviceRet.code"
Login_Local_Var_Table.HPACTIVEDEVICERET_CODE_FIELD.number = 2
Login_Local_Var_Table.HPACTIVEDEVICERET_CODE_FIELD.index = 1
Login_Local_Var_Table.HPACTIVEDEVICERET_CODE_FIELD.label = 2
Login_Local_Var_Table.HPACTIVEDEVICERET_CODE_FIELD.has_default_value = false
Login_Local_Var_Table.HPACTIVEDEVICERET_CODE_FIELD.default_value = 0
Login_Local_Var_Table.HPACTIVEDEVICERET_CODE_FIELD.type = 5
Login_Local_Var_Table.HPACTIVEDEVICERET_CODE_FIELD.cpp_type = 1

HPACTIVEDEVICERET.name = "HPActiveDeviceRet"
HPACTIVEDEVICERET.full_name = ".HPActiveDeviceRet"
HPACTIVEDEVICERET.nested_types = {}
HPACTIVEDEVICERET.enum_types = {}
HPACTIVEDEVICERET.fields = {Login_Local_Var_Table.HPACTIVEDEVICERET_DEVICEID_FIELD, Login_Local_Var_Table.HPACTIVEDEVICERET_CODE_FIELD}
HPACTIVEDEVICERET.is_extendable = false
HPACTIVEDEVICERET.extensions = {}
Login_Local_Var_Table.HPASSEMBLEFINISH_PLAYERID_FIELD.name = "playerId"
Login_Local_Var_Table.HPASSEMBLEFINISH_PLAYERID_FIELD.full_name = ".HPAssembleFinish.playerId"
Login_Local_Var_Table.HPASSEMBLEFINISH_PLAYERID_FIELD.number = 1
Login_Local_Var_Table.HPASSEMBLEFINISH_PLAYERID_FIELD.index = 0
Login_Local_Var_Table.HPASSEMBLEFINISH_PLAYERID_FIELD.label = 2
Login_Local_Var_Table.HPASSEMBLEFINISH_PLAYERID_FIELD.has_default_value = false
Login_Local_Var_Table.HPASSEMBLEFINISH_PLAYERID_FIELD.default_value = ""
Login_Local_Var_Table.HPASSEMBLEFINISH_PLAYERID_FIELD.type = 9
Login_Local_Var_Table.HPASSEMBLEFINISH_PLAYERID_FIELD.cpp_type = 9

Login_Local_Var_Table.HPASSEMBLEFINISH_TOKEN_FIELD.name = "token"
Login_Local_Var_Table.HPASSEMBLEFINISH_TOKEN_FIELD.full_name = ".HPAssembleFinish.token"
Login_Local_Var_Table.HPASSEMBLEFINISH_TOKEN_FIELD.number = 2
Login_Local_Var_Table.HPASSEMBLEFINISH_TOKEN_FIELD.index = 1
Login_Local_Var_Table.HPASSEMBLEFINISH_TOKEN_FIELD.label = 1
Login_Local_Var_Table.HPASSEMBLEFINISH_TOKEN_FIELD.has_default_value = false
Login_Local_Var_Table.HPASSEMBLEFINISH_TOKEN_FIELD.default_value = ""
Login_Local_Var_Table.HPASSEMBLEFINISH_TOKEN_FIELD.type = 9
Login_Local_Var_Table.HPASSEMBLEFINISH_TOKEN_FIELD.cpp_type = 9

HPASSEMBLEFINISH.name = "HPAssembleFinish"
HPASSEMBLEFINISH.full_name = ".HPAssembleFinish"
HPASSEMBLEFINISH.nested_types = {}
HPASSEMBLEFINISH.enum_types = {}
HPASSEMBLEFINISH.fields = {Login_Local_Var_Table.HPASSEMBLEFINISH_PLAYERID_FIELD, Login_Local_Var_Table.HPASSEMBLEFINISH_TOKEN_FIELD}
HPASSEMBLEFINISH.is_extendable = false
HPASSEMBLEFINISH.extensions = {}
Login_Local_Var_Table.HPPLAYERKICKOUT_REASON_FIELD.name = "reason"
Login_Local_Var_Table.HPPLAYERKICKOUT_REASON_FIELD.full_name = ".HPPlayerKickout.reason"
Login_Local_Var_Table.HPPLAYERKICKOUT_REASON_FIELD.number = 1
Login_Local_Var_Table.HPPLAYERKICKOUT_REASON_FIELD.index = 0
Login_Local_Var_Table.HPPLAYERKICKOUT_REASON_FIELD.label = 2
Login_Local_Var_Table.HPPLAYERKICKOUT_REASON_FIELD.has_default_value = false
Login_Local_Var_Table.HPPLAYERKICKOUT_REASON_FIELD.default_value = 0
Login_Local_Var_Table.HPPLAYERKICKOUT_REASON_FIELD.type = 5
Login_Local_Var_Table.HPPLAYERKICKOUT_REASON_FIELD.cpp_type = 1

HPPLAYERKICKOUT.name = "HPPlayerKickout"
HPPLAYERKICKOUT.full_name = ".HPPlayerKickout"
HPPLAYERKICKOUT.nested_types = {}
HPPLAYERKICKOUT.enum_types = {}
HPPLAYERKICKOUT.fields = {Login_Local_Var_Table.HPPLAYERKICKOUT_REASON_FIELD}
HPPLAYERKICKOUT.is_extendable = false
HPPLAYERKICKOUT.extensions = {}

HPActiveDevice = protobuf.Message(HPACTIVEDEVICE)
HPActiveDeviceRet = protobuf.Message(HPACTIVEDEVICERET)
HPAssembleFinish = protobuf.Message(HPASSEMBLEFINISH)
HPLogin = protobuf.Message(HPLOGIN)
HPLoginRet = protobuf.Message(HPLOGINRET)
HPPlayerKickout = protobuf.Message(HPPLAYERKICKOUT)

