-- Generated By protoc-gen-lua Do not Edit


local Mission_Local_Var_Table = {}

local protobuf = require "protobuf"
module('Mission_pb')


MISSIONPB = protobuf.Descriptor();
Mission_Local_Var_Table.MISSIONPB_MISSIONID_FIELD = protobuf.FieldDescriptor();
Mission_Local_Var_Table.MISSIONPB_CFGID_FIELD = protobuf.FieldDescriptor();
Mission_Local_Var_Table.MISSIONPB_STATE_FIELD = protobuf.FieldDescriptor();
Mission_Local_Var_Table.MISSIONPB_NUM_FIELD = protobuf.FieldDescriptor();
MISSIONLISTREQ = protobuf.Descriptor();
MISSIONLISTRES = protobuf.Descriptor();
Mission_Local_Var_Table.MISSIONLISTRES_LIST_FIELD = protobuf.FieldDescriptor();
MISSIONBONUSREQ = protobuf.Descriptor();
Mission_Local_Var_Table.MISSIONBONUSREQ_MISSIONID_FIELD = protobuf.FieldDescriptor();
MISSIONBONUSRES = protobuf.Descriptor();
Mission_Local_Var_Table.MISSIONBONUSRES_REMOVEMISSIONID_FIELD = protobuf.FieldDescriptor();
Mission_Local_Var_Table.MISSIONBONUSRES_ADDMISSION_FIELD = protobuf.FieldDescriptor();
MISSIONREFRESHRES = protobuf.Descriptor();
Mission_Local_Var_Table.MISSIONREFRESHRES_REFRESHMISSION_FIELD = protobuf.FieldDescriptor();

Mission_Local_Var_Table.MISSIONPB_MISSIONID_FIELD.name = "missionId"
Mission_Local_Var_Table.MISSIONPB_MISSIONID_FIELD.full_name = ".MissionPB.missionId"
Mission_Local_Var_Table.MISSIONPB_MISSIONID_FIELD.number = 1
Mission_Local_Var_Table.MISSIONPB_MISSIONID_FIELD.index = 0
Mission_Local_Var_Table.MISSIONPB_MISSIONID_FIELD.label = 2
Mission_Local_Var_Table.MISSIONPB_MISSIONID_FIELD.has_default_value = false
Mission_Local_Var_Table.MISSIONPB_MISSIONID_FIELD.default_value = ""
Mission_Local_Var_Table.MISSIONPB_MISSIONID_FIELD.type = 9
Mission_Local_Var_Table.MISSIONPB_MISSIONID_FIELD.cpp_type = 9

Mission_Local_Var_Table.MISSIONPB_CFGID_FIELD.name = "cfgId"
Mission_Local_Var_Table.MISSIONPB_CFGID_FIELD.full_name = ".MissionPB.cfgId"
Mission_Local_Var_Table.MISSIONPB_CFGID_FIELD.number = 2
Mission_Local_Var_Table.MISSIONPB_CFGID_FIELD.index = 1
Mission_Local_Var_Table.MISSIONPB_CFGID_FIELD.label = 2
Mission_Local_Var_Table.MISSIONPB_CFGID_FIELD.has_default_value = false
Mission_Local_Var_Table.MISSIONPB_CFGID_FIELD.default_value = 0
Mission_Local_Var_Table.MISSIONPB_CFGID_FIELD.type = 5
Mission_Local_Var_Table.MISSIONPB_CFGID_FIELD.cpp_type = 1

Mission_Local_Var_Table.MISSIONPB_STATE_FIELD.name = "state"
Mission_Local_Var_Table.MISSIONPB_STATE_FIELD.full_name = ".MissionPB.state"
Mission_Local_Var_Table.MISSIONPB_STATE_FIELD.number = 3
Mission_Local_Var_Table.MISSIONPB_STATE_FIELD.index = 2
Mission_Local_Var_Table.MISSIONPB_STATE_FIELD.label = 2
Mission_Local_Var_Table.MISSIONPB_STATE_FIELD.has_default_value = false
Mission_Local_Var_Table.MISSIONPB_STATE_FIELD.default_value = 0
Mission_Local_Var_Table.MISSIONPB_STATE_FIELD.type = 5
Mission_Local_Var_Table.MISSIONPB_STATE_FIELD.cpp_type = 1

Mission_Local_Var_Table.MISSIONPB_NUM_FIELD.name = "num"
Mission_Local_Var_Table.MISSIONPB_NUM_FIELD.full_name = ".MissionPB.num"
Mission_Local_Var_Table.MISSIONPB_NUM_FIELD.number = 4
Mission_Local_Var_Table.MISSIONPB_NUM_FIELD.index = 3
Mission_Local_Var_Table.MISSIONPB_NUM_FIELD.label = 2
Mission_Local_Var_Table.MISSIONPB_NUM_FIELD.has_default_value = false
Mission_Local_Var_Table.MISSIONPB_NUM_FIELD.default_value = 0
Mission_Local_Var_Table.MISSIONPB_NUM_FIELD.type = 5
Mission_Local_Var_Table.MISSIONPB_NUM_FIELD.cpp_type = 1

MISSIONPB.name = "MissionPB"
MISSIONPB.full_name = ".MissionPB"
MISSIONPB.nested_types = {}
MISSIONPB.enum_types = {}
MISSIONPB.fields = {Mission_Local_Var_Table.MISSIONPB_MISSIONID_FIELD, Mission_Local_Var_Table.MISSIONPB_CFGID_FIELD, Mission_Local_Var_Table.MISSIONPB_STATE_FIELD, Mission_Local_Var_Table.MISSIONPB_NUM_FIELD}
MISSIONPB.is_extendable = false
MISSIONPB.extensions = {}
MISSIONLISTREQ.name = "MissionListReq"
MISSIONLISTREQ.full_name = ".MissionListReq"
MISSIONLISTREQ.nested_types = {}
MISSIONLISTREQ.enum_types = {}
MISSIONLISTREQ.fields = {}
MISSIONLISTREQ.is_extendable = false
MISSIONLISTREQ.extensions = {}
Mission_Local_Var_Table.MISSIONLISTRES_LIST_FIELD.name = "list"
Mission_Local_Var_Table.MISSIONLISTRES_LIST_FIELD.full_name = ".MissionListRes.list"
Mission_Local_Var_Table.MISSIONLISTRES_LIST_FIELD.number = 1
Mission_Local_Var_Table.MISSIONLISTRES_LIST_FIELD.index = 0
Mission_Local_Var_Table.MISSIONLISTRES_LIST_FIELD.label = 3
Mission_Local_Var_Table.MISSIONLISTRES_LIST_FIELD.has_default_value = false
Mission_Local_Var_Table.MISSIONLISTRES_LIST_FIELD.default_value = {}
Mission_Local_Var_Table.MISSIONLISTRES_LIST_FIELD.message_type = MISSIONPB
Mission_Local_Var_Table.MISSIONLISTRES_LIST_FIELD.type = 11
Mission_Local_Var_Table.MISSIONLISTRES_LIST_FIELD.cpp_type = 10

MISSIONLISTRES.name = "MissionListRes"
MISSIONLISTRES.full_name = ".MissionListRes"
MISSIONLISTRES.nested_types = {}
MISSIONLISTRES.enum_types = {}
MISSIONLISTRES.fields = {Mission_Local_Var_Table.MISSIONLISTRES_LIST_FIELD}
MISSIONLISTRES.is_extendable = false
MISSIONLISTRES.extensions = {}
Mission_Local_Var_Table.MISSIONBONUSREQ_MISSIONID_FIELD.name = "missionId"
Mission_Local_Var_Table.MISSIONBONUSREQ_MISSIONID_FIELD.full_name = ".MissionBonusReq.missionId"
Mission_Local_Var_Table.MISSIONBONUSREQ_MISSIONID_FIELD.number = 1
Mission_Local_Var_Table.MISSIONBONUSREQ_MISSIONID_FIELD.index = 0
Mission_Local_Var_Table.MISSIONBONUSREQ_MISSIONID_FIELD.label = 2
Mission_Local_Var_Table.MISSIONBONUSREQ_MISSIONID_FIELD.has_default_value = false
Mission_Local_Var_Table.MISSIONBONUSREQ_MISSIONID_FIELD.default_value = ""
Mission_Local_Var_Table.MISSIONBONUSREQ_MISSIONID_FIELD.type = 9
Mission_Local_Var_Table.MISSIONBONUSREQ_MISSIONID_FIELD.cpp_type = 9

MISSIONBONUSREQ.name = "MissionBonusReq"
MISSIONBONUSREQ.full_name = ".MissionBonusReq"
MISSIONBONUSREQ.nested_types = {}
MISSIONBONUSREQ.enum_types = {}
MISSIONBONUSREQ.fields = {Mission_Local_Var_Table.MISSIONBONUSREQ_MISSIONID_FIELD}
MISSIONBONUSREQ.is_extendable = false
MISSIONBONUSREQ.extensions = {}
Mission_Local_Var_Table.MISSIONBONUSRES_REMOVEMISSIONID_FIELD.name = "removeMissionId"
Mission_Local_Var_Table.MISSIONBONUSRES_REMOVEMISSIONID_FIELD.full_name = ".MissionBonusRes.removeMissionId"
Mission_Local_Var_Table.MISSIONBONUSRES_REMOVEMISSIONID_FIELD.number = 1
Mission_Local_Var_Table.MISSIONBONUSRES_REMOVEMISSIONID_FIELD.index = 0
Mission_Local_Var_Table.MISSIONBONUSRES_REMOVEMISSIONID_FIELD.label = 2
Mission_Local_Var_Table.MISSIONBONUSRES_REMOVEMISSIONID_FIELD.has_default_value = false
Mission_Local_Var_Table.MISSIONBONUSRES_REMOVEMISSIONID_FIELD.default_value = ""
Mission_Local_Var_Table.MISSIONBONUSRES_REMOVEMISSIONID_FIELD.type = 9
Mission_Local_Var_Table.MISSIONBONUSRES_REMOVEMISSIONID_FIELD.cpp_type = 9

Mission_Local_Var_Table.MISSIONBONUSRES_ADDMISSION_FIELD.name = "addMission"
Mission_Local_Var_Table.MISSIONBONUSRES_ADDMISSION_FIELD.full_name = ".MissionBonusRes.addMission"
Mission_Local_Var_Table.MISSIONBONUSRES_ADDMISSION_FIELD.number = 2
Mission_Local_Var_Table.MISSIONBONUSRES_ADDMISSION_FIELD.index = 1
Mission_Local_Var_Table.MISSIONBONUSRES_ADDMISSION_FIELD.label = 3
Mission_Local_Var_Table.MISSIONBONUSRES_ADDMISSION_FIELD.has_default_value = false
Mission_Local_Var_Table.MISSIONBONUSRES_ADDMISSION_FIELD.default_value = {}
Mission_Local_Var_Table.MISSIONBONUSRES_ADDMISSION_FIELD.message_type = MISSIONPB
Mission_Local_Var_Table.MISSIONBONUSRES_ADDMISSION_FIELD.type = 11
Mission_Local_Var_Table.MISSIONBONUSRES_ADDMISSION_FIELD.cpp_type = 10

MISSIONBONUSRES.name = "MissionBonusRes"
MISSIONBONUSRES.full_name = ".MissionBonusRes"
MISSIONBONUSRES.nested_types = {}
MISSIONBONUSRES.enum_types = {}
MISSIONBONUSRES.fields = {Mission_Local_Var_Table.MISSIONBONUSRES_REMOVEMISSIONID_FIELD, Mission_Local_Var_Table.MISSIONBONUSRES_ADDMISSION_FIELD}
MISSIONBONUSRES.is_extendable = false
MISSIONBONUSRES.extensions = {}
Mission_Local_Var_Table.MISSIONREFRESHRES_REFRESHMISSION_FIELD.name = "refreshMission"
Mission_Local_Var_Table.MISSIONREFRESHRES_REFRESHMISSION_FIELD.full_name = ".MissionRefreshRes.refreshMission"
Mission_Local_Var_Table.MISSIONREFRESHRES_REFRESHMISSION_FIELD.number = 1
Mission_Local_Var_Table.MISSIONREFRESHRES_REFRESHMISSION_FIELD.index = 0
Mission_Local_Var_Table.MISSIONREFRESHRES_REFRESHMISSION_FIELD.label = 3
Mission_Local_Var_Table.MISSIONREFRESHRES_REFRESHMISSION_FIELD.has_default_value = false
Mission_Local_Var_Table.MISSIONREFRESHRES_REFRESHMISSION_FIELD.default_value = {}
Mission_Local_Var_Table.MISSIONREFRESHRES_REFRESHMISSION_FIELD.message_type = MISSIONPB
Mission_Local_Var_Table.MISSIONREFRESHRES_REFRESHMISSION_FIELD.type = 11
Mission_Local_Var_Table.MISSIONREFRESHRES_REFRESHMISSION_FIELD.cpp_type = 10

MISSIONREFRESHRES.name = "MissionRefreshRes"
MISSIONREFRESHRES.full_name = ".MissionRefreshRes"
MISSIONREFRESHRES.nested_types = {}
MISSIONREFRESHRES.enum_types = {}
MISSIONREFRESHRES.fields = {Mission_Local_Var_Table.MISSIONREFRESHRES_REFRESHMISSION_FIELD}
MISSIONREFRESHRES.is_extendable = false
MISSIONREFRESHRES.extensions = {}

MissionBonusReq = protobuf.Message(MISSIONBONUSREQ)
MissionBonusRes = protobuf.Message(MISSIONBONUSRES)
MissionListReq = protobuf.Message(MISSIONLISTREQ)
MissionListRes = protobuf.Message(MISSIONLISTRES)
MissionPB = protobuf.Message(MISSIONPB)
MissionRefreshRes = protobuf.Message(MISSIONREFRESHRES)

