-- Generated By protoc-gen-lua Do not Edit


local Queue_Local_Var_Table = {}

local protobuf = require "protobuf"
local Const_pb = require("Const_pb")
module('Queue_pb')


QUEUEPB = protobuf.Descriptor();
Queue_Local_Var_Table.QUEUEPB_ID_FIELD = protobuf.FieldDescriptor();
Queue_Local_Var_Table.QUEUEPB_QUEUETYPE_FIELD = protobuf.FieldDescriptor();
Queue_Local_Var_Table.QUEUEPB_ITEMID_FIELD = protobuf.FieldDescriptor();
Queue_Local_Var_Table.QUEUEPB_STARTTIME_FIELD = protobuf.FieldDescriptor();
Queue_Local_Var_Table.QUEUEPB_ENDTIME_FIELD = protobuf.FieldDescriptor();
Queue_Local_Var_Table.QUEUEPB_INFO_FIELD = protobuf.FieldDescriptor();
Queue_Local_Var_Table.QUEUEPB_STATUS_FIELD = protobuf.FieldDescriptor();
Queue_Local_Var_Table.QUEUEPB_HELPTIMES_FIELD = protobuf.FieldDescriptor();
Queue_Local_Var_Table.QUEUEPB_TOTALQUEUETIME_FIELD = protobuf.FieldDescriptor();
Queue_Local_Var_Table.QUEUEPB_TOTALREDUCETIME_FIELD = protobuf.FieldDescriptor();
HPQUEUEINFOSYNC = protobuf.Descriptor();
Queue_Local_Var_Table.HPQUEUEINFOSYNC_QUEUES_FIELD = protobuf.FieldDescriptor();
QUEUECANCELREQ = protobuf.Descriptor();
Queue_Local_Var_Table.QUEUECANCELREQ_ID_FIELD = protobuf.FieldDescriptor();
QUEUESPEEDUPREQ = protobuf.Descriptor();
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ID_FIELD = protobuf.FieldDescriptor();
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ISGOLD_FIELD = protobuf.FieldDescriptor();
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ITEMUUID_FIELD = protobuf.FieldDescriptor();
Queue_Local_Var_Table.QUEUESPEEDUPREQ_COUNT_FIELD = protobuf.FieldDescriptor();
QUEUEFINISHFREEREQ = protobuf.Descriptor();
Queue_Local_Var_Table.QUEUEFINISHFREEREQ_ID_FIELD = protobuf.FieldDescriptor();
QUEUEPBSIMPLE = protobuf.Descriptor();
Queue_Local_Var_Table.QUEUEPBSIMPLE_QUEUETYPE_FIELD = protobuf.FieldDescriptor();
Queue_Local_Var_Table.QUEUEPBSIMPLE_ID_FIELD = protobuf.FieldDescriptor();

Queue_Local_Var_Table.QUEUEPB_ID_FIELD.name = "id"
Queue_Local_Var_Table.QUEUEPB_ID_FIELD.full_name = ".QueuePB.id"
Queue_Local_Var_Table.QUEUEPB_ID_FIELD.number = 1
Queue_Local_Var_Table.QUEUEPB_ID_FIELD.index = 0
Queue_Local_Var_Table.QUEUEPB_ID_FIELD.label = 2
Queue_Local_Var_Table.QUEUEPB_ID_FIELD.has_default_value = false
Queue_Local_Var_Table.QUEUEPB_ID_FIELD.default_value = ""
Queue_Local_Var_Table.QUEUEPB_ID_FIELD.type = 9
Queue_Local_Var_Table.QUEUEPB_ID_FIELD.cpp_type = 9

Queue_Local_Var_Table.QUEUEPB_QUEUETYPE_FIELD.name = "queueType"
Queue_Local_Var_Table.QUEUEPB_QUEUETYPE_FIELD.full_name = ".QueuePB.queueType"
Queue_Local_Var_Table.QUEUEPB_QUEUETYPE_FIELD.number = 2
Queue_Local_Var_Table.QUEUEPB_QUEUETYPE_FIELD.index = 1
Queue_Local_Var_Table.QUEUEPB_QUEUETYPE_FIELD.label = 2
Queue_Local_Var_Table.QUEUEPB_QUEUETYPE_FIELD.has_default_value = false
Queue_Local_Var_Table.QUEUEPB_QUEUETYPE_FIELD.default_value = nil
Queue_Local_Var_Table.QUEUEPB_QUEUETYPE_FIELD.enum_type = Const_pb.QUEUETYPE
Queue_Local_Var_Table.QUEUEPB_QUEUETYPE_FIELD.type = 14
Queue_Local_Var_Table.QUEUEPB_QUEUETYPE_FIELD.cpp_type = 8

Queue_Local_Var_Table.QUEUEPB_ITEMID_FIELD.name = "itemId"
Queue_Local_Var_Table.QUEUEPB_ITEMID_FIELD.full_name = ".QueuePB.itemId"
Queue_Local_Var_Table.QUEUEPB_ITEMID_FIELD.number = 3
Queue_Local_Var_Table.QUEUEPB_ITEMID_FIELD.index = 2
Queue_Local_Var_Table.QUEUEPB_ITEMID_FIELD.label = 2
Queue_Local_Var_Table.QUEUEPB_ITEMID_FIELD.has_default_value = false
Queue_Local_Var_Table.QUEUEPB_ITEMID_FIELD.default_value = ""
Queue_Local_Var_Table.QUEUEPB_ITEMID_FIELD.type = 9
Queue_Local_Var_Table.QUEUEPB_ITEMID_FIELD.cpp_type = 9

Queue_Local_Var_Table.QUEUEPB_STARTTIME_FIELD.name = "startTime"
Queue_Local_Var_Table.QUEUEPB_STARTTIME_FIELD.full_name = ".QueuePB.startTime"
Queue_Local_Var_Table.QUEUEPB_STARTTIME_FIELD.number = 4
Queue_Local_Var_Table.QUEUEPB_STARTTIME_FIELD.index = 3
Queue_Local_Var_Table.QUEUEPB_STARTTIME_FIELD.label = 2
Queue_Local_Var_Table.QUEUEPB_STARTTIME_FIELD.has_default_value = false
Queue_Local_Var_Table.QUEUEPB_STARTTIME_FIELD.default_value = 0
Queue_Local_Var_Table.QUEUEPB_STARTTIME_FIELD.type = 3
Queue_Local_Var_Table.QUEUEPB_STARTTIME_FIELD.cpp_type = 2

Queue_Local_Var_Table.QUEUEPB_ENDTIME_FIELD.name = "endTime"
Queue_Local_Var_Table.QUEUEPB_ENDTIME_FIELD.full_name = ".QueuePB.endTime"
Queue_Local_Var_Table.QUEUEPB_ENDTIME_FIELD.number = 5
Queue_Local_Var_Table.QUEUEPB_ENDTIME_FIELD.index = 4
Queue_Local_Var_Table.QUEUEPB_ENDTIME_FIELD.label = 2
Queue_Local_Var_Table.QUEUEPB_ENDTIME_FIELD.has_default_value = false
Queue_Local_Var_Table.QUEUEPB_ENDTIME_FIELD.default_value = 0
Queue_Local_Var_Table.QUEUEPB_ENDTIME_FIELD.type = 3
Queue_Local_Var_Table.QUEUEPB_ENDTIME_FIELD.cpp_type = 2

Queue_Local_Var_Table.QUEUEPB_INFO_FIELD.name = "info"
Queue_Local_Var_Table.QUEUEPB_INFO_FIELD.full_name = ".QueuePB.info"
Queue_Local_Var_Table.QUEUEPB_INFO_FIELD.number = 6
Queue_Local_Var_Table.QUEUEPB_INFO_FIELD.index = 5
Queue_Local_Var_Table.QUEUEPB_INFO_FIELD.label = 1
Queue_Local_Var_Table.QUEUEPB_INFO_FIELD.has_default_value = false
Queue_Local_Var_Table.QUEUEPB_INFO_FIELD.default_value = ""
Queue_Local_Var_Table.QUEUEPB_INFO_FIELD.type = 9
Queue_Local_Var_Table.QUEUEPB_INFO_FIELD.cpp_type = 9

Queue_Local_Var_Table.QUEUEPB_STATUS_FIELD.name = "status"
Queue_Local_Var_Table.QUEUEPB_STATUS_FIELD.full_name = ".QueuePB.status"
Queue_Local_Var_Table.QUEUEPB_STATUS_FIELD.number = 7
Queue_Local_Var_Table.QUEUEPB_STATUS_FIELD.index = 6
Queue_Local_Var_Table.QUEUEPB_STATUS_FIELD.label = 1
Queue_Local_Var_Table.QUEUEPB_STATUS_FIELD.has_default_value = false
Queue_Local_Var_Table.QUEUEPB_STATUS_FIELD.default_value = nil
Queue_Local_Var_Table.QUEUEPB_STATUS_FIELD.enum_type = Const_pb.QUEUESTATUS
Queue_Local_Var_Table.QUEUEPB_STATUS_FIELD.type = 14
Queue_Local_Var_Table.QUEUEPB_STATUS_FIELD.cpp_type = 8

Queue_Local_Var_Table.QUEUEPB_HELPTIMES_FIELD.name = "helpTimes"
Queue_Local_Var_Table.QUEUEPB_HELPTIMES_FIELD.full_name = ".QueuePB.helpTimes"
Queue_Local_Var_Table.QUEUEPB_HELPTIMES_FIELD.number = 8
Queue_Local_Var_Table.QUEUEPB_HELPTIMES_FIELD.index = 7
Queue_Local_Var_Table.QUEUEPB_HELPTIMES_FIELD.label = 1
Queue_Local_Var_Table.QUEUEPB_HELPTIMES_FIELD.has_default_value = false
Queue_Local_Var_Table.QUEUEPB_HELPTIMES_FIELD.default_value = 0
Queue_Local_Var_Table.QUEUEPB_HELPTIMES_FIELD.type = 5
Queue_Local_Var_Table.QUEUEPB_HELPTIMES_FIELD.cpp_type = 1

Queue_Local_Var_Table.QUEUEPB_TOTALQUEUETIME_FIELD.name = "totalQueueTime"
Queue_Local_Var_Table.QUEUEPB_TOTALQUEUETIME_FIELD.full_name = ".QueuePB.totalQueueTime"
Queue_Local_Var_Table.QUEUEPB_TOTALQUEUETIME_FIELD.number = 9
Queue_Local_Var_Table.QUEUEPB_TOTALQUEUETIME_FIELD.index = 8
Queue_Local_Var_Table.QUEUEPB_TOTALQUEUETIME_FIELD.label = 2
Queue_Local_Var_Table.QUEUEPB_TOTALQUEUETIME_FIELD.has_default_value = false
Queue_Local_Var_Table.QUEUEPB_TOTALQUEUETIME_FIELD.default_value = 0
Queue_Local_Var_Table.QUEUEPB_TOTALQUEUETIME_FIELD.type = 3
Queue_Local_Var_Table.QUEUEPB_TOTALQUEUETIME_FIELD.cpp_type = 2

Queue_Local_Var_Table.QUEUEPB_TOTALREDUCETIME_FIELD.name = "totalReduceTime"
Queue_Local_Var_Table.QUEUEPB_TOTALREDUCETIME_FIELD.full_name = ".QueuePB.totalReduceTime"
Queue_Local_Var_Table.QUEUEPB_TOTALREDUCETIME_FIELD.number = 10
Queue_Local_Var_Table.QUEUEPB_TOTALREDUCETIME_FIELD.index = 9
Queue_Local_Var_Table.QUEUEPB_TOTALREDUCETIME_FIELD.label = 2
Queue_Local_Var_Table.QUEUEPB_TOTALREDUCETIME_FIELD.has_default_value = false
Queue_Local_Var_Table.QUEUEPB_TOTALREDUCETIME_FIELD.default_value = 0
Queue_Local_Var_Table.QUEUEPB_TOTALREDUCETIME_FIELD.type = 3
Queue_Local_Var_Table.QUEUEPB_TOTALREDUCETIME_FIELD.cpp_type = 2

QUEUEPB.name = "QueuePB"
QUEUEPB.full_name = ".QueuePB"
QUEUEPB.nested_types = {}
QUEUEPB.enum_types = {}
QUEUEPB.fields = {Queue_Local_Var_Table.QUEUEPB_ID_FIELD, Queue_Local_Var_Table.QUEUEPB_QUEUETYPE_FIELD, Queue_Local_Var_Table.QUEUEPB_ITEMID_FIELD, Queue_Local_Var_Table.QUEUEPB_STARTTIME_FIELD, Queue_Local_Var_Table.QUEUEPB_ENDTIME_FIELD, Queue_Local_Var_Table.QUEUEPB_INFO_FIELD, Queue_Local_Var_Table.QUEUEPB_STATUS_FIELD, Queue_Local_Var_Table.QUEUEPB_HELPTIMES_FIELD, Queue_Local_Var_Table.QUEUEPB_TOTALQUEUETIME_FIELD, Queue_Local_Var_Table.QUEUEPB_TOTALREDUCETIME_FIELD}
QUEUEPB.is_extendable = false
QUEUEPB.extensions = {}
Queue_Local_Var_Table.HPQUEUEINFOSYNC_QUEUES_FIELD.name = "queues"
Queue_Local_Var_Table.HPQUEUEINFOSYNC_QUEUES_FIELD.full_name = ".HPQueueInfoSync.queues"
Queue_Local_Var_Table.HPQUEUEINFOSYNC_QUEUES_FIELD.number = 1
Queue_Local_Var_Table.HPQUEUEINFOSYNC_QUEUES_FIELD.index = 0
Queue_Local_Var_Table.HPQUEUEINFOSYNC_QUEUES_FIELD.label = 3
Queue_Local_Var_Table.HPQUEUEINFOSYNC_QUEUES_FIELD.has_default_value = false
Queue_Local_Var_Table.HPQUEUEINFOSYNC_QUEUES_FIELD.default_value = {}
Queue_Local_Var_Table.HPQUEUEINFOSYNC_QUEUES_FIELD.message_type = QUEUEPB
Queue_Local_Var_Table.HPQUEUEINFOSYNC_QUEUES_FIELD.type = 11
Queue_Local_Var_Table.HPQUEUEINFOSYNC_QUEUES_FIELD.cpp_type = 10

HPQUEUEINFOSYNC.name = "HPQueueInfoSync"
HPQUEUEINFOSYNC.full_name = ".HPQueueInfoSync"
HPQUEUEINFOSYNC.nested_types = {}
HPQUEUEINFOSYNC.enum_types = {}
HPQUEUEINFOSYNC.fields = {Queue_Local_Var_Table.HPQUEUEINFOSYNC_QUEUES_FIELD}
HPQUEUEINFOSYNC.is_extendable = false
HPQUEUEINFOSYNC.extensions = {}
Queue_Local_Var_Table.QUEUECANCELREQ_ID_FIELD.name = "id"
Queue_Local_Var_Table.QUEUECANCELREQ_ID_FIELD.full_name = ".QueueCancelReq.id"
Queue_Local_Var_Table.QUEUECANCELREQ_ID_FIELD.number = 1
Queue_Local_Var_Table.QUEUECANCELREQ_ID_FIELD.index = 0
Queue_Local_Var_Table.QUEUECANCELREQ_ID_FIELD.label = 2
Queue_Local_Var_Table.QUEUECANCELREQ_ID_FIELD.has_default_value = false
Queue_Local_Var_Table.QUEUECANCELREQ_ID_FIELD.default_value = ""
Queue_Local_Var_Table.QUEUECANCELREQ_ID_FIELD.type = 9
Queue_Local_Var_Table.QUEUECANCELREQ_ID_FIELD.cpp_type = 9

QUEUECANCELREQ.name = "QueueCancelReq"
QUEUECANCELREQ.full_name = ".QueueCancelReq"
QUEUECANCELREQ.nested_types = {}
QUEUECANCELREQ.enum_types = {}
QUEUECANCELREQ.fields = {Queue_Local_Var_Table.QUEUECANCELREQ_ID_FIELD}
QUEUECANCELREQ.is_extendable = false
QUEUECANCELREQ.extensions = {}
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ID_FIELD.name = "id"
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ID_FIELD.full_name = ".QueueSpeedUpReq.id"
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ID_FIELD.number = 1
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ID_FIELD.index = 0
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ID_FIELD.label = 2
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ID_FIELD.has_default_value = false
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ID_FIELD.default_value = ""
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ID_FIELD.type = 9
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ID_FIELD.cpp_type = 9

Queue_Local_Var_Table.QUEUESPEEDUPREQ_ISGOLD_FIELD.name = "isGold"
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ISGOLD_FIELD.full_name = ".QueueSpeedUpReq.isGold"
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ISGOLD_FIELD.number = 2
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ISGOLD_FIELD.index = 1
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ISGOLD_FIELD.label = 2
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ISGOLD_FIELD.has_default_value = false
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ISGOLD_FIELD.default_value = false
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ISGOLD_FIELD.type = 8
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ISGOLD_FIELD.cpp_type = 7

Queue_Local_Var_Table.QUEUESPEEDUPREQ_ITEMUUID_FIELD.name = "itemUUid"
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ITEMUUID_FIELD.full_name = ".QueueSpeedUpReq.itemUUid"
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ITEMUUID_FIELD.number = 3
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ITEMUUID_FIELD.index = 2
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ITEMUUID_FIELD.label = 1
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ITEMUUID_FIELD.has_default_value = false
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ITEMUUID_FIELD.default_value = ""
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ITEMUUID_FIELD.type = 9
Queue_Local_Var_Table.QUEUESPEEDUPREQ_ITEMUUID_FIELD.cpp_type = 9

Queue_Local_Var_Table.QUEUESPEEDUPREQ_COUNT_FIELD.name = "count"
Queue_Local_Var_Table.QUEUESPEEDUPREQ_COUNT_FIELD.full_name = ".QueueSpeedUpReq.count"
Queue_Local_Var_Table.QUEUESPEEDUPREQ_COUNT_FIELD.number = 4
Queue_Local_Var_Table.QUEUESPEEDUPREQ_COUNT_FIELD.index = 3
Queue_Local_Var_Table.QUEUESPEEDUPREQ_COUNT_FIELD.label = 1
Queue_Local_Var_Table.QUEUESPEEDUPREQ_COUNT_FIELD.has_default_value = false
Queue_Local_Var_Table.QUEUESPEEDUPREQ_COUNT_FIELD.default_value = 0
Queue_Local_Var_Table.QUEUESPEEDUPREQ_COUNT_FIELD.type = 5
Queue_Local_Var_Table.QUEUESPEEDUPREQ_COUNT_FIELD.cpp_type = 1

QUEUESPEEDUPREQ.name = "QueueSpeedUpReq"
QUEUESPEEDUPREQ.full_name = ".QueueSpeedUpReq"
QUEUESPEEDUPREQ.nested_types = {}
QUEUESPEEDUPREQ.enum_types = {}
QUEUESPEEDUPREQ.fields = {Queue_Local_Var_Table.QUEUESPEEDUPREQ_ID_FIELD, Queue_Local_Var_Table.QUEUESPEEDUPREQ_ISGOLD_FIELD, Queue_Local_Var_Table.QUEUESPEEDUPREQ_ITEMUUID_FIELD, Queue_Local_Var_Table.QUEUESPEEDUPREQ_COUNT_FIELD}
QUEUESPEEDUPREQ.is_extendable = false
QUEUESPEEDUPREQ.extensions = {}
Queue_Local_Var_Table.QUEUEFINISHFREEREQ_ID_FIELD.name = "id"
Queue_Local_Var_Table.QUEUEFINISHFREEREQ_ID_FIELD.full_name = ".QueueFinishFreeReq.id"
Queue_Local_Var_Table.QUEUEFINISHFREEREQ_ID_FIELD.number = 1
Queue_Local_Var_Table.QUEUEFINISHFREEREQ_ID_FIELD.index = 0
Queue_Local_Var_Table.QUEUEFINISHFREEREQ_ID_FIELD.label = 2
Queue_Local_Var_Table.QUEUEFINISHFREEREQ_ID_FIELD.has_default_value = false
Queue_Local_Var_Table.QUEUEFINISHFREEREQ_ID_FIELD.default_value = ""
Queue_Local_Var_Table.QUEUEFINISHFREEREQ_ID_FIELD.type = 9
Queue_Local_Var_Table.QUEUEFINISHFREEREQ_ID_FIELD.cpp_type = 9

QUEUEFINISHFREEREQ.name = "QueueFinishFreeReq"
QUEUEFINISHFREEREQ.full_name = ".QueueFinishFreeReq"
QUEUEFINISHFREEREQ.nested_types = {}
QUEUEFINISHFREEREQ.enum_types = {}
QUEUEFINISHFREEREQ.fields = {Queue_Local_Var_Table.QUEUEFINISHFREEREQ_ID_FIELD}
QUEUEFINISHFREEREQ.is_extendable = false
QUEUEFINISHFREEREQ.extensions = {}
Queue_Local_Var_Table.QUEUEPBSIMPLE_QUEUETYPE_FIELD.name = "queueType"
Queue_Local_Var_Table.QUEUEPBSIMPLE_QUEUETYPE_FIELD.full_name = ".QueuePBSimple.queueType"
Queue_Local_Var_Table.QUEUEPBSIMPLE_QUEUETYPE_FIELD.number = 1
Queue_Local_Var_Table.QUEUEPBSIMPLE_QUEUETYPE_FIELD.index = 0
Queue_Local_Var_Table.QUEUEPBSIMPLE_QUEUETYPE_FIELD.label = 2
Queue_Local_Var_Table.QUEUEPBSIMPLE_QUEUETYPE_FIELD.has_default_value = false
Queue_Local_Var_Table.QUEUEPBSIMPLE_QUEUETYPE_FIELD.default_value = nil
Queue_Local_Var_Table.QUEUEPBSIMPLE_QUEUETYPE_FIELD.enum_type = Const_pb.QUEUETYPE
Queue_Local_Var_Table.QUEUEPBSIMPLE_QUEUETYPE_FIELD.type = 14
Queue_Local_Var_Table.QUEUEPBSIMPLE_QUEUETYPE_FIELD.cpp_type = 8

Queue_Local_Var_Table.QUEUEPBSIMPLE_ID_FIELD.name = "id"
Queue_Local_Var_Table.QUEUEPBSIMPLE_ID_FIELD.full_name = ".QueuePBSimple.id"
Queue_Local_Var_Table.QUEUEPBSIMPLE_ID_FIELD.number = 2
Queue_Local_Var_Table.QUEUEPBSIMPLE_ID_FIELD.index = 1
Queue_Local_Var_Table.QUEUEPBSIMPLE_ID_FIELD.label = 2
Queue_Local_Var_Table.QUEUEPBSIMPLE_ID_FIELD.has_default_value = false
Queue_Local_Var_Table.QUEUEPBSIMPLE_ID_FIELD.default_value = ""
Queue_Local_Var_Table.QUEUEPBSIMPLE_ID_FIELD.type = 9
Queue_Local_Var_Table.QUEUEPBSIMPLE_ID_FIELD.cpp_type = 9

QUEUEPBSIMPLE.name = "QueuePBSimple"
QUEUEPBSIMPLE.full_name = ".QueuePBSimple"
QUEUEPBSIMPLE.nested_types = {}
QUEUEPBSIMPLE.enum_types = {}
QUEUEPBSIMPLE.fields = {Queue_Local_Var_Table.QUEUEPBSIMPLE_QUEUETYPE_FIELD, Queue_Local_Var_Table.QUEUEPBSIMPLE_ID_FIELD}
QUEUEPBSIMPLE.is_extendable = false
QUEUEPBSIMPLE.extensions = {}

HPQueueInfoSync = protobuf.Message(HPQUEUEINFOSYNC)
QueueCancelReq = protobuf.Message(QUEUECANCELREQ)
QueueFinishFreeReq = protobuf.Message(QUEUEFINISHFREEREQ)
QueuePB = protobuf.Message(QUEUEPB)
QueuePBSimple = protobuf.Message(QUEUEPBSIMPLE)
QueueSpeedUpReq = protobuf.Message(QUEUESPEEDUPREQ)

