-- Generated By protoc-gen-lua Do not Edit


local Reward_Local_Var_Table = {}

local protobuf = require "protobuf"
module('Reward_pb')


REWARDITEM = protobuf.Descriptor();
Reward_Local_Var_Table.REWARDITEM_ITEMID_FIELD = protobuf.FieldDescriptor();
Reward_Local_Var_Table.REWARDITEM_ITEMTYPE_FIELD = protobuf.FieldDescriptor();
Reward_Local_Var_Table.REWARDITEM_ITEMCOUNT_FIELD = protobuf.FieldDescriptor();
REWARDINFO = protobuf.Descriptor();
Reward_Local_Var_Table.REWARDINFO_GOLD_FIELD = protobuf.FieldDescriptor();
Reward_Local_Var_Table.REWARDINFO_COIN_FIELD = protobuf.FieldDescriptor();
Reward_Local_Var_Table.REWARDINFO_GOLDORE_FIELD = protobuf.FieldDescriptor();
Reward_Local_Var_Table.REWARDINFO_OIL_FIELD = protobuf.FieldDescriptor();
Reward_Local_Var_Table.REWARDINFO_STEEL_FIELD = protobuf.FieldDescriptor();
Reward_Local_Var_Table.REWARDINFO_TOMBARTHITE_FIELD = protobuf.FieldDescriptor();
Reward_Local_Var_Table.REWARDINFO_LEVEL_FIELD = protobuf.FieldDescriptor();
Reward_Local_Var_Table.REWARDINFO_EXP_FIELD = protobuf.FieldDescriptor();
Reward_Local_Var_Table.REWARDINFO_VIPLEVEL_FIELD = protobuf.FieldDescriptor();
Reward_Local_Var_Table.REWARDINFO_VIPPOINT_FIELD = protobuf.FieldDescriptor();
Reward_Local_Var_Table.REWARDINFO_VIPENDTIME_FIELD = protobuf.FieldDescriptor();
Reward_Local_Var_Table.REWARDINFO_ELECTRIC_FIELD = protobuf.FieldDescriptor();
Reward_Local_Var_Table.REWARDINFO_ELECTRICMAX_FIELD = protobuf.FieldDescriptor();
Reward_Local_Var_Table.REWARDINFO_VIT_FIELD = protobuf.FieldDescriptor();
Reward_Local_Var_Table.REWARDINFO_GUILDCONTRIBUTION_FIELD = protobuf.FieldDescriptor();
Reward_Local_Var_Table.REWARDINFO_SHOWITEMS_FIELD = protobuf.FieldDescriptor();
HPPLAYERREWARD = protobuf.Descriptor();
Reward_Local_Var_Table.HPPLAYERREWARD_FLAG_FIELD = protobuf.FieldDescriptor();
Reward_Local_Var_Table.HPPLAYERREWARD_REWARDS_FIELD = protobuf.FieldDescriptor();

Reward_Local_Var_Table.REWARDITEM_ITEMID_FIELD.name = "itemId"
Reward_Local_Var_Table.REWARDITEM_ITEMID_FIELD.full_name = ".RewardItem.itemId"
Reward_Local_Var_Table.REWARDITEM_ITEMID_FIELD.number = 1
Reward_Local_Var_Table.REWARDITEM_ITEMID_FIELD.index = 0
Reward_Local_Var_Table.REWARDITEM_ITEMID_FIELD.label = 2
Reward_Local_Var_Table.REWARDITEM_ITEMID_FIELD.has_default_value = false
Reward_Local_Var_Table.REWARDITEM_ITEMID_FIELD.default_value = 0
Reward_Local_Var_Table.REWARDITEM_ITEMID_FIELD.type = 5
Reward_Local_Var_Table.REWARDITEM_ITEMID_FIELD.cpp_type = 1

Reward_Local_Var_Table.REWARDITEM_ITEMTYPE_FIELD.name = "itemType"
Reward_Local_Var_Table.REWARDITEM_ITEMTYPE_FIELD.full_name = ".RewardItem.itemType"
Reward_Local_Var_Table.REWARDITEM_ITEMTYPE_FIELD.number = 2
Reward_Local_Var_Table.REWARDITEM_ITEMTYPE_FIELD.index = 1
Reward_Local_Var_Table.REWARDITEM_ITEMTYPE_FIELD.label = 2
Reward_Local_Var_Table.REWARDITEM_ITEMTYPE_FIELD.has_default_value = false
Reward_Local_Var_Table.REWARDITEM_ITEMTYPE_FIELD.default_value = 0
Reward_Local_Var_Table.REWARDITEM_ITEMTYPE_FIELD.type = 5
Reward_Local_Var_Table.REWARDITEM_ITEMTYPE_FIELD.cpp_type = 1

Reward_Local_Var_Table.REWARDITEM_ITEMCOUNT_FIELD.name = "itemCount"
Reward_Local_Var_Table.REWARDITEM_ITEMCOUNT_FIELD.full_name = ".RewardItem.itemCount"
Reward_Local_Var_Table.REWARDITEM_ITEMCOUNT_FIELD.number = 3
Reward_Local_Var_Table.REWARDITEM_ITEMCOUNT_FIELD.index = 2
Reward_Local_Var_Table.REWARDITEM_ITEMCOUNT_FIELD.label = 2
Reward_Local_Var_Table.REWARDITEM_ITEMCOUNT_FIELD.has_default_value = false
Reward_Local_Var_Table.REWARDITEM_ITEMCOUNT_FIELD.default_value = 0
Reward_Local_Var_Table.REWARDITEM_ITEMCOUNT_FIELD.type = 3
Reward_Local_Var_Table.REWARDITEM_ITEMCOUNT_FIELD.cpp_type = 2

REWARDITEM.name = "RewardItem"
REWARDITEM.full_name = ".RewardItem"
REWARDITEM.nested_types = {}
REWARDITEM.enum_types = {}
REWARDITEM.fields = {Reward_Local_Var_Table.REWARDITEM_ITEMID_FIELD, Reward_Local_Var_Table.REWARDITEM_ITEMTYPE_FIELD, Reward_Local_Var_Table.REWARDITEM_ITEMCOUNT_FIELD}
REWARDITEM.is_extendable = false
REWARDITEM.extensions = {}
Reward_Local_Var_Table.REWARDINFO_GOLD_FIELD.name = "gold"
Reward_Local_Var_Table.REWARDINFO_GOLD_FIELD.full_name = ".RewardInfo.gold"
Reward_Local_Var_Table.REWARDINFO_GOLD_FIELD.number = 1
Reward_Local_Var_Table.REWARDINFO_GOLD_FIELD.index = 0
Reward_Local_Var_Table.REWARDINFO_GOLD_FIELD.label = 1
Reward_Local_Var_Table.REWARDINFO_GOLD_FIELD.has_default_value = false
Reward_Local_Var_Table.REWARDINFO_GOLD_FIELD.default_value = 0
Reward_Local_Var_Table.REWARDINFO_GOLD_FIELD.type = 5
Reward_Local_Var_Table.REWARDINFO_GOLD_FIELD.cpp_type = 1

Reward_Local_Var_Table.REWARDINFO_COIN_FIELD.name = "coin"
Reward_Local_Var_Table.REWARDINFO_COIN_FIELD.full_name = ".RewardInfo.coin"
Reward_Local_Var_Table.REWARDINFO_COIN_FIELD.number = 2
Reward_Local_Var_Table.REWARDINFO_COIN_FIELD.index = 1
Reward_Local_Var_Table.REWARDINFO_COIN_FIELD.label = 1
Reward_Local_Var_Table.REWARDINFO_COIN_FIELD.has_default_value = false
Reward_Local_Var_Table.REWARDINFO_COIN_FIELD.default_value = 0
Reward_Local_Var_Table.REWARDINFO_COIN_FIELD.type = 5
Reward_Local_Var_Table.REWARDINFO_COIN_FIELD.cpp_type = 1

Reward_Local_Var_Table.REWARDINFO_GOLDORE_FIELD.name = "goldore"
Reward_Local_Var_Table.REWARDINFO_GOLDORE_FIELD.full_name = ".RewardInfo.goldore"
Reward_Local_Var_Table.REWARDINFO_GOLDORE_FIELD.number = 4
Reward_Local_Var_Table.REWARDINFO_GOLDORE_FIELD.index = 2
Reward_Local_Var_Table.REWARDINFO_GOLDORE_FIELD.label = 1
Reward_Local_Var_Table.REWARDINFO_GOLDORE_FIELD.has_default_value = false
Reward_Local_Var_Table.REWARDINFO_GOLDORE_FIELD.default_value = 0
Reward_Local_Var_Table.REWARDINFO_GOLDORE_FIELD.type = 3
Reward_Local_Var_Table.REWARDINFO_GOLDORE_FIELD.cpp_type = 2

Reward_Local_Var_Table.REWARDINFO_OIL_FIELD.name = "oil"
Reward_Local_Var_Table.REWARDINFO_OIL_FIELD.full_name = ".RewardInfo.oil"
Reward_Local_Var_Table.REWARDINFO_OIL_FIELD.number = 5
Reward_Local_Var_Table.REWARDINFO_OIL_FIELD.index = 3
Reward_Local_Var_Table.REWARDINFO_OIL_FIELD.label = 1
Reward_Local_Var_Table.REWARDINFO_OIL_FIELD.has_default_value = false
Reward_Local_Var_Table.REWARDINFO_OIL_FIELD.default_value = 0
Reward_Local_Var_Table.REWARDINFO_OIL_FIELD.type = 3
Reward_Local_Var_Table.REWARDINFO_OIL_FIELD.cpp_type = 2

Reward_Local_Var_Table.REWARDINFO_STEEL_FIELD.name = "steel"
Reward_Local_Var_Table.REWARDINFO_STEEL_FIELD.full_name = ".RewardInfo.steel"
Reward_Local_Var_Table.REWARDINFO_STEEL_FIELD.number = 6
Reward_Local_Var_Table.REWARDINFO_STEEL_FIELD.index = 4
Reward_Local_Var_Table.REWARDINFO_STEEL_FIELD.label = 1
Reward_Local_Var_Table.REWARDINFO_STEEL_FIELD.has_default_value = false
Reward_Local_Var_Table.REWARDINFO_STEEL_FIELD.default_value = 0
Reward_Local_Var_Table.REWARDINFO_STEEL_FIELD.type = 3
Reward_Local_Var_Table.REWARDINFO_STEEL_FIELD.cpp_type = 2

Reward_Local_Var_Table.REWARDINFO_TOMBARTHITE_FIELD.name = "tombarthite"
Reward_Local_Var_Table.REWARDINFO_TOMBARTHITE_FIELD.full_name = ".RewardInfo.tombarthite"
Reward_Local_Var_Table.REWARDINFO_TOMBARTHITE_FIELD.number = 7
Reward_Local_Var_Table.REWARDINFO_TOMBARTHITE_FIELD.index = 5
Reward_Local_Var_Table.REWARDINFO_TOMBARTHITE_FIELD.label = 1
Reward_Local_Var_Table.REWARDINFO_TOMBARTHITE_FIELD.has_default_value = false
Reward_Local_Var_Table.REWARDINFO_TOMBARTHITE_FIELD.default_value = 0
Reward_Local_Var_Table.REWARDINFO_TOMBARTHITE_FIELD.type = 3
Reward_Local_Var_Table.REWARDINFO_TOMBARTHITE_FIELD.cpp_type = 2

Reward_Local_Var_Table.REWARDINFO_LEVEL_FIELD.name = "level"
Reward_Local_Var_Table.REWARDINFO_LEVEL_FIELD.full_name = ".RewardInfo.level"
Reward_Local_Var_Table.REWARDINFO_LEVEL_FIELD.number = 8
Reward_Local_Var_Table.REWARDINFO_LEVEL_FIELD.index = 6
Reward_Local_Var_Table.REWARDINFO_LEVEL_FIELD.label = 1
Reward_Local_Var_Table.REWARDINFO_LEVEL_FIELD.has_default_value = false
Reward_Local_Var_Table.REWARDINFO_LEVEL_FIELD.default_value = 0
Reward_Local_Var_Table.REWARDINFO_LEVEL_FIELD.type = 5
Reward_Local_Var_Table.REWARDINFO_LEVEL_FIELD.cpp_type = 1

Reward_Local_Var_Table.REWARDINFO_EXP_FIELD.name = "exp"
Reward_Local_Var_Table.REWARDINFO_EXP_FIELD.full_name = ".RewardInfo.exp"
Reward_Local_Var_Table.REWARDINFO_EXP_FIELD.number = 9
Reward_Local_Var_Table.REWARDINFO_EXP_FIELD.index = 7
Reward_Local_Var_Table.REWARDINFO_EXP_FIELD.label = 1
Reward_Local_Var_Table.REWARDINFO_EXP_FIELD.has_default_value = false
Reward_Local_Var_Table.REWARDINFO_EXP_FIELD.default_value = 0
Reward_Local_Var_Table.REWARDINFO_EXP_FIELD.type = 5
Reward_Local_Var_Table.REWARDINFO_EXP_FIELD.cpp_type = 1

Reward_Local_Var_Table.REWARDINFO_VIPLEVEL_FIELD.name = "vipLevel"
Reward_Local_Var_Table.REWARDINFO_VIPLEVEL_FIELD.full_name = ".RewardInfo.vipLevel"
Reward_Local_Var_Table.REWARDINFO_VIPLEVEL_FIELD.number = 10
Reward_Local_Var_Table.REWARDINFO_VIPLEVEL_FIELD.index = 8
Reward_Local_Var_Table.REWARDINFO_VIPLEVEL_FIELD.label = 1
Reward_Local_Var_Table.REWARDINFO_VIPLEVEL_FIELD.has_default_value = false
Reward_Local_Var_Table.REWARDINFO_VIPLEVEL_FIELD.default_value = 0
Reward_Local_Var_Table.REWARDINFO_VIPLEVEL_FIELD.type = 5
Reward_Local_Var_Table.REWARDINFO_VIPLEVEL_FIELD.cpp_type = 1

Reward_Local_Var_Table.REWARDINFO_VIPPOINT_FIELD.name = "vipPoint"
Reward_Local_Var_Table.REWARDINFO_VIPPOINT_FIELD.full_name = ".RewardInfo.vipPoint"
Reward_Local_Var_Table.REWARDINFO_VIPPOINT_FIELD.number = 11
Reward_Local_Var_Table.REWARDINFO_VIPPOINT_FIELD.index = 9
Reward_Local_Var_Table.REWARDINFO_VIPPOINT_FIELD.label = 1
Reward_Local_Var_Table.REWARDINFO_VIPPOINT_FIELD.has_default_value = false
Reward_Local_Var_Table.REWARDINFO_VIPPOINT_FIELD.default_value = 0
Reward_Local_Var_Table.REWARDINFO_VIPPOINT_FIELD.type = 3
Reward_Local_Var_Table.REWARDINFO_VIPPOINT_FIELD.cpp_type = 2

Reward_Local_Var_Table.REWARDINFO_VIPENDTIME_FIELD.name = "vipEndTime"
Reward_Local_Var_Table.REWARDINFO_VIPENDTIME_FIELD.full_name = ".RewardInfo.vipEndTime"
Reward_Local_Var_Table.REWARDINFO_VIPENDTIME_FIELD.number = 12
Reward_Local_Var_Table.REWARDINFO_VIPENDTIME_FIELD.index = 10
Reward_Local_Var_Table.REWARDINFO_VIPENDTIME_FIELD.label = 1
Reward_Local_Var_Table.REWARDINFO_VIPENDTIME_FIELD.has_default_value = false
Reward_Local_Var_Table.REWARDINFO_VIPENDTIME_FIELD.default_value = 0
Reward_Local_Var_Table.REWARDINFO_VIPENDTIME_FIELD.type = 3
Reward_Local_Var_Table.REWARDINFO_VIPENDTIME_FIELD.cpp_type = 2

Reward_Local_Var_Table.REWARDINFO_ELECTRIC_FIELD.name = "electric"
Reward_Local_Var_Table.REWARDINFO_ELECTRIC_FIELD.full_name = ".RewardInfo.electric"
Reward_Local_Var_Table.REWARDINFO_ELECTRIC_FIELD.number = 13
Reward_Local_Var_Table.REWARDINFO_ELECTRIC_FIELD.index = 11
Reward_Local_Var_Table.REWARDINFO_ELECTRIC_FIELD.label = 1
Reward_Local_Var_Table.REWARDINFO_ELECTRIC_FIELD.has_default_value = false
Reward_Local_Var_Table.REWARDINFO_ELECTRIC_FIELD.default_value = 0
Reward_Local_Var_Table.REWARDINFO_ELECTRIC_FIELD.type = 3
Reward_Local_Var_Table.REWARDINFO_ELECTRIC_FIELD.cpp_type = 2

Reward_Local_Var_Table.REWARDINFO_ELECTRICMAX_FIELD.name = "electricMax"
Reward_Local_Var_Table.REWARDINFO_ELECTRICMAX_FIELD.full_name = ".RewardInfo.electricMax"
Reward_Local_Var_Table.REWARDINFO_ELECTRICMAX_FIELD.number = 14
Reward_Local_Var_Table.REWARDINFO_ELECTRICMAX_FIELD.index = 12
Reward_Local_Var_Table.REWARDINFO_ELECTRICMAX_FIELD.label = 1
Reward_Local_Var_Table.REWARDINFO_ELECTRICMAX_FIELD.has_default_value = false
Reward_Local_Var_Table.REWARDINFO_ELECTRICMAX_FIELD.default_value = 0
Reward_Local_Var_Table.REWARDINFO_ELECTRICMAX_FIELD.type = 3
Reward_Local_Var_Table.REWARDINFO_ELECTRICMAX_FIELD.cpp_type = 2

Reward_Local_Var_Table.REWARDINFO_VIT_FIELD.name = "vit"
Reward_Local_Var_Table.REWARDINFO_VIT_FIELD.full_name = ".RewardInfo.vit"
Reward_Local_Var_Table.REWARDINFO_VIT_FIELD.number = 15
Reward_Local_Var_Table.REWARDINFO_VIT_FIELD.index = 13
Reward_Local_Var_Table.REWARDINFO_VIT_FIELD.label = 1
Reward_Local_Var_Table.REWARDINFO_VIT_FIELD.has_default_value = false
Reward_Local_Var_Table.REWARDINFO_VIT_FIELD.default_value = 0
Reward_Local_Var_Table.REWARDINFO_VIT_FIELD.type = 5
Reward_Local_Var_Table.REWARDINFO_VIT_FIELD.cpp_type = 1

Reward_Local_Var_Table.REWARDINFO_GUILDCONTRIBUTION_FIELD.name = "guildContribution"
Reward_Local_Var_Table.REWARDINFO_GUILDCONTRIBUTION_FIELD.full_name = ".RewardInfo.guildContribution"
Reward_Local_Var_Table.REWARDINFO_GUILDCONTRIBUTION_FIELD.number = 16
Reward_Local_Var_Table.REWARDINFO_GUILDCONTRIBUTION_FIELD.index = 14
Reward_Local_Var_Table.REWARDINFO_GUILDCONTRIBUTION_FIELD.label = 1
Reward_Local_Var_Table.REWARDINFO_GUILDCONTRIBUTION_FIELD.has_default_value = false
Reward_Local_Var_Table.REWARDINFO_GUILDCONTRIBUTION_FIELD.default_value = 0
Reward_Local_Var_Table.REWARDINFO_GUILDCONTRIBUTION_FIELD.type = 5
Reward_Local_Var_Table.REWARDINFO_GUILDCONTRIBUTION_FIELD.cpp_type = 1

Reward_Local_Var_Table.REWARDINFO_SHOWITEMS_FIELD.name = "showItems"
Reward_Local_Var_Table.REWARDINFO_SHOWITEMS_FIELD.full_name = ".RewardInfo.showItems"
Reward_Local_Var_Table.REWARDINFO_SHOWITEMS_FIELD.number = 20
Reward_Local_Var_Table.REWARDINFO_SHOWITEMS_FIELD.index = 15
Reward_Local_Var_Table.REWARDINFO_SHOWITEMS_FIELD.label = 3
Reward_Local_Var_Table.REWARDINFO_SHOWITEMS_FIELD.has_default_value = false
Reward_Local_Var_Table.REWARDINFO_SHOWITEMS_FIELD.default_value = {}
Reward_Local_Var_Table.REWARDINFO_SHOWITEMS_FIELD.message_type = REWARDITEM
Reward_Local_Var_Table.REWARDINFO_SHOWITEMS_FIELD.type = 11
Reward_Local_Var_Table.REWARDINFO_SHOWITEMS_FIELD.cpp_type = 10

REWARDINFO.name = "RewardInfo"
REWARDINFO.full_name = ".RewardInfo"
REWARDINFO.nested_types = {}
REWARDINFO.enum_types = {}
REWARDINFO.fields = {Reward_Local_Var_Table.REWARDINFO_GOLD_FIELD, Reward_Local_Var_Table.REWARDINFO_COIN_FIELD, Reward_Local_Var_Table.REWARDINFO_GOLDORE_FIELD, Reward_Local_Var_Table.REWARDINFO_OIL_FIELD, Reward_Local_Var_Table.REWARDINFO_STEEL_FIELD, Reward_Local_Var_Table.REWARDINFO_TOMBARTHITE_FIELD, Reward_Local_Var_Table.REWARDINFO_LEVEL_FIELD, Reward_Local_Var_Table.REWARDINFO_EXP_FIELD, Reward_Local_Var_Table.REWARDINFO_VIPLEVEL_FIELD, Reward_Local_Var_Table.REWARDINFO_VIPPOINT_FIELD, Reward_Local_Var_Table.REWARDINFO_VIPENDTIME_FIELD, Reward_Local_Var_Table.REWARDINFO_ELECTRIC_FIELD, Reward_Local_Var_Table.REWARDINFO_ELECTRICMAX_FIELD, Reward_Local_Var_Table.REWARDINFO_VIT_FIELD, Reward_Local_Var_Table.REWARDINFO_GUILDCONTRIBUTION_FIELD, Reward_Local_Var_Table.REWARDINFO_SHOWITEMS_FIELD}
REWARDINFO.is_extendable = false
REWARDINFO.extensions = {}
Reward_Local_Var_Table.HPPLAYERREWARD_FLAG_FIELD.name = "flag"
Reward_Local_Var_Table.HPPLAYERREWARD_FLAG_FIELD.full_name = ".HPPlayerReward.flag"
Reward_Local_Var_Table.HPPLAYERREWARD_FLAG_FIELD.number = 1
Reward_Local_Var_Table.HPPLAYERREWARD_FLAG_FIELD.index = 0
Reward_Local_Var_Table.HPPLAYERREWARD_FLAG_FIELD.label = 1
Reward_Local_Var_Table.HPPLAYERREWARD_FLAG_FIELD.has_default_value = false
Reward_Local_Var_Table.HPPLAYERREWARD_FLAG_FIELD.default_value = 0
Reward_Local_Var_Table.HPPLAYERREWARD_FLAG_FIELD.type = 5
Reward_Local_Var_Table.HPPLAYERREWARD_FLAG_FIELD.cpp_type = 1

Reward_Local_Var_Table.HPPLAYERREWARD_REWARDS_FIELD.name = "rewards"
Reward_Local_Var_Table.HPPLAYERREWARD_REWARDS_FIELD.full_name = ".HPPlayerReward.rewards"
Reward_Local_Var_Table.HPPLAYERREWARD_REWARDS_FIELD.number = 2
Reward_Local_Var_Table.HPPLAYERREWARD_REWARDS_FIELD.index = 1
Reward_Local_Var_Table.HPPLAYERREWARD_REWARDS_FIELD.label = 1
Reward_Local_Var_Table.HPPLAYERREWARD_REWARDS_FIELD.has_default_value = false
Reward_Local_Var_Table.HPPLAYERREWARD_REWARDS_FIELD.default_value = nil
Reward_Local_Var_Table.HPPLAYERREWARD_REWARDS_FIELD.message_type = REWARDINFO
Reward_Local_Var_Table.HPPLAYERREWARD_REWARDS_FIELD.type = 11
Reward_Local_Var_Table.HPPLAYERREWARD_REWARDS_FIELD.cpp_type = 10

HPPLAYERREWARD.name = "HPPlayerReward"
HPPLAYERREWARD.full_name = ".HPPlayerReward"
HPPLAYERREWARD.nested_types = {}
HPPLAYERREWARD.enum_types = {}
HPPLAYERREWARD.fields = {Reward_Local_Var_Table.HPPLAYERREWARD_FLAG_FIELD, Reward_Local_Var_Table.HPPLAYERREWARD_REWARDS_FIELD}
HPPLAYERREWARD.is_extendable = false
HPPLAYERREWARD.extensions = {}

HPPlayerReward = protobuf.Message(HPPLAYERREWARD)
RewardInfo = protobuf.Message(REWARDINFO)
RewardItem = protobuf.Message(REWARDITEM)

