-- Generated By protoc-gen-lua Do not Edit


local Setting_Local_Var_Table = {}

local protobuf = require "protobuf"
module('Setting_pb')


SETTINGINFO = protobuf.Descriptor();
Setting_Local_Var_Table.SETTINGINFO_ID_FIELD = protobuf.FieldDescriptor();
Setting_Local_Var_Table.SETTINGINFO_SETTINGID_FIELD = protobuf.FieldDescriptor();
Setting_Local_Var_Table.SETTINGINFO_VALUE_FIELD = protobuf.FieldDescriptor();
HPSETTINGINFOSYNC = protobuf.Descriptor();
Setting_Local_Var_Table.HPSETTINGINFOSYNC_SETTINGINFOS_FIELD = protobuf.FieldDescriptor();
HPSETTINGUPDATEREQ = protobuf.Descriptor();
Setting_Local_Var_Table.HPSETTINGUPDATEREQ_SETTINGID_FIELD = protobuf.FieldDescriptor();
Setting_Local_Var_Table.HPSETTINGUPDATEREQ_VALUE_FIELD = protobuf.FieldDescriptor();

Setting_Local_Var_Table.SETTINGINFO_ID_FIELD.name = "id"
Setting_Local_Var_Table.SETTINGINFO_ID_FIELD.full_name = ".SettingInfo.id"
Setting_Local_Var_Table.SETTINGINFO_ID_FIELD.number = 1
Setting_Local_Var_Table.SETTINGINFO_ID_FIELD.index = 0
Setting_Local_Var_Table.SETTINGINFO_ID_FIELD.label = 2
Setting_Local_Var_Table.SETTINGINFO_ID_FIELD.has_default_value = false
Setting_Local_Var_Table.SETTINGINFO_ID_FIELD.default_value = ""
Setting_Local_Var_Table.SETTINGINFO_ID_FIELD.type = 9
Setting_Local_Var_Table.SETTINGINFO_ID_FIELD.cpp_type = 9

Setting_Local_Var_Table.SETTINGINFO_SETTINGID_FIELD.name = "settingId"
Setting_Local_Var_Table.SETTINGINFO_SETTINGID_FIELD.full_name = ".SettingInfo.settingId"
Setting_Local_Var_Table.SETTINGINFO_SETTINGID_FIELD.number = 2
Setting_Local_Var_Table.SETTINGINFO_SETTINGID_FIELD.index = 1
Setting_Local_Var_Table.SETTINGINFO_SETTINGID_FIELD.label = 2
Setting_Local_Var_Table.SETTINGINFO_SETTINGID_FIELD.has_default_value = false
Setting_Local_Var_Table.SETTINGINFO_SETTINGID_FIELD.default_value = 0
Setting_Local_Var_Table.SETTINGINFO_SETTINGID_FIELD.type = 5
Setting_Local_Var_Table.SETTINGINFO_SETTINGID_FIELD.cpp_type = 1

Setting_Local_Var_Table.SETTINGINFO_VALUE_FIELD.name = "value"
Setting_Local_Var_Table.SETTINGINFO_VALUE_FIELD.full_name = ".SettingInfo.value"
Setting_Local_Var_Table.SETTINGINFO_VALUE_FIELD.number = 3
Setting_Local_Var_Table.SETTINGINFO_VALUE_FIELD.index = 2
Setting_Local_Var_Table.SETTINGINFO_VALUE_FIELD.label = 2
Setting_Local_Var_Table.SETTINGINFO_VALUE_FIELD.has_default_value = false
Setting_Local_Var_Table.SETTINGINFO_VALUE_FIELD.default_value = 0
Setting_Local_Var_Table.SETTINGINFO_VALUE_FIELD.type = 5
Setting_Local_Var_Table.SETTINGINFO_VALUE_FIELD.cpp_type = 1

SETTINGINFO.name = "SettingInfo"
SETTINGINFO.full_name = ".SettingInfo"
SETTINGINFO.nested_types = {}
SETTINGINFO.enum_types = {}
SETTINGINFO.fields = {Setting_Local_Var_Table.SETTINGINFO_ID_FIELD, Setting_Local_Var_Table.SETTINGINFO_SETTINGID_FIELD, Setting_Local_Var_Table.SETTINGINFO_VALUE_FIELD}
SETTINGINFO.is_extendable = false
SETTINGINFO.extensions = {}
Setting_Local_Var_Table.HPSETTINGINFOSYNC_SETTINGINFOS_FIELD.name = "settingInfos"
Setting_Local_Var_Table.HPSETTINGINFOSYNC_SETTINGINFOS_FIELD.full_name = ".HPSettingInfoSync.settingInfos"
Setting_Local_Var_Table.HPSETTINGINFOSYNC_SETTINGINFOS_FIELD.number = 1
Setting_Local_Var_Table.HPSETTINGINFOSYNC_SETTINGINFOS_FIELD.index = 0
Setting_Local_Var_Table.HPSETTINGINFOSYNC_SETTINGINFOS_FIELD.label = 3
Setting_Local_Var_Table.HPSETTINGINFOSYNC_SETTINGINFOS_FIELD.has_default_value = false
Setting_Local_Var_Table.HPSETTINGINFOSYNC_SETTINGINFOS_FIELD.default_value = {}
Setting_Local_Var_Table.HPSETTINGINFOSYNC_SETTINGINFOS_FIELD.message_type = SETTINGINFO
Setting_Local_Var_Table.HPSETTINGINFOSYNC_SETTINGINFOS_FIELD.type = 11
Setting_Local_Var_Table.HPSETTINGINFOSYNC_SETTINGINFOS_FIELD.cpp_type = 10

HPSETTINGINFOSYNC.name = "HPSettingInfoSync"
HPSETTINGINFOSYNC.full_name = ".HPSettingInfoSync"
HPSETTINGINFOSYNC.nested_types = {}
HPSETTINGINFOSYNC.enum_types = {}
HPSETTINGINFOSYNC.fields = {Setting_Local_Var_Table.HPSETTINGINFOSYNC_SETTINGINFOS_FIELD}
HPSETTINGINFOSYNC.is_extendable = false
HPSETTINGINFOSYNC.extensions = {}
Setting_Local_Var_Table.HPSETTINGUPDATEREQ_SETTINGID_FIELD.name = "settingId"
Setting_Local_Var_Table.HPSETTINGUPDATEREQ_SETTINGID_FIELD.full_name = ".HPSettingUpdateReq.settingId"
Setting_Local_Var_Table.HPSETTINGUPDATEREQ_SETTINGID_FIELD.number = 1
Setting_Local_Var_Table.HPSETTINGUPDATEREQ_SETTINGID_FIELD.index = 0
Setting_Local_Var_Table.HPSETTINGUPDATEREQ_SETTINGID_FIELD.label = 2
Setting_Local_Var_Table.HPSETTINGUPDATEREQ_SETTINGID_FIELD.has_default_value = false
Setting_Local_Var_Table.HPSETTINGUPDATEREQ_SETTINGID_FIELD.default_value = 0
Setting_Local_Var_Table.HPSETTINGUPDATEREQ_SETTINGID_FIELD.type = 5
Setting_Local_Var_Table.HPSETTINGUPDATEREQ_SETTINGID_FIELD.cpp_type = 1

Setting_Local_Var_Table.HPSETTINGUPDATEREQ_VALUE_FIELD.name = "value"
Setting_Local_Var_Table.HPSETTINGUPDATEREQ_VALUE_FIELD.full_name = ".HPSettingUpdateReq.value"
Setting_Local_Var_Table.HPSETTINGUPDATEREQ_VALUE_FIELD.number = 2
Setting_Local_Var_Table.HPSETTINGUPDATEREQ_VALUE_FIELD.index = 1
Setting_Local_Var_Table.HPSETTINGUPDATEREQ_VALUE_FIELD.label = 2
Setting_Local_Var_Table.HPSETTINGUPDATEREQ_VALUE_FIELD.has_default_value = false
Setting_Local_Var_Table.HPSETTINGUPDATEREQ_VALUE_FIELD.default_value = 0
Setting_Local_Var_Table.HPSETTINGUPDATEREQ_VALUE_FIELD.type = 5
Setting_Local_Var_Table.HPSETTINGUPDATEREQ_VALUE_FIELD.cpp_type = 1

HPSETTINGUPDATEREQ.name = "HPSettingUpdateReq"
HPSETTINGUPDATEREQ.full_name = ".HPSettingUpdateReq"
HPSETTINGUPDATEREQ.nested_types = {}
HPSETTINGUPDATEREQ.enum_types = {}
HPSETTINGUPDATEREQ.fields = {Setting_Local_Var_Table.HPSETTINGUPDATEREQ_SETTINGID_FIELD, Setting_Local_Var_Table.HPSETTINGUPDATEREQ_VALUE_FIELD}
HPSETTINGUPDATEREQ.is_extendable = false
HPSETTINGUPDATEREQ.extensions = {}

HPSettingInfoSync = protobuf.Message(HPSETTINGINFOSYNC)
HPSettingUpdateReq = protobuf.Message(HPSETTINGUPDATEREQ)
SettingInfo = protobuf.Message(SETTINGINFO)

