-- Generated By protoc-gen-lua Do not Edit


local SysPush_Local_Var_Table = {}

local protobuf = require "protobuf"
module('SysPush_pb')


SysPush_Local_Var_Table.PUSH = protobuf.EnumDescriptor();
SysPush_Local_Var_Table.PUSH_PUSH_NOTIFICATION_ENUM = protobuf.EnumValueDescriptor();
HPPUSHNOTIFICATION = protobuf.Descriptor();
SysPush_Local_Var_Table.HPPUSHNOTIFICATION_JSONDATA_FIELD = protobuf.FieldDescriptor();

SysPush_Local_Var_Table.PUSH_PUSH_NOTIFICATION_ENUM.name = "PUSH_NOTIFICATION"
SysPush_Local_Var_Table.PUSH_PUSH_NOTIFICATION_ENUM.index = 0
SysPush_Local_Var_Table.PUSH_PUSH_NOTIFICATION_ENUM.number = 70
SysPush_Local_Var_Table.PUSH.name = "push"
SysPush_Local_Var_Table.PUSH.full_name = ".push"
SysPush_Local_Var_Table.PUSH.values = {}
SysPush_Local_Var_Table.PUSH.values[1] = SysPush_Local_Var_Table.PUSH_PUSH_NOTIFICATION_ENUM;
SysPush_Local_Var_Table.HPPUSHNOTIFICATION_JSONDATA_FIELD.name = "jsonData"
SysPush_Local_Var_Table.HPPUSHNOTIFICATION_JSONDATA_FIELD.full_name = ".HPPushNotification.jsonData"
SysPush_Local_Var_Table.HPPUSHNOTIFICATION_JSONDATA_FIELD.number = 1
SysPush_Local_Var_Table.HPPUSHNOTIFICATION_JSONDATA_FIELD.index = 0
SysPush_Local_Var_Table.HPPUSHNOTIFICATION_JSONDATA_FIELD.label = 2
SysPush_Local_Var_Table.HPPUSHNOTIFICATION_JSONDATA_FIELD.has_default_value = false
SysPush_Local_Var_Table.HPPUSHNOTIFICATION_JSONDATA_FIELD.default_value = ""
SysPush_Local_Var_Table.HPPUSHNOTIFICATION_JSONDATA_FIELD.type = 9
SysPush_Local_Var_Table.HPPUSHNOTIFICATION_JSONDATA_FIELD.cpp_type = 9

HPPUSHNOTIFICATION.name = "HPPushNotification"
HPPUSHNOTIFICATION.full_name = ".HPPushNotification"
HPPUSHNOTIFICATION.nested_types = {}
HPPUSHNOTIFICATION.enum_types = {}
HPPUSHNOTIFICATION.fields = {SysPush_Local_Var_Table.HPPUSHNOTIFICATION_JSONDATA_FIELD}
HPPUSHNOTIFICATION.is_extendable = false
HPPUSHNOTIFICATION.extensions = {}

HPPushNotification = protobuf.Message(HPPUSHNOTIFICATION)
PUSH_NOTIFICATION = 70

