-- Generated By protoc-gen-lua Do not Edit


local SysSearch_Local_Var_Table = {}

local protobuf = require "protobuf"
module('SysSearch_pb')


SysSearch_Local_Var_Table.SEARCH = protobuf.EnumDescriptor();
SysSearch_Local_Var_Table.SEARCH_UPDATE_KEY_DATA_ENUM = protobuf.EnumValueDescriptor();
SysSearch_Local_Var_Table.SEARCH_MATCHING_KEY_ENUM = protobuf.EnumValueDescriptor();
SysSearch_Local_Var_Table.SEARCH_KEY_INFO_RESULT_ENUM = protobuf.EnumValueDescriptor();
KEYINFO = protobuf.Descriptor();
SysSearch_Local_Var_Table.KEYINFO_KEY_FIELD = protobuf.FieldDescriptor();
SysSearch_Local_Var_Table.KEYINFO_INFO_FIELD = protobuf.FieldDescriptor();
HPUPDATEKEYINFO = protobuf.Descriptor();
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_TYPE_FIELD = protobuf.FieldDescriptor();
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_KEY_FIELD = protobuf.FieldDescriptor();
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_INFO_FIELD = protobuf.FieldDescriptor();
HPMATCHINGKEY = protobuf.Descriptor();
SysSearch_Local_Var_Table.HPMATCHINGKEY_TYPE_FIELD = protobuf.FieldDescriptor();
SysSearch_Local_Var_Table.HPMATCHINGKEY_KEYPREFIX_FIELD = protobuf.FieldDescriptor();
SysSearch_Local_Var_Table.HPMATCHINGKEY_COUNTLIMIT_FIELD = protobuf.FieldDescriptor();
HPKEYINFORESULT = protobuf.Descriptor();
SysSearch_Local_Var_Table.HPKEYINFORESULT_KEYPREFIX_FIELD = protobuf.FieldDescriptor();
SysSearch_Local_Var_Table.HPKEYINFORESULT_KEYINFOS_FIELD = protobuf.FieldDescriptor();

SysSearch_Local_Var_Table.SEARCH_UPDATE_KEY_DATA_ENUM.name = "UPDATE_KEY_DATA"
SysSearch_Local_Var_Table.SEARCH_UPDATE_KEY_DATA_ENUM.index = 0
SysSearch_Local_Var_Table.SEARCH_UPDATE_KEY_DATA_ENUM.number = 60
SysSearch_Local_Var_Table.SEARCH_MATCHING_KEY_ENUM.name = "MATCHING_KEY"
SysSearch_Local_Var_Table.SEARCH_MATCHING_KEY_ENUM.index = 1
SysSearch_Local_Var_Table.SEARCH_MATCHING_KEY_ENUM.number = 61
SysSearch_Local_Var_Table.SEARCH_KEY_INFO_RESULT_ENUM.name = "KEY_INFO_RESULT"
SysSearch_Local_Var_Table.SEARCH_KEY_INFO_RESULT_ENUM.index = 2
SysSearch_Local_Var_Table.SEARCH_KEY_INFO_RESULT_ENUM.number = 63
SysSearch_Local_Var_Table.SEARCH.name = "search"
SysSearch_Local_Var_Table.SEARCH.full_name = ".search"
SysSearch_Local_Var_Table.SEARCH.values = {}
SysSearch_Local_Var_Table.SEARCH.values[1] = SysSearch_Local_Var_Table.SEARCH_UPDATE_KEY_DATA_ENUM;
SysSearch_Local_Var_Table.SEARCH.values[2] = SysSearch_Local_Var_Table.SEARCH_MATCHING_KEY_ENUM;
SysSearch_Local_Var_Table.SEARCH.values[3] = SysSearch_Local_Var_Table.SEARCH_KEY_INFO_RESULT_ENUM;
SysSearch_Local_Var_Table.KEYINFO_KEY_FIELD.name = "key"
SysSearch_Local_Var_Table.KEYINFO_KEY_FIELD.full_name = ".KeyInfo.key"
SysSearch_Local_Var_Table.KEYINFO_KEY_FIELD.number = 1
SysSearch_Local_Var_Table.KEYINFO_KEY_FIELD.index = 0
SysSearch_Local_Var_Table.KEYINFO_KEY_FIELD.label = 2
SysSearch_Local_Var_Table.KEYINFO_KEY_FIELD.has_default_value = false
SysSearch_Local_Var_Table.KEYINFO_KEY_FIELD.default_value = ""
SysSearch_Local_Var_Table.KEYINFO_KEY_FIELD.type = 9
SysSearch_Local_Var_Table.KEYINFO_KEY_FIELD.cpp_type = 9

SysSearch_Local_Var_Table.KEYINFO_INFO_FIELD.name = "info"
SysSearch_Local_Var_Table.KEYINFO_INFO_FIELD.full_name = ".KeyInfo.info"
SysSearch_Local_Var_Table.KEYINFO_INFO_FIELD.number = 2
SysSearch_Local_Var_Table.KEYINFO_INFO_FIELD.index = 1
SysSearch_Local_Var_Table.KEYINFO_INFO_FIELD.label = 2
SysSearch_Local_Var_Table.KEYINFO_INFO_FIELD.has_default_value = false
SysSearch_Local_Var_Table.KEYINFO_INFO_FIELD.default_value = ""
SysSearch_Local_Var_Table.KEYINFO_INFO_FIELD.type = 9
SysSearch_Local_Var_Table.KEYINFO_INFO_FIELD.cpp_type = 9

KEYINFO.name = "KeyInfo"
KEYINFO.full_name = ".KeyInfo"
KEYINFO.nested_types = {}
KEYINFO.enum_types = {}
KEYINFO.fields = {SysSearch_Local_Var_Table.KEYINFO_KEY_FIELD, SysSearch_Local_Var_Table.KEYINFO_INFO_FIELD}
KEYINFO.is_extendable = false
KEYINFO.extensions = {}
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_TYPE_FIELD.name = "type"
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_TYPE_FIELD.full_name = ".HPUpdateKeyInfo.type"
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_TYPE_FIELD.number = 1
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_TYPE_FIELD.index = 0
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_TYPE_FIELD.label = 2
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_TYPE_FIELD.has_default_value = false
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_TYPE_FIELD.default_value = ""
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_TYPE_FIELD.type = 9
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_TYPE_FIELD.cpp_type = 9

SysSearch_Local_Var_Table.HPUPDATEKEYINFO_KEY_FIELD.name = "key"
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_KEY_FIELD.full_name = ".HPUpdateKeyInfo.key"
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_KEY_FIELD.number = 2
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_KEY_FIELD.index = 1
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_KEY_FIELD.label = 2
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_KEY_FIELD.has_default_value = false
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_KEY_FIELD.default_value = ""
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_KEY_FIELD.type = 9
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_KEY_FIELD.cpp_type = 9

SysSearch_Local_Var_Table.HPUPDATEKEYINFO_INFO_FIELD.name = "info"
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_INFO_FIELD.full_name = ".HPUpdateKeyInfo.info"
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_INFO_FIELD.number = 3
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_INFO_FIELD.index = 2
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_INFO_FIELD.label = 1
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_INFO_FIELD.has_default_value = false
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_INFO_FIELD.default_value = ""
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_INFO_FIELD.type = 9
SysSearch_Local_Var_Table.HPUPDATEKEYINFO_INFO_FIELD.cpp_type = 9

HPUPDATEKEYINFO.name = "HPUpdateKeyInfo"
HPUPDATEKEYINFO.full_name = ".HPUpdateKeyInfo"
HPUPDATEKEYINFO.nested_types = {}
HPUPDATEKEYINFO.enum_types = {}
HPUPDATEKEYINFO.fields = {SysSearch_Local_Var_Table.HPUPDATEKEYINFO_TYPE_FIELD, SysSearch_Local_Var_Table.HPUPDATEKEYINFO_KEY_FIELD, SysSearch_Local_Var_Table.HPUPDATEKEYINFO_INFO_FIELD}
HPUPDATEKEYINFO.is_extendable = false
HPUPDATEKEYINFO.extensions = {}
SysSearch_Local_Var_Table.HPMATCHINGKEY_TYPE_FIELD.name = "type"
SysSearch_Local_Var_Table.HPMATCHINGKEY_TYPE_FIELD.full_name = ".HPMatchingKey.type"
SysSearch_Local_Var_Table.HPMATCHINGKEY_TYPE_FIELD.number = 1
SysSearch_Local_Var_Table.HPMATCHINGKEY_TYPE_FIELD.index = 0
SysSearch_Local_Var_Table.HPMATCHINGKEY_TYPE_FIELD.label = 2
SysSearch_Local_Var_Table.HPMATCHINGKEY_TYPE_FIELD.has_default_value = false
SysSearch_Local_Var_Table.HPMATCHINGKEY_TYPE_FIELD.default_value = ""
SysSearch_Local_Var_Table.HPMATCHINGKEY_TYPE_FIELD.type = 9
SysSearch_Local_Var_Table.HPMATCHINGKEY_TYPE_FIELD.cpp_type = 9

SysSearch_Local_Var_Table.HPMATCHINGKEY_KEYPREFIX_FIELD.name = "keyPrefix"
SysSearch_Local_Var_Table.HPMATCHINGKEY_KEYPREFIX_FIELD.full_name = ".HPMatchingKey.keyPrefix"
SysSearch_Local_Var_Table.HPMATCHINGKEY_KEYPREFIX_FIELD.number = 2
SysSearch_Local_Var_Table.HPMATCHINGKEY_KEYPREFIX_FIELD.index = 1
SysSearch_Local_Var_Table.HPMATCHINGKEY_KEYPREFIX_FIELD.label = 2
SysSearch_Local_Var_Table.HPMATCHINGKEY_KEYPREFIX_FIELD.has_default_value = false
SysSearch_Local_Var_Table.HPMATCHINGKEY_KEYPREFIX_FIELD.default_value = ""
SysSearch_Local_Var_Table.HPMATCHINGKEY_KEYPREFIX_FIELD.type = 9
SysSearch_Local_Var_Table.HPMATCHINGKEY_KEYPREFIX_FIELD.cpp_type = 9

SysSearch_Local_Var_Table.HPMATCHINGKEY_COUNTLIMIT_FIELD.name = "countLimit"
SysSearch_Local_Var_Table.HPMATCHINGKEY_COUNTLIMIT_FIELD.full_name = ".HPMatchingKey.countLimit"
SysSearch_Local_Var_Table.HPMATCHINGKEY_COUNTLIMIT_FIELD.number = 3
SysSearch_Local_Var_Table.HPMATCHINGKEY_COUNTLIMIT_FIELD.index = 2
SysSearch_Local_Var_Table.HPMATCHINGKEY_COUNTLIMIT_FIELD.label = 1
SysSearch_Local_Var_Table.HPMATCHINGKEY_COUNTLIMIT_FIELD.has_default_value = false
SysSearch_Local_Var_Table.HPMATCHINGKEY_COUNTLIMIT_FIELD.default_value = 0
SysSearch_Local_Var_Table.HPMATCHINGKEY_COUNTLIMIT_FIELD.type = 5
SysSearch_Local_Var_Table.HPMATCHINGKEY_COUNTLIMIT_FIELD.cpp_type = 1

HPMATCHINGKEY.name = "HPMatchingKey"
HPMATCHINGKEY.full_name = ".HPMatchingKey"
HPMATCHINGKEY.nested_types = {}
HPMATCHINGKEY.enum_types = {}
HPMATCHINGKEY.fields = {SysSearch_Local_Var_Table.HPMATCHINGKEY_TYPE_FIELD, SysSearch_Local_Var_Table.HPMATCHINGKEY_KEYPREFIX_FIELD, SysSearch_Local_Var_Table.HPMATCHINGKEY_COUNTLIMIT_FIELD}
HPMATCHINGKEY.is_extendable = false
HPMATCHINGKEY.extensions = {}
SysSearch_Local_Var_Table.HPKEYINFORESULT_KEYPREFIX_FIELD.name = "keyPrefix"
SysSearch_Local_Var_Table.HPKEYINFORESULT_KEYPREFIX_FIELD.full_name = ".HPKeyInfoResult.keyPrefix"
SysSearch_Local_Var_Table.HPKEYINFORESULT_KEYPREFIX_FIELD.number = 1
SysSearch_Local_Var_Table.HPKEYINFORESULT_KEYPREFIX_FIELD.index = 0
SysSearch_Local_Var_Table.HPKEYINFORESULT_KEYPREFIX_FIELD.label = 2
SysSearch_Local_Var_Table.HPKEYINFORESULT_KEYPREFIX_FIELD.has_default_value = false
SysSearch_Local_Var_Table.HPKEYINFORESULT_KEYPREFIX_FIELD.default_value = ""
SysSearch_Local_Var_Table.HPKEYINFORESULT_KEYPREFIX_FIELD.type = 9
SysSearch_Local_Var_Table.HPKEYINFORESULT_KEYPREFIX_FIELD.cpp_type = 9

SysSearch_Local_Var_Table.HPKEYINFORESULT_KEYINFOS_FIELD.name = "keyInfos"
SysSearch_Local_Var_Table.HPKEYINFORESULT_KEYINFOS_FIELD.full_name = ".HPKeyInfoResult.keyInfos"
SysSearch_Local_Var_Table.HPKEYINFORESULT_KEYINFOS_FIELD.number = 2
SysSearch_Local_Var_Table.HPKEYINFORESULT_KEYINFOS_FIELD.index = 1
SysSearch_Local_Var_Table.HPKEYINFORESULT_KEYINFOS_FIELD.label = 3
SysSearch_Local_Var_Table.HPKEYINFORESULT_KEYINFOS_FIELD.has_default_value = false
SysSearch_Local_Var_Table.HPKEYINFORESULT_KEYINFOS_FIELD.default_value = {}
SysSearch_Local_Var_Table.HPKEYINFORESULT_KEYINFOS_FIELD.message_type = KEYINFO
SysSearch_Local_Var_Table.HPKEYINFORESULT_KEYINFOS_FIELD.type = 11
SysSearch_Local_Var_Table.HPKEYINFORESULT_KEYINFOS_FIELD.cpp_type = 10

HPKEYINFORESULT.name = "HPKeyInfoResult"
HPKEYINFORESULT.full_name = ".HPKeyInfoResult"
HPKEYINFORESULT.nested_types = {}
HPKEYINFORESULT.enum_types = {}
HPKEYINFORESULT.fields = {SysSearch_Local_Var_Table.HPKEYINFORESULT_KEYPREFIX_FIELD, SysSearch_Local_Var_Table.HPKEYINFORESULT_KEYINFOS_FIELD}
HPKEYINFORESULT.is_extendable = false
HPKEYINFORESULT.extensions = {}

HPKeyInfoResult = protobuf.Message(HPKEYINFORESULT)
HPMatchingKey = protobuf.Message(HPMATCHINGKEY)
HPUpdateKeyInfo = protobuf.Message(HPUPDATEKEYINFO)
KEY_INFO_RESULT = 63
KeyInfo = protobuf.Message(KEYINFO)
MATCHING_KEY = 61
UPDATE_KEY_DATA = 60

