-- Generated By protoc-gen-lua Do not Edit


local Talent_Local_Var_Table = {}

local protobuf = require "protobuf"
module('Talent_pb')


Talent_Local_Var_Table.TALENTTYPE = protobuf.EnumDescriptor();
Talent_Local_Var_Table.TALENTTYPE_TALENT_TYPE_DEFAULT_ENUM = protobuf.EnumValueDescriptor();
Talent_Local_Var_Table.TALENTTYPE_TALENT_TYPE_BACKUP_ENUM = protobuf.EnumValueDescriptor();
TALENTINFO = protobuf.Descriptor();
Talent_Local_Var_Table.TALENTINFO_ID_FIELD = protobuf.FieldDescriptor();
Talent_Local_Var_Table.TALENTINFO_TALENTID_FIELD = protobuf.FieldDescriptor();
Talent_Local_Var_Table.TALENTINFO_LEVEL_FIELD = protobuf.FieldDescriptor();
Talent_Local_Var_Table.TALENTINFO_TYPE_FIELD = protobuf.FieldDescriptor();
HPTALENTINFOSYNC = protobuf.Descriptor();
Talent_Local_Var_Table.HPTALENTINFOSYNC_TALENTINFOS_FIELD = protobuf.FieldDescriptor();
Talent_Local_Var_Table.HPTALENTINFOSYNC_TYPE_FIELD = protobuf.FieldDescriptor();
HPTALENTUPGRADEREQ = protobuf.Descriptor();
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TALENTID_FIELD = protobuf.FieldDescriptor();
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TARGETLEVEL_FIELD = protobuf.FieldDescriptor();
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TYPE_FIELD = protobuf.FieldDescriptor();
HPTALENTUPGRADERESP = protobuf.Descriptor();
Talent_Local_Var_Table.HPTALENTUPGRADERESP_RESULT_FIELD = protobuf.FieldDescriptor();
Talent_Local_Var_Table.HPTALENTUPGRADERESP_LEVEL_FIELD = protobuf.FieldDescriptor();
HPTALENTCLEARREQ = protobuf.Descriptor();
Talent_Local_Var_Table.HPTALENTCLEARREQ_USEGOLD_FIELD = protobuf.FieldDescriptor();
Talent_Local_Var_Table.HPTALENTCLEARREQ_TYPE_FIELD = protobuf.FieldDescriptor();
HPTALENTCHANGEREQ = protobuf.Descriptor();
Talent_Local_Var_Table.HPTALENTCHANGEREQ_USEGOLD_FIELD = protobuf.FieldDescriptor();
Talent_Local_Var_Table.HPTALENTCHANGEREQ_TYPE_FIELD = protobuf.FieldDescriptor();

Talent_Local_Var_Table.TALENTTYPE_TALENT_TYPE_DEFAULT_ENUM.name = "TALENT_TYPE_DEFAULT"
Talent_Local_Var_Table.TALENTTYPE_TALENT_TYPE_DEFAULT_ENUM.index = 0
Talent_Local_Var_Table.TALENTTYPE_TALENT_TYPE_DEFAULT_ENUM.number = 0
Talent_Local_Var_Table.TALENTTYPE_TALENT_TYPE_BACKUP_ENUM.name = "TALENT_TYPE_BACKUP"
Talent_Local_Var_Table.TALENTTYPE_TALENT_TYPE_BACKUP_ENUM.index = 1
Talent_Local_Var_Table.TALENTTYPE_TALENT_TYPE_BACKUP_ENUM.number = 1
Talent_Local_Var_Table.TALENTTYPE.name = "TalentType"
Talent_Local_Var_Table.TALENTTYPE.full_name = ".TalentType"
Talent_Local_Var_Table.TALENTTYPE.values = {}
Talent_Local_Var_Table.TALENTTYPE.values[1] = Talent_Local_Var_Table.TALENTTYPE_TALENT_TYPE_DEFAULT_ENUM;
Talent_Local_Var_Table.TALENTTYPE.values[2] = Talent_Local_Var_Table.TALENTTYPE_TALENT_TYPE_BACKUP_ENUM;
Talent_Local_Var_Table.TALENTINFO_ID_FIELD.name = "id"
Talent_Local_Var_Table.TALENTINFO_ID_FIELD.full_name = ".TalentInfo.id"
Talent_Local_Var_Table.TALENTINFO_ID_FIELD.number = 1
Talent_Local_Var_Table.TALENTINFO_ID_FIELD.index = 0
Talent_Local_Var_Table.TALENTINFO_ID_FIELD.label = 2
Talent_Local_Var_Table.TALENTINFO_ID_FIELD.has_default_value = false
Talent_Local_Var_Table.TALENTINFO_ID_FIELD.default_value = ""
Talent_Local_Var_Table.TALENTINFO_ID_FIELD.type = 9
Talent_Local_Var_Table.TALENTINFO_ID_FIELD.cpp_type = 9

Talent_Local_Var_Table.TALENTINFO_TALENTID_FIELD.name = "talentId"
Talent_Local_Var_Table.TALENTINFO_TALENTID_FIELD.full_name = ".TalentInfo.talentId"
Talent_Local_Var_Table.TALENTINFO_TALENTID_FIELD.number = 2
Talent_Local_Var_Table.TALENTINFO_TALENTID_FIELD.index = 1
Talent_Local_Var_Table.TALENTINFO_TALENTID_FIELD.label = 2
Talent_Local_Var_Table.TALENTINFO_TALENTID_FIELD.has_default_value = false
Talent_Local_Var_Table.TALENTINFO_TALENTID_FIELD.default_value = 0
Talent_Local_Var_Table.TALENTINFO_TALENTID_FIELD.type = 5
Talent_Local_Var_Table.TALENTINFO_TALENTID_FIELD.cpp_type = 1

Talent_Local_Var_Table.TALENTINFO_LEVEL_FIELD.name = "level"
Talent_Local_Var_Table.TALENTINFO_LEVEL_FIELD.full_name = ".TalentInfo.level"
Talent_Local_Var_Table.TALENTINFO_LEVEL_FIELD.number = 3
Talent_Local_Var_Table.TALENTINFO_LEVEL_FIELD.index = 2
Talent_Local_Var_Table.TALENTINFO_LEVEL_FIELD.label = 2
Talent_Local_Var_Table.TALENTINFO_LEVEL_FIELD.has_default_value = false
Talent_Local_Var_Table.TALENTINFO_LEVEL_FIELD.default_value = 0
Talent_Local_Var_Table.TALENTINFO_LEVEL_FIELD.type = 5
Talent_Local_Var_Table.TALENTINFO_LEVEL_FIELD.cpp_type = 1

Talent_Local_Var_Table.TALENTINFO_TYPE_FIELD.name = "type"
Talent_Local_Var_Table.TALENTINFO_TYPE_FIELD.full_name = ".TalentInfo.type"
Talent_Local_Var_Table.TALENTINFO_TYPE_FIELD.number = 4
Talent_Local_Var_Table.TALENTINFO_TYPE_FIELD.index = 3
Talent_Local_Var_Table.TALENTINFO_TYPE_FIELD.label = 2
Talent_Local_Var_Table.TALENTINFO_TYPE_FIELD.has_default_value = false
Talent_Local_Var_Table.TALENTINFO_TYPE_FIELD.default_value = 0
Talent_Local_Var_Table.TALENTINFO_TYPE_FIELD.type = 5
Talent_Local_Var_Table.TALENTINFO_TYPE_FIELD.cpp_type = 1

TALENTINFO.name = "TalentInfo"
TALENTINFO.full_name = ".TalentInfo"
TALENTINFO.nested_types = {}
TALENTINFO.enum_types = {}
TALENTINFO.fields = {Talent_Local_Var_Table.TALENTINFO_ID_FIELD, Talent_Local_Var_Table.TALENTINFO_TALENTID_FIELD, Talent_Local_Var_Table.TALENTINFO_LEVEL_FIELD, Talent_Local_Var_Table.TALENTINFO_TYPE_FIELD}
TALENTINFO.is_extendable = false
TALENTINFO.extensions = {}
Talent_Local_Var_Table.HPTALENTINFOSYNC_TALENTINFOS_FIELD.name = "talentInfos"
Talent_Local_Var_Table.HPTALENTINFOSYNC_TALENTINFOS_FIELD.full_name = ".HPTalentInfoSync.talentInfos"
Talent_Local_Var_Table.HPTALENTINFOSYNC_TALENTINFOS_FIELD.number = 1
Talent_Local_Var_Table.HPTALENTINFOSYNC_TALENTINFOS_FIELD.index = 0
Talent_Local_Var_Table.HPTALENTINFOSYNC_TALENTINFOS_FIELD.label = 3
Talent_Local_Var_Table.HPTALENTINFOSYNC_TALENTINFOS_FIELD.has_default_value = false
Talent_Local_Var_Table.HPTALENTINFOSYNC_TALENTINFOS_FIELD.default_value = {}
Talent_Local_Var_Table.HPTALENTINFOSYNC_TALENTINFOS_FIELD.message_type = TALENTINFO
Talent_Local_Var_Table.HPTALENTINFOSYNC_TALENTINFOS_FIELD.type = 11
Talent_Local_Var_Table.HPTALENTINFOSYNC_TALENTINFOS_FIELD.cpp_type = 10

Talent_Local_Var_Table.HPTALENTINFOSYNC_TYPE_FIELD.name = "type"
Talent_Local_Var_Table.HPTALENTINFOSYNC_TYPE_FIELD.full_name = ".HPTalentInfoSync.type"
Talent_Local_Var_Table.HPTALENTINFOSYNC_TYPE_FIELD.number = 2
Talent_Local_Var_Table.HPTALENTINFOSYNC_TYPE_FIELD.index = 1
Talent_Local_Var_Table.HPTALENTINFOSYNC_TYPE_FIELD.label = 2
Talent_Local_Var_Table.HPTALENTINFOSYNC_TYPE_FIELD.has_default_value = false
Talent_Local_Var_Table.HPTALENTINFOSYNC_TYPE_FIELD.default_value = 0
Talent_Local_Var_Table.HPTALENTINFOSYNC_TYPE_FIELD.type = 5
Talent_Local_Var_Table.HPTALENTINFOSYNC_TYPE_FIELD.cpp_type = 1

HPTALENTINFOSYNC.name = "HPTalentInfoSync"
HPTALENTINFOSYNC.full_name = ".HPTalentInfoSync"
HPTALENTINFOSYNC.nested_types = {}
HPTALENTINFOSYNC.enum_types = {}
HPTALENTINFOSYNC.fields = {Talent_Local_Var_Table.HPTALENTINFOSYNC_TALENTINFOS_FIELD, Talent_Local_Var_Table.HPTALENTINFOSYNC_TYPE_FIELD}
HPTALENTINFOSYNC.is_extendable = false
HPTALENTINFOSYNC.extensions = {}
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TALENTID_FIELD.name = "talentId"
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TALENTID_FIELD.full_name = ".HPTalentUpgradeReq.talentId"
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TALENTID_FIELD.number = 1
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TALENTID_FIELD.index = 0
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TALENTID_FIELD.label = 2
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TALENTID_FIELD.has_default_value = false
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TALENTID_FIELD.default_value = 0
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TALENTID_FIELD.type = 5
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TALENTID_FIELD.cpp_type = 1

Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TARGETLEVEL_FIELD.name = "targetLevel"
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TARGETLEVEL_FIELD.full_name = ".HPTalentUpgradeReq.targetLevel"
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TARGETLEVEL_FIELD.number = 2
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TARGETLEVEL_FIELD.index = 1
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TARGETLEVEL_FIELD.label = 2
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TARGETLEVEL_FIELD.has_default_value = false
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TARGETLEVEL_FIELD.default_value = 0
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TARGETLEVEL_FIELD.type = 5
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TARGETLEVEL_FIELD.cpp_type = 1

Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TYPE_FIELD.name = "type"
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TYPE_FIELD.full_name = ".HPTalentUpgradeReq.type"
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TYPE_FIELD.number = 3
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TYPE_FIELD.index = 2
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TYPE_FIELD.label = 2
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TYPE_FIELD.has_default_value = false
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TYPE_FIELD.default_value = 0
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TYPE_FIELD.type = 5
Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TYPE_FIELD.cpp_type = 1

HPTALENTUPGRADEREQ.name = "HPTalentUpgradeReq"
HPTALENTUPGRADEREQ.full_name = ".HPTalentUpgradeReq"
HPTALENTUPGRADEREQ.nested_types = {}
HPTALENTUPGRADEREQ.enum_types = {}
HPTALENTUPGRADEREQ.fields = {Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TALENTID_FIELD, Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TARGETLEVEL_FIELD, Talent_Local_Var_Table.HPTALENTUPGRADEREQ_TYPE_FIELD}
HPTALENTUPGRADEREQ.is_extendable = false
HPTALENTUPGRADEREQ.extensions = {}
Talent_Local_Var_Table.HPTALENTUPGRADERESP_RESULT_FIELD.name = "result"
Talent_Local_Var_Table.HPTALENTUPGRADERESP_RESULT_FIELD.full_name = ".HPTalentUpgradeResp.result"
Talent_Local_Var_Table.HPTALENTUPGRADERESP_RESULT_FIELD.number = 1
Talent_Local_Var_Table.HPTALENTUPGRADERESP_RESULT_FIELD.index = 0
Talent_Local_Var_Table.HPTALENTUPGRADERESP_RESULT_FIELD.label = 2
Talent_Local_Var_Table.HPTALENTUPGRADERESP_RESULT_FIELD.has_default_value = false
Talent_Local_Var_Table.HPTALENTUPGRADERESP_RESULT_FIELD.default_value = false
Talent_Local_Var_Table.HPTALENTUPGRADERESP_RESULT_FIELD.type = 8
Talent_Local_Var_Table.HPTALENTUPGRADERESP_RESULT_FIELD.cpp_type = 7

Talent_Local_Var_Table.HPTALENTUPGRADERESP_LEVEL_FIELD.name = "level"
Talent_Local_Var_Table.HPTALENTUPGRADERESP_LEVEL_FIELD.full_name = ".HPTalentUpgradeResp.level"
Talent_Local_Var_Table.HPTALENTUPGRADERESP_LEVEL_FIELD.number = 2
Talent_Local_Var_Table.HPTALENTUPGRADERESP_LEVEL_FIELD.index = 1
Talent_Local_Var_Table.HPTALENTUPGRADERESP_LEVEL_FIELD.label = 2
Talent_Local_Var_Table.HPTALENTUPGRADERESP_LEVEL_FIELD.has_default_value = false
Talent_Local_Var_Table.HPTALENTUPGRADERESP_LEVEL_FIELD.default_value = 0
Talent_Local_Var_Table.HPTALENTUPGRADERESP_LEVEL_FIELD.type = 5
Talent_Local_Var_Table.HPTALENTUPGRADERESP_LEVEL_FIELD.cpp_type = 1

HPTALENTUPGRADERESP.name = "HPTalentUpgradeResp"
HPTALENTUPGRADERESP.full_name = ".HPTalentUpgradeResp"
HPTALENTUPGRADERESP.nested_types = {}
HPTALENTUPGRADERESP.enum_types = {}
HPTALENTUPGRADERESP.fields = {Talent_Local_Var_Table.HPTALENTUPGRADERESP_RESULT_FIELD, Talent_Local_Var_Table.HPTALENTUPGRADERESP_LEVEL_FIELD}
HPTALENTUPGRADERESP.is_extendable = false
HPTALENTUPGRADERESP.extensions = {}
Talent_Local_Var_Table.HPTALENTCLEARREQ_USEGOLD_FIELD.name = "useGold"
Talent_Local_Var_Table.HPTALENTCLEARREQ_USEGOLD_FIELD.full_name = ".HPTalentClearReq.useGold"
Talent_Local_Var_Table.HPTALENTCLEARREQ_USEGOLD_FIELD.number = 1
Talent_Local_Var_Table.HPTALENTCLEARREQ_USEGOLD_FIELD.index = 0
Talent_Local_Var_Table.HPTALENTCLEARREQ_USEGOLD_FIELD.label = 2
Talent_Local_Var_Table.HPTALENTCLEARREQ_USEGOLD_FIELD.has_default_value = false
Talent_Local_Var_Table.HPTALENTCLEARREQ_USEGOLD_FIELD.default_value = false
Talent_Local_Var_Table.HPTALENTCLEARREQ_USEGOLD_FIELD.type = 8
Talent_Local_Var_Table.HPTALENTCLEARREQ_USEGOLD_FIELD.cpp_type = 7

Talent_Local_Var_Table.HPTALENTCLEARREQ_TYPE_FIELD.name = "type"
Talent_Local_Var_Table.HPTALENTCLEARREQ_TYPE_FIELD.full_name = ".HPTalentClearReq.type"
Talent_Local_Var_Table.HPTALENTCLEARREQ_TYPE_FIELD.number = 2
Talent_Local_Var_Table.HPTALENTCLEARREQ_TYPE_FIELD.index = 1
Talent_Local_Var_Table.HPTALENTCLEARREQ_TYPE_FIELD.label = 2
Talent_Local_Var_Table.HPTALENTCLEARREQ_TYPE_FIELD.has_default_value = false
Talent_Local_Var_Table.HPTALENTCLEARREQ_TYPE_FIELD.default_value = 0
Talent_Local_Var_Table.HPTALENTCLEARREQ_TYPE_FIELD.type = 5
Talent_Local_Var_Table.HPTALENTCLEARREQ_TYPE_FIELD.cpp_type = 1

HPTALENTCLEARREQ.name = "HPTalentClearReq"
HPTALENTCLEARREQ.full_name = ".HPTalentClearReq"
HPTALENTCLEARREQ.nested_types = {}
HPTALENTCLEARREQ.enum_types = {}
HPTALENTCLEARREQ.fields = {Talent_Local_Var_Table.HPTALENTCLEARREQ_USEGOLD_FIELD, Talent_Local_Var_Table.HPTALENTCLEARREQ_TYPE_FIELD}
HPTALENTCLEARREQ.is_extendable = false
HPTALENTCLEARREQ.extensions = {}
Talent_Local_Var_Table.HPTALENTCHANGEREQ_USEGOLD_FIELD.name = "useGold"
Talent_Local_Var_Table.HPTALENTCHANGEREQ_USEGOLD_FIELD.full_name = ".HPTalentChangeReq.useGold"
Talent_Local_Var_Table.HPTALENTCHANGEREQ_USEGOLD_FIELD.number = 1
Talent_Local_Var_Table.HPTALENTCHANGEREQ_USEGOLD_FIELD.index = 0
Talent_Local_Var_Table.HPTALENTCHANGEREQ_USEGOLD_FIELD.label = 2
Talent_Local_Var_Table.HPTALENTCHANGEREQ_USEGOLD_FIELD.has_default_value = false
Talent_Local_Var_Table.HPTALENTCHANGEREQ_USEGOLD_FIELD.default_value = false
Talent_Local_Var_Table.HPTALENTCHANGEREQ_USEGOLD_FIELD.type = 8
Talent_Local_Var_Table.HPTALENTCHANGEREQ_USEGOLD_FIELD.cpp_type = 7

Talent_Local_Var_Table.HPTALENTCHANGEREQ_TYPE_FIELD.name = "type"
Talent_Local_Var_Table.HPTALENTCHANGEREQ_TYPE_FIELD.full_name = ".HPTalentChangeReq.type"
Talent_Local_Var_Table.HPTALENTCHANGEREQ_TYPE_FIELD.number = 2
Talent_Local_Var_Table.HPTALENTCHANGEREQ_TYPE_FIELD.index = 1
Talent_Local_Var_Table.HPTALENTCHANGEREQ_TYPE_FIELD.label = 2
Talent_Local_Var_Table.HPTALENTCHANGEREQ_TYPE_FIELD.has_default_value = false
Talent_Local_Var_Table.HPTALENTCHANGEREQ_TYPE_FIELD.default_value = 0
Talent_Local_Var_Table.HPTALENTCHANGEREQ_TYPE_FIELD.type = 5
Talent_Local_Var_Table.HPTALENTCHANGEREQ_TYPE_FIELD.cpp_type = 1

HPTALENTCHANGEREQ.name = "HPTalentChangeReq"
HPTALENTCHANGEREQ.full_name = ".HPTalentChangeReq"
HPTALENTCHANGEREQ.nested_types = {}
HPTALENTCHANGEREQ.enum_types = {}
HPTALENTCHANGEREQ.fields = {Talent_Local_Var_Table.HPTALENTCHANGEREQ_USEGOLD_FIELD, Talent_Local_Var_Table.HPTALENTCHANGEREQ_TYPE_FIELD}
HPTALENTCHANGEREQ.is_extendable = false
HPTALENTCHANGEREQ.extensions = {}

HPTalentChangeReq = protobuf.Message(HPTALENTCHANGEREQ)
HPTalentClearReq = protobuf.Message(HPTALENTCLEARREQ)
HPTalentInfoSync = protobuf.Message(HPTALENTINFOSYNC)
HPTalentUpgradeReq = protobuf.Message(HPTALENTUPGRADEREQ)
HPTalentUpgradeResp = protobuf.Message(HPTALENTUPGRADERESP)
TALENT_TYPE_BACKUP = 1
TALENT_TYPE_DEFAULT = 0
TalentInfo = protobuf.Message(TALENTINFO)

