-- Generated By protoc-gen-lua Do not Edit


local Technology_Local_Var_Table = {}

local protobuf = require "protobuf"
module('Technology_pb')


HPTECHNOLOGYSYNC = protobuf.Descriptor();
Technology_Local_Var_Table.HPTECHNOLOGYSYNC_TECHID_FIELD = protobuf.FieldDescriptor();
LEVELUPTECHNOLOGYREQ = protobuf.Descriptor();
Technology_Local_Var_Table.LEVELUPTECHNOLOGYREQ_TECHID_FIELD = protobuf.FieldDescriptor();
Technology_Local_Var_Table.LEVELUPTECHNOLOGYREQ_USEGOLD_FIELD = protobuf.FieldDescriptor();

Technology_Local_Var_Table.HPTECHNOLOGYSYNC_TECHID_FIELD.name = "techId"
Technology_Local_Var_Table.HPTECHNOLOGYSYNC_TECHID_FIELD.full_name = ".HPTechnologySync.techId"
Technology_Local_Var_Table.HPTECHNOLOGYSYNC_TECHID_FIELD.number = 1
Technology_Local_Var_Table.HPTECHNOLOGYSYNC_TECHID_FIELD.index = 0
Technology_Local_Var_Table.HPTECHNOLOGYSYNC_TECHID_FIELD.label = 3
Technology_Local_Var_Table.HPTECHNOLOGYSYNC_TECHID_FIELD.has_default_value = false
Technology_Local_Var_Table.HPTECHNOLOGYSYNC_TECHID_FIELD.default_value = {}
Technology_Local_Var_Table.HPTECHNOLOGYSYNC_TECHID_FIELD.type = 5
Technology_Local_Var_Table.HPTECHNOLOGYSYNC_TECHID_FIELD.cpp_type = 1

HPTECHNOLOGYSYNC.name = "HPTechnologySync"
HPTECHNOLOGYSYNC.full_name = ".HPTechnologySync"
HPTECHNOLOGYSYNC.nested_types = {}
HPTECHNOLOGYSYNC.enum_types = {}
HPTECHNOLOGYSYNC.fields = {Technology_Local_Var_Table.HPTECHNOLOGYSYNC_TECHID_FIELD}
HPTECHNOLOGYSYNC.is_extendable = false
HPTECHNOLOGYSYNC.extensions = {}
Technology_Local_Var_Table.LEVELUPTECHNOLOGYREQ_TECHID_FIELD.name = "techId"
Technology_Local_Var_Table.LEVELUPTECHNOLOGYREQ_TECHID_FIELD.full_name = ".LevelUpTechnologyReq.techId"
Technology_Local_Var_Table.LEVELUPTECHNOLOGYREQ_TECHID_FIELD.number = 1
Technology_Local_Var_Table.LEVELUPTECHNOLOGYREQ_TECHID_FIELD.index = 0
Technology_Local_Var_Table.LEVELUPTECHNOLOGYREQ_TECHID_FIELD.label = 2
Technology_Local_Var_Table.LEVELUPTECHNOLOGYREQ_TECHID_FIELD.has_default_value = false
Technology_Local_Var_Table.LEVELUPTECHNOLOGYREQ_TECHID_FIELD.default_value = 0
Technology_Local_Var_Table.LEVELUPTECHNOLOGYREQ_TECHID_FIELD.type = 5
Technology_Local_Var_Table.LEVELUPTECHNOLOGYREQ_TECHID_FIELD.cpp_type = 1

Technology_Local_Var_Table.LEVELUPTECHNOLOGYREQ_USEGOLD_FIELD.name = "useGold"
Technology_Local_Var_Table.LEVELUPTECHNOLOGYREQ_USEGOLD_FIELD.full_name = ".LevelUpTechnologyReq.useGold"
Technology_Local_Var_Table.LEVELUPTECHNOLOGYREQ_USEGOLD_FIELD.number = 2
Technology_Local_Var_Table.LEVELUPTECHNOLOGYREQ_USEGOLD_FIELD.index = 1
Technology_Local_Var_Table.LEVELUPTECHNOLOGYREQ_USEGOLD_FIELD.label = 2
Technology_Local_Var_Table.LEVELUPTECHNOLOGYREQ_USEGOLD_FIELD.has_default_value = false
Technology_Local_Var_Table.LEVELUPTECHNOLOGYREQ_USEGOLD_FIELD.default_value = 0
Technology_Local_Var_Table.LEVELUPTECHNOLOGYREQ_USEGOLD_FIELD.type = 5
Technology_Local_Var_Table.LEVELUPTECHNOLOGYREQ_USEGOLD_FIELD.cpp_type = 1

LEVELUPTECHNOLOGYREQ.name = "LevelUpTechnologyReq"
LEVELUPTECHNOLOGYREQ.full_name = ".LevelUpTechnologyReq"
LEVELUPTECHNOLOGYREQ.nested_types = {}
LEVELUPTECHNOLOGYREQ.enum_types = {}
LEVELUPTECHNOLOGYREQ.fields = {Technology_Local_Var_Table.LEVELUPTECHNOLOGYREQ_TECHID_FIELD, Technology_Local_Var_Table.LEVELUPTECHNOLOGYREQ_USEGOLD_FIELD}
LEVELUPTECHNOLOGYREQ.is_extendable = false
LEVELUPTECHNOLOGYREQ.extensions = {}

HPTechnologySync = protobuf.Message(HPTECHNOLOGYSYNC)
LevelUpTechnologyReq = protobuf.Message(LEVELUPTECHNOLOGYREQ)

