local setting_conf = {
[15] ={
     id = 15,
     name = '@HelpShift',
     icon = 'Menu_Help.png',
     priority = 1,
     isshow = 1,
     helpShiftFAQS = 1
},
[2] ={
     id = 2,
     name = '@SettingMenu_Push',
     icon = 'item000.png',
     priority = 2,
     isshow = 0,
     pageName = 'RARankPage',
},
[3] ={
     id = 3,
     name = '@SettingMenu_About',
     icon = 'Menu_About.png',
     priority = 3,
     isshow = 1,
     helpShiftId = 15,
},
[4] ={
     id = 4,
     name = '@SettingMenu_Option',
     icon = 'Menu_Setting.png',
     priority = 4,
     isshow = 1,
     pageName = 'RASettingOptionPage',
},
[5] ={
     id = 5,
     name = '@SettingMenu_Search',
     icon = 'Menu_Search.png',
     priority = 5,
     isshow = 1,
     pageName = 'RASettingSearchPage',
},
[6] ={
     id = 6,
     name = '@SettingMenu_BlockList',
     icon = 'Menu_BlockList.png',
     priority = 6,
     isshow = 1,
     pageName = 'RASettingBlockPage',
},
[7] ={
     id = 7,
     name = '@SettingMenu_Lang',
     icon = 'Menu_LangChange.png',
     priority = 7,
     isshow = 1,
     pageName = 'RASettingLangPage',
},
[8] ={
     id = 8,
     name = '@SettingMenu_Account',
     icon = 'Menu_AccountChange.png',
     priority = 8,
     isshow = 1,
},
[9] ={
     id = 9,
     name = '@SettingMenu_Rank',
     icon = 'Menu_Rank.png',
     priority = 9,
     isshow = 1,
     pageName = 'RARankPage',
},
[10] ={
     id = 10,
     name = '@SettingMenu_ContactUs',
     icon = 'item000.png',
     priority = 10,
     isshow = 0,
},
[11] ={
     id = 11,
     name = '@SettingMenu_News',
     icon = 'item000.png',
     priority = 11,
     isshow = 0,
},
[12] ={
     id = 12,
     name = '@SettingMenu_BBS',
     icon = 'item000.png',
     priority = 12,
     isshow = 0,
},
[13] ={
     id = 13,
     name = '@SettingMenu_MessagePush',
     icon = 'Menu_MessagePush.png',
     priority = 13,
     isshow = 1,
     pageName = 'RASettingMessagePushPage',
},
[14] ={
     id = 14,
     name = '@SettingMenu_GooglePlay',
     icon = 'Menu_GooglePlay.png',
     priority = 14,
     isshow = 1,
     pageName = 'RASettingAccountBindPage',
}
}
return setting_conf
