local territory_building_conf = {
[100] ={
     id = 100,
     type = 1,
     level = 1,
     spine = 'GuildBuilding_Command',
     name = '@AllianceBastionName',
     gridCnt = 3,
     icon = 'Alliance_Build_Base.png',
     hudSound = 'hud_bastion'
},
[101] ={
     id = 101,
     type = 2,
     level = 1,
     spine = 'GuildBuilding_Bomb',
     name = '@AllianceSiloName',
     gridCnt = 3,
     icon = 'Alliance_Build_Nuclear.png',
     hudSound = 'hud_silo'
},
[102] ={
     id = 102,
     type = 3,
     level = 1,
     uraniumYield = 86400,
     spine = 'GuildBuilding_Uranium',
     name = '@AllianceUraniumName1',
     gridCnt = 3,
     icon = 'AA_1_5.png',
},
[103] ={
     id = 103,
     type = 3,
     level = 2,
     uraniumYield = 172800,
     spine = 'GuildBuilding_Uranium',
     name = '@AllianceUraniumName2',
     gridCnt = 3,
     icon = 'AA_2_5.png',
},
[104] ={
     id = 104,
     type = 4,
     level = 1,
     spine = 'WeatherController',
     name = '@AllianceWeatherName',
     gridCnt = 3,
     icon = 'Alliance_Build_SkyController.png',
},
[105] ={
     id = 105,
     type = 5,
     level = 1,
     nuclearPowerYield = 86400,
     spine = 'NuclearPowerPlant',
     name = '@AlliancePowerName1',
     gridCnt = 3,
     icon = 'AA_2_3.png',
},
[106] ={
     id = 106,
     type = 5,
     level = 2,
     nuclearPowerYield = 172800,
     spine = 'NuclearPowerPlant',
     name = '@AlliancePowerName2',
     gridCnt = 3,
     icon = 'AA_1_3.png',
},
[107] ={
     id = 107,
     type = 6,
     level = 1,
     hospitalRate1 = 500,
     hospitalRate2 = 500,
     spine = 'GuildBuilding_Hospital',
     name = '@AllianceHosptialName1',
     gridCnt = 2,
     icon = 'Alliance_Build_Haspital.png',
},
[108] ={
     id = 108,
     type = 6,
     level = 2,
     hospitalRate1 = 2000,
     hospitalRate2 = 2000,
     spine = 'GuildBuilding_Hospital',
     name = '@AllianceHosptialName2',
     gridCnt = 2,
     icon = 'Alliance_Build_Haspital.png',
},
[109] ={
     id = 109,
     type = 6,
     level = 3,
     hospitalRate1 = 4000,
     hospitalRate2 = 4000,
     spine = 'GuildBuilding_Hospital',
     name = '@AllianceHosptialName3',
     gridCnt = 2,
     icon = 'Alliance_Build_Haspital.png',
},
[110] ={
     id = 110,
     type = 6,
     level = 4,
     hospitalRate1 = 5000,
     hospitalRate2 = 5000,
     spine = 'GuildBuilding_Hospital',
     name = '@AllianceHosptialName4',
     gridCnt = 2,
     icon = 'Alliance_Build_Haspital.png',
},
[111] ={
     id = 111,
     type = 7,
     level = 1,
     spine = 'GuildBuilding_Shop',
     name = '@AllianceShopName',
     gridCnt = 2,
     icon = 'AA_2_2.png',
},
[112] ={
     id = 112,
     type = 8,
     level = 1,
     spine = 'GuildBuilding_SuperGold',
     name = '@AllianceSuperMineName',
     gridCnt = 2,
     icon = 'AA_2_2.png',
},
[113] ={
     id = 113,
     type = 9,
     level = 1,
     cannonRate = 20,
     spine = 215401,
     name = '@AllianceCanonName',
     gridCnt = 1,
     icon = 'Alliance_Build_Bombard.png',
},
[114] ={
     id = 114,
     type = 10,
     level = 1,
     spine = 'AllianceStatue',
     name = '@StatueName1',
     statuePicture = 'StatueIcon_Attack.png',
     gridCnt = 1,
     jumpInterface = 1,
     icon = 'AA_2_2.png',
},
[115] ={
     id = 115,
     type = 10,
     level = 1,
     spine = 'AllianceStatue',
     name = '@StatueName2',
     statuePicture = 'StatueIcon_Defence.png',
     gridCnt = 1,
     jumpInterface = 2,
     icon = 'AA_2_2.png',
},
[116] ={
     id = 116,
     type = 10,
     level = 1,
     spine = 'AllianceStatue',
     name = '@StatueName3',
     statuePicture = 'StatueIcon_Life.png',
     gridCnt = 1,
     jumpInterface = 3,
     icon = 'AA_2_2.png',
},
[117] ={
     id = 117,
     type = 10,
     level = 1,
     spine = 'AllianceStatue',
     name = '@StatueName4',
     statuePicture = 'StatueIcon_DefBuild.png',
     gridCnt = 1,
     jumpInterface = 4,
     icon = 'AA_2_2.png',
},
[118] ={
     id = 118,
     type = 10,
     level = 1,
     spine = 'AllianceStatue',
     name = '@StatueName5',
     statuePicture = 'StatueIcon_BuildSpeedUp.png',
     gridCnt = 1,
     jumpInterface = 5,
     icon = 'AA_2_2.png',
},
[119] ={
     id = 119,
     type = 10,
     level = 1,
     spine = 'AllianceStatue',
     name = '@StatueName6',
     statuePicture = 'StatueIcon_TechSpeedUp.png',
     gridCnt = 1,
     jumpInterface = 6,
     icon = 'AA_2_2.png',
},
[120] ={
     id = 120,
     type = 10,
     level = 1,
     spine = 'AllianceStatue',
     name = '@StatueName7',
     statuePicture = 'StatueIcon_Res.png',
     gridCnt = 1,
     jumpInterface = 7,
     icon = 'AA_2_2.png',
},
[121] ={
     id = 121,
     type = 10,
     level = 1,
     spine = 'AllianceStatue',
     name = '@StatueName8',
     statuePicture = 'StatueIcon_Gather.png',
     gridCnt = 1,
     jumpInterface = 8,
     icon = 'AA_2_2.png',
},
[122] ={
     id = 122,
     type = 11,
     level = 1,
     spine = 'GuildBuilding_Bomb',
     name = '@AllianceSiloPlatformName',
     gridCnt = 3,
     icon = 'Alliance_Build_Nuclear.png',
},
[123] ={
     id = 123,
     type = 11,
     level = 1,
     spine = 'WeatherController',
     name = '@AllianceWeatherPlatformName',
     gridCnt = 3,
     icon = 'Alliance_Build_SkyController.png',
}
}
return territory_building_conf
